// Oblivio translations — zh
window._oblivioLang = {
// Navigation
        nav_home: '首页',
        nav_features: '功能',
        nav_philosophy: '理念',
        nav_journey: '旅程',
        nav_login: '登录',
        nav_signup: '注册',
        nav_logout: '退出登录',
        nav_back: '← 返回',
        nav_back_home: '← 返回首页',

        // Hero Section
        hero_subtitle: '一份跨越世代的数字遗产。留存你的本真，分享你的智慧，留下的不仅仅是回忆。',
        hero_cta: '立即开始',

        // Features Section
        features_title: '留存生命的精华',
        features_subtitle: '你的遗产，三步成就。',
        feature1_title: '注册账号',
        feature1_desc: '几分钟即可完成账号设置。你的数据采用端到端加密存储——只有你自己可以访问。',
        feature2_title: '讲述你的故事',
        feature2_desc: '让我们的传记师引导你走过生命中的每一章——从日常点滴和珍贵回忆，到你最深层的价值观和人生智慧。',
        feature3_title: '分享你的 Oblivio',
        feature3_desc: '给你最亲近的人一份经久不衰的礼物——一份鲜活的遗产，将你的声音、你的价值观和你的爱，留存在生命之外。',

        // Philosophy Section
        philosophy_title: '不止于记忆',
        philosophy_p1: 'Oblivio 不仅仅是事实和数据的存储库。它是一份鲜活的遗产，一个让你的个性、价值观和爱永远存在的地方。',
        philosophy_p2: '我们相信，每个人都拥有值得被保存的独特智慧。为了子女、孙辈，以及所有在我们之后到来的人。',
        philosophy_p3: '时光流逝，但最重要的东西会留下。',

        // Journey Page
        journey_welcome: '欢迎来到 Oblivio',
        journey_subtitle: '你今天想做什么？',
        journey_card1_label: '为你自己',
        journey_card1_title: '讲述你的故事',
        journey_card1_desc: '分享你的回忆、经历和人生智慧。我们的传记师会温柔地引导你，帮你记录下个人故事，作为留给你最重要的人的遗产。',
        journey_card1_cta: '开始对话',
        journey_card2_label: '为你的亲人',
        journey_card2_title: '体验一份遗产',
        journey_card2_desc: '与一个特别的人留下的遗产对话。聆听他们的故事，发现他们的智慧，在你需要的时候感受他们的存在。',
        journey_card2_cta: '开始对话',
        journey_coming_soon: '即将推出',

        // Login Page
        login_title: '欢迎回来',
        login_subtitle: '登录以继续你的旅程',
        login_email: '邮箱',
        login_password: '密码',
        login_button: '登录',
        login_signing_in: '正在登录...',
        login_no_account: '还没有账号？',
        login_create_here: '在这里创建',
        login_success: '登录成功！正在跳转...',

        // Signup Page
        signup_title: '创建账号',
        signup_subtitle: '今天就开始你的遗产之旅',
        signup_name: '姓名',
        signup_name_placeholder: '你的全名',
        signup_email: '邮箱',
        signup_email_placeholder: 'your@email.com',
        signup_password: '密码',
        signup_password_placeholder: '创建一个强密码',
        signup_password_req: '至少6个字符',
        signup_confirm: '确认密码',
        signup_confirm_placeholder: '再次输入密码',
        signup_button: '创建账号',
        signup_creating: '正在创建账号...',
        signup_have_account: '已经有账号了？',
        signup_signin_here: '在这里登录',
        signup_success: '账号创建成功！正在跳转到登录页面...',
        signup_error_match: '两次输入的密码不一致',
        signup_error_length: '密码长度至少为6个字符',

        // Biographer Page
        bio_title: '传记师',
        bio_subtitle: '让我们一起留存你的故事',
        bio_input_placeholder: '在这里输入你的回答...',
        bio_send: '发送',
        bio_complete_title: '传记已完成',
        bio_complete: '感谢你与我分享你的故事。你的遗产正在精心准备中 — Dennis会在一切准备就绪后与你联系。',

        // Biographer Questions
        bio_q1: '你好！我是传记师，我在这里帮助你留存你的遗产。你叫什么名字？',
        bio_q2: '跟我聊聊你的童年吧。你在哪里长大的？你最美好的回忆是什么？',
        bio_q3: '你生命中最重要的价值观是什么？哪些原则指引着你的决定？',
        bio_q4: '谁对你的人生影响最大？他们是如何塑造了今天的你？',
        bio_q5: '你一生中最引以为豪的成就是什么？',
        bio_q6: '你学到了哪些希望传给后代的人生经验？',
        bio_q7: '如果你能给你的亲人一条建议，你会说什么？',
        bio_q8: '什么给你带来了生命中最大的快乐？',
        bio_q9: '关于你的人生故事，还有什么想分享的吗？',

        // Language Selection Modal
        lang_modal_title: '选择你的语言',
        lang_modal_subtitle: '选择你与传记师对话时使用的语言',
        lang_modal_continue: '继续',

        // Footer
        footer_tagline: '留存那些不可遗忘的。<br>一份永恒的遗产。',
        footer_product: '产品',
        footer_features: '功能',
        footer_pricing: '价格',
        footer_security: '安全',
        footer_faq: '常见问题',
        footer_company: '关于我们',
        footer_about: '关于 Oblivio',
        footer_blog: '博客',
        footer_careers: '招聘',
        footer_press: '媒体',
        footer_legal: '法律',
        footer_privacy: '隐私',
        footer_terms: '使用条款',
        footer_imprint: '版本说明',
        footer_contact: '联系我们',
        footer_rights: '© 2026 Oblivio. 保留所有权利。',
        footer_tech: '技术',

        // Nav sub-page links
        nav_tech_link: '技术',
        nav_about_link: '关于 Oblivio',
        nav_start_link: '开始',

        // Security page
        sec_label: '安全',
        sec_h1: '你的故事<br>只属于你自己。',
        sec_sub: '你与 Oblivio 分享的内容是你最私密的东西。我们对此严肃以待。',
        sec_c1_title: '加密',
        sec_c1_desc: '所有连接均采用 TLS 加密。数据在 Supabase 中以静态加密方式存储。没有人能以明文方式读取。',
        sec_c2_title: '行级安全',
        sec_c2_desc: 'Supabase RLS 确保每次数据库查询只返回你自己的数据，从技术上杜绝了访问他人记录的可能。',
        sec_c3_title: 'JWT 身份验证',
        sec_c3_desc: '你的账号访问由签名的 JSON Web Tokens 保护。过期或无效的令牌会被自动拒绝。',
        sec_c4_title: '瑞士基础设施',
        sec_c4_desc: '前端通过经认证的瑞士托管商运营。瑞士数据保护法 (revDSG) 作为所有数据处理的最低标准。',
        sec_c5_title: '无追踪，无广告',
        sec_c5_desc: 'Oblivio 不使用广告追踪器，不使用第三方分析服务，不向任何人出售用户数据。',
        sec_c6_title: '删除权',
        sec_c6_desc: '你可以随时请求删除你的数据。你的账号、对话和遗产将被完全且不可逆地移除。',
        sec_auth_title: '身份验证与访问',
        sec_auth_p1: '访问 Oblivio 仅通过经验证的邮箱地址加上自设密码。密码永不以明文存储。Supabase Auth 使用基于 <strong>bcrypt</strong> 的哈希算法，这是最安全的密码存储标准之一。',
        sec_auth_p2: '会话通过短期有效的 JWT 令牌管理。经过一定时间后，令牌会自动刷新或失效，因此过期的会话无法获得访问权限。',
        sec_auth_box: '<strong>行级安全 (RLS)</strong> 已在所有表上启用。这意味着：即使应用逻辑出现技术错误，数据库在服务器层面也会确保没有用户能访问其他用户的数据。',
        sec_dm_title: '数据最小化',
        sec_dm_p1: 'Oblivio 只收集服务所必需的数据：姓名、邮箱地址、语言偏好以及你与传记师的对话内容。不会收集超出技术必要范围的位置数据、设备指纹、行为模式或其他元数据。',
        sec_dm_p2: '对话内容仅用于生成你的遗产，不会进行任何其他分析、第三方 AI 模型训练或共享。',
        sec_ai_title: 'AI 请求',
        sec_ai_p: '对话内容会传输到 OpenAI GPT API 进行处理。OpenAI 已通过合同承诺不使用商业客户的 API 请求来训练其模型。传输全程加密 (TLS 1.3)，且仅在处理期间进行，OpenAI 不会永久存储。',

        // Pricing page
        price_label: '价格',
        price_h1: '梦想不应该<br>寄账单。',
        price_sub: 'Oblivio 现在和将来对每位用户都是免费的。以下是背后的真实故事。',
        price_s1_title: 'API 的真相',
        price_s1_p1: '与传记师的每次对话背后都有真实的成本。你写的每条消息都会传送到 OpenAI 的数据中心，并以一个体贴、富有同理心的回复返回。每段存储的记忆都会占用 Supabase 服务器的空间。每次对 PROMISE AI 的调用都会消耗 Railway 的计算资源。',
        price_s1_p2: '这些不是假设的成本，而是每次对话都会产生的真实 API 费用：',
        price_cost1_title: 'OpenAI (GPT API)',
        price_cost1_desc: '每个对话模块都会产生令牌费用，具体取决于对话深度和系统上下文的长度。',
        price_cost2_title: 'Supabase',
        price_cost2_desc: '数据库查询、身份验证，以及对话历史和遗产的存储。',
        price_cost3_title: 'Railway',
        price_cost3_desc: 'PROMISE 后端服务的持续运行，在并发用户下计算密集。',
        price_cost4_title: '网站托管 (瑞士)',
        price_cost4_desc: '通过 oblivio.ch 域名托管和分发前端。',
        price_s2_title: '为什么还是免费的？',
        price_s2_p1: 'Oblivio 是一个热情项目，诞生于一个简单的信念，而非商业计划：<em>每个人都值得被倾听和铭记。</em>不仅仅是那些买得起昂贵软件的人。',
        price_s2_p2: '记录自己的一生、为后代留存自己的声音、传承自己的智慧：这不是奢侈品，而是一种深层的人类需求。Oblivio 希望成为满足这一需求的地方，无论银行账户余额多少。',
        price_s2_p3: '在目前作为 ZHAW 学术研究项目的阶段，运营费用由开发者承担。重要的是体验，而它应当是完整的、不受限制的、有尊严的。',
        price_plan_label: '当前方案',
        price_plan_name: 'Oblivio 免费版',
        price_plan_price: 'CHF 0',
        price_plan_per: '/ 月',
        price_plan_desc: '完整使用传记师、全部 10 个对话模块、自动遗产存储和数字遗产，没有任何限制。',
        price_inc1: '10 个对话模块',
        price_inc2: '自动知识存储',
        price_inc3: '数字遗产',
        price_inc4: '全部 8 种语言',
        price_inc5: '安全加密',
        price_inc6: '无广告',
        price_footnote: 'Oblivio 正在积极开发中。未来的功能，例如使用 ElevenLabs 进行语音克隆或与亲属继续对话，也将秉承这一承诺推出：有尊严、用心、尽可能让每个人都能使用。',

        // FAQ page
        faq_label: '常见问题',
        faq_h1: '常见问题<br>解答',
        faq_sub: '关于 Oblivio 你想知道的一切，清晰坦诚地回答。',
        faq_cat1: '综合',
        faq_q1: '什么是 Oblivio？',
        faq_a1: 'Oblivio 是一个数字平台，你可以在 AI 传记师的引导下记录你的人生。由此产生的对话、感悟和回忆将作为数字遗产保存，你的亲人未来可以体验。',
        faq_q2: 'Oblivio 适合谁？',
        faq_a2: '适合任何有故事要讲的人——也就是每一个人。Oblivio 尤其面向那些希望为子女、孙辈和后代留存智慧、回忆和个性的人。',
        faq_q3: '传记师是如何工作的？',
        faq_a3: '传记师会引导你完成十个主题对话模块，从日常生活、情感回忆、人际关系、价值观一直到你的遗产。每个模块都是一次深度对话，在收集到足够有意义的信息后自动总结并保存。',
        faq_q4: 'Oblivio 支持哪些语言？',
        faq_a4: 'Oblivio 目前支持八种语言：德语、英语、法语、意大利语、土耳其语、韩语、日语和中文。您在第一次对话开始时选择传记作家的语言。之后传记作家将始终以该语言进行交流。',
        faq_cat2: '对话与传记师',
        faq_q5: '共有多少个对话模块？',
        faq_a5: '共有十个模块：日常生活、情感、回忆、人际关系、个人成长、梦想、价值观、遗产、个人寄语和结束语。每个模块专注于生活的一个领域，只有在传记师收集到足够深入的回答后才会完成。',
        faq_q6: '我可以暂停并恢复对话吗？',
        faq_a6: '可以。你的对话记录会自动保存在 Supabase 中。当你再次登录时，你将从上次离开的地方继续，包括当前的对话模块。',
        faq_q7: '完成全部 10 个模块后会发生什么？',
        faq_a7: '完成全部十个模块后，你的完整数字遗产会自动保存。它包含了所有对话中提取的总结性见解。在未来的版本中，亲属将能够与这份遗产进行对话。',
        faq_q8: '传记师真的在倾听，还是标准文本？',
        faq_a8: '传记师由 OpenAI 的 GPT 语言模型驱动。它会阅读你写的每一句话，记住整个对话的上下文，并提出真正回应你所说内容的后续问题。这不是填表，而是一场真正的对话。',
        faq_cat3: '隐私与安全',
        faq_q9: '谁能阅读我的对话？',
        faq_a9: '只有你自己。Supabase 行级安全确保每次数据库查询在技术上仅限于你自己的数据。没有管理员、开发者或其他用户可以查看你的对话内容。',
        faq_q10: '我的数据会被用于 AI 训练吗？',
        faq_a10: '不会。OpenAI 已通过合同承诺不使用商业客户的 API 请求来训练模型。你的对话内容仅用于生成回复，之后不会被存储。',
        faq_q11: '我可以删除我的数据吗？',
        faq_a11: '可以，随时都可以。发送邮件至 <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>，主题为"数据删除"，你的所有数据将被完全且不可逆地移除。',
        faq_cat4: '费用',
        faq_q12: 'Oblivio 真的免费吗？',
        faq_a12: '是的。Oblivio 是 ZHAW 的学术研究项目，对所有用户完全免费，没有隐藏费用、没有免费增值限制、没有广告。更多信息请查看<a href="pricing.html">价格页面</a>。',
        faq_q13: 'Oblivio 会永久免费吗？',
        faq_a13: '这是我们的意愿。由于 Oblivio 是作为本科毕业论文创建的，运营成本可控。如果项目发展壮大，任何商业模式的变更都会透明地进行沟通。',

        // Features / Technology page
        tech_label: '技术',
        tech_h1: '永恒的<br>架构',
        tech_sub: 'Oblivio 将前沿研究与精心设计的基础设施相结合，让每一个故事都被安全保存，每一场对话都充满生机，每一份遗产都永久可访问。',
        tech_intro: 'Oblivio 的背后没有现成的解决方案，而是精心选择的技术，它们共同构建了一个兼顾尊严、安全与深度的系统。',
        tech_01_sub: '对话式 AI 框架',
        tech_01_title: 'PROMISE',
        tech_01_p: 'PROMISE 是来自 <strong>ZHAW——苏黎世应用科学大学</strong> 的科学框架，支持基于状态的多步骤 AI 对话。Oblivio 的传记师完全构建于 PROMISE 之上：十个主题对话模块中的每一个都是独立的状态，拥有自己的系统上下文、转换条件和自动知识提取。后端服务通过 <strong>Railway</strong> 提供，并可随时扩展访问。',
        tech_01_tag1: 'ZHAW 研究',
        tech_01_tag2: '有状态 AI',
        tech_02_sub: '语言模型',
        tech_02_title: 'OpenAI 的 GPT',
        tech_02_p: '传记师的对话由 <strong>OpenAI 的 GPT 语言模型</strong> 驱动。OpenAI 的模型在海量人类语言数据上训练，能够进行上下文敏感、富有同理心的对话。这使得 Oblivio 的对话不会感觉机械，而像一个用心的倾听者：耐心、敏锐，始终关注着这个人。',
        tech_02_tag1: 'OpenAI',
        tech_02_tag2: 'GPT',
        tech_03_sub: '数据库与身份验证',
        tech_03_title: 'Supabase',
        tech_03_p: '所有用户数据、对话历史和存储的遗产都保存在 <strong>Supabase</strong> 中，这是一个开源的 PostgreSQL 平台，具备行级安全 (RLS)。这意味着：没有用户能访问他人的数据——无论是通过错误还是漏洞。身份验证通过加密的 JWT 令牌进行，所有连接均受 TLS 保护。',
        tech_03_tag1: 'PostgreSQL',
        tech_03_tag2: '行级安全',
        tech_04_sub: '后端基础设施',
        tech_04_title: 'Railway',
        tech_04_p: 'PROMISE 后端服务运行在 <strong>Railway</strong> 上，这是一个现代化的云平台，集自动部署、扩展和监控于一体。传记师系统的每次更改都能在几分钟内上线，无需手动配置服务器。Railway 确保 Oblivio 即使在高负载下也能可靠访问。',
        tech_04_tag1: '自动部署',
        tech_04_tag2: '云基础设施',
        tech_05_sub: '语音合成 · 计划中',
        tech_05_title: 'ElevenLabs',
        tech_05_p: '在 Oblivio 的未来版本中，每份数字遗产不仅可以阅读，还可以<em>聆听</em>。借助 <strong>ElevenLabs</strong>，这一领先的逼真语音合成平台，将可以录制和克隆自己的声音。亲属届时不仅可以阅读文字消息，还能再次听到亲人熟悉的声音。',
        tech_05_tag1: '语音克隆',
        tech_05_tag2: '2026 年路线图',
        tech_06_sub: '网站托管',
        tech_06_title: '瑞士网站托管',
        tech_06_p: 'Oblivio 的前端通过知名的瑞士托管商运营。域名 <em>oblivio.ch</em> 和所有静态资源直接从瑞士分发。这意味着：数据留在瑞士，受瑞士数据保护法 (DSG) 约束，并享有优质的网络基础设施。',
        tech_06_tag1: '瑞士托管',
        tech_06_tag2: '符合 DSG 标准',
        tech_arch_title: '它们如何协同工作',
        tech_arch_lead: '从你的输入到存储的记忆：每一步都经过深思熟虑和安全保障。',
        tech_flow1_title: '输入',
        tech_flow1_p: '你在浏览器中输入一条消息，通过 HTTPS 加密传输。',
        tech_flow2_title: 'PROMISE 处理',
        tech_flow2_p: 'Railway 后端服务接收消息，确定当前状态，并将其发送到 OpenAI GPT。',
        tech_flow3_title: 'GPT 回复',
        tech_flow3_p: '语言模型根据传记师当前的状态生成一个富有同理心、上下文敏感的回复。',
        tech_flow4_title: 'Supabase 存储',
        tech_flow4_p: '对话和提取的见解安全地存储在你的个人 Supabase 实例中，只有你自己可以访问。',

        // Contact page
        contact_label: '联系我们',
        contact_h1: '保持<br>联系。',
        contact_li_title: 'Dennis Riccardo',
        contact_li_sub: 'Oblivio 创建者 · ZHAW 学生',
        contact_li_cta: '访问主页',
        contact_em_title: '邮箱',
        contact_em_addr: 'riccaden@students.zhaw.ch',
        contact_info: '<strong>学术背景：</strong>Oblivio 是 <strong>ZHAW</strong>——苏黎世应用科学大学的本科毕业论文。欢迎提出问题、反馈或合作建议。',

        // About page
        about_label: '关于 Oblivio',
        about_h1: '一个人。<br>一个想法。<br>一份遗产。',
        about_sub: 'Oblivio 源于一个信念：每个人都值得被倾听和铭记，远远超越自己的一生。',
        about_badge: '本科毕业论文',
        about_inst: '<strong>ZHAW——苏黎世应用科学大学</strong> · 管理与法律学院 · 商业信息学 · 2026',
        about_role: '开发者 · 学生',
        about_bio1: '我在温特图尔的 ZHAW 学习商业信息学，这个专业从一开始就深深吸引了我，因为它连接了我热爱的两个世界：技术的逻辑精确和商业的战略思维。',
        about_bio2: '同时，我在瑞士最大的健康保险公司之一担任项目经理。在那里，我每天都在学习如何组织复杂的系统、如何领导团队、如何可持续地推动变革。那是一个非常关注关怀和真实个体福祉的世界。',
        about_bio3: 'Oblivio 是我的毕业论文。但不仅如此：它是一个将我所代表的一切汇聚在一起的项目。技术实现包括 AI 和现代基础设施。人文关怀则包括对话、回忆，以及跨越时间连接的需要。还有一个信念：技术应该服务于人，而不是反过来。',
        about_bio4: '我做 Oblivio 的目标是打造一个不仅能运作，而且让人感觉对的东西。一个以尊严对待最私密之事的平台：一个人自己的一生。',
        about_values_title: 'Oblivio 的驱动力',
        about_v1_title: '尊严',
        about_v1_p: '每一个故事都值得被尊重对待——不是作为一个数据点，而是作为一个人的毕生心血。',
        about_v2_title: '可及性',
        about_v2_p: '留存自己的一生不应该是金钱问题。Oblivio 是免费的，而且是刻意为之。',
        about_v3_title: '深度',
        about_v3_p: '肤浅的回答只会留下肤浅的记忆。传记师会持续追问，直到最重要的东西浮出水面。',

        // Blog page
        blog_label: '博客',
        blog_h1: 'Oblivio<br>是如何诞生的。',
        blog_sub: '从创意到平台之路上的决策、弯路和洞见的真实记录。',
        blog_date: '2026 年春',
        blog_tag1: '本科毕业论文',
        blog_tag2: '开发',
        blog_art_h2: '从想法到鲜活的平台：Oblivio 的开发故事',
        blog_art_lead: '当你开始问自己：一个人离去后留下了什么？Oblivio 从这个问题开始，最终得到了一个包含比我最初预想更多技术决策的答案。',
        blog_h3_1: '最初的问题',
        blog_p1_1: 'Oblivio 的创意不是在书桌前诞生的，而是在一个个人沉思的时刻：如果有一个我已经失去的人，我还想问他们什么？反过来：当我不在了，我自己想留下什么？',
        blog_p1_2: '这些问题引导我走向了毕业论文。目标很有雄心：一个由 AI 驱动的平台，让每个人都能以数字遗产的形式记录自己的一生——深刻、私人、持久。',
        blog_quote: '"不是表格。不是问卷。而是一场真正在倾听的对话。"',
        blog_h3_2: 'PROMISE：核心',
        blog_p2_1: 'Oblivio 的技术骨干是 <strong>PROMISE</strong>，一个在 ZHAW 开发的基于状态的对话框架。与简单的聊天机器人序列不同，PROMISE 实现了真正的对话状态：十个传记师模块中的每一个都是独立的状态，拥有自己的系统上下文、转换条件和自动知识提取。',
        blog_p2_2: '核心挑战是：模块何时切换到下一个？第一个方案是双重条件：用户必须明确说"继续"，且守卫必须确认已覆盖足够多的话题。这听起来合理，但导致了一个严重的 bug。',
        blog_technote: '<strong>Bug：</strong> <code>Transition(List.of(trigger, guard), ...)</code>——AND 逻辑。当用户在长时间对话后说"不"(Trigger = true)(Guard = true)时，<code>TransferUtterancesAction</code> 被触发——由于整个对话历史被转移到所有后续状态，所有守卫同时判定为 true。模块 1 直接跳到"传记完成"。<br><br><strong>解决方案：</strong> <code>Transition(List.of(guard), ...)</code>——仅守卫。无触发器。一旦收集到足够有意义的回答，切换就会自动发生。',
        blog_h3_3: '十个模块而非一个',
        blog_p3_1: '传记师的原始版本是一个单一状态——一个没有结构的无尽对话流。问题在于：没有主题引导，很多生活领域都被忽略了。用户谈论童年记忆，却从不谈论价值观。谈论工作，却从不谈论梦想。',
        blog_p3_2: '解决方案是切换到十个主题模块：Ice-Breaker (Geschmack & Vorlieben)、Alltag & Lebenswelt、Kommunikationsstil、Erinnerungen & Schlüsselerlebnisse、Emotionen & Beziehungsmuster、Beziehungen & Fremdbild、Werte & Überzeugungen、Macken & Widersprüche、Vermächtnis & Zukunft 和 Abschluss。每个模块旨在充分探索生活的特定领域，完成后才自动切换到下一个。',
        blog_h3_4: '前端：功能与尊严之间',
        blog_p4_1: 'Oblivio 的设计遵循一个明确的前提：它不应该感觉像一个应用程序，而应该像一封信。色彩方案（奶油色、炭灰色、铁锈红、苔绿色）经过精心选择，传达温暖和永恒。字体 Crimson Pro 和 DM Serif Display 为界面注入了文学气质。',
        blog_p4_2: '进度条在模块 1 之后出现，陪伴用户从模块 1 到模块 10，是一个微小但意义重大的用户体验决策：可见的进度提供方向感，又不会打断对话。其状态保存在 <code>localStorage</code> 中，刷新后依然保留。',
        blog_h3_5: '模块 0 问卷',
        blog_p5_1: '在正式传记开始之前，用户会完成一份简短问卷：姓名、年龄段、性别、婚姻状况、性格特征和沟通风格。这些信息作为上下文传递给传记师，使其知道面对的是谁，从而调整语气、问题和反应。',
        blog_p5_2: '这个"模块 0"支持七种语言（德语、英语、法语、意大利语、韩语、日语和中文），设计得快速、不打扰且真诚。之前的知情同意书清楚地说明了存储了什么以及为什么。',
        blog_h3_6: 'Supabase、Railway 和瑞士托管',
        blog_p6_1: 'Oblivio 的基础设施遵循一个简单原则：每个组件都应该是其类别中最好的，彼此协作良好，且不增加不必要的复杂性。Supabase 负责身份验证和数据库。Railway 负责 PROMISE 后端服务，每次 git push 自动部署。瑞士服务商负责前端托管。',
        blog_p6_2: 'Railway 尤其有价值：Java 后端的每次更改（新守卫、新提示词、新语言支持）都能在几分钟内上线。这极大地提高了迭代速度。',
        blog_h3_7: '已经取得的成就',
        blog_p7_1: 'Oblivio 已经超越了最初的愿景：遗产聊天功能已经上线——亲属可以通过访问代码与存储的遗产进行对话。ElevenLabs 语音合成赋予传记师一个可以聆听的声音，借助 Web Speech API，用户还可以通过语音输入口述他们的回答。',
        blog_p7_2: 'Oblivio 已经完成，但远未终结。它是一个随着每一次对话而变得更加丰富的平台。',
        blog_date_v2: '2026年5月9日',
        blog_tag_v2_1: '更新',
        blog_tag_v2_2: '迭代',
        blog_v2_h2: '从四种语言到八种语言：重大改版',
        blog_v2_lead: '在过去的几周里，Oblivio 成长了。不仅是人物角色的数量，还有其功能的深度。以下是最重要变化的概览。',
        blog_v2_h3_1: '从四种语言扩展到八种',
        blog_v2_p1: 'Oblivio 现在支持八种语言：德语、英语、法语、意大利语、土耳其语、韩语、日语和中文。为了进一步扩大国际影响力，土耳其语作为第八种语言被加入。为此，所有界面文本、传记师问卷和模块指令都得到了补充。',
        blog_v2_h3_2: '三种对话变体',
        blog_v2_p2_1: '现在可以通过三种不同的模式与遗产人物角色进行交流：变体 1 包含完整的性格分析，配有雷达图、沟通 DNA 和生活模式。变体 2 让人物角色主动开启对话。变体 3 静静地等待访客的第一条消息。',
        blog_v2_p2_2: '每种变体适合不同的情感场景：深入理解、低入门门槛或对对话开始方式的完全掌控。',
        blog_v2_h3_3: '自动上下文压缩',
        blog_v2_p3: 'PROMISE 后端的技术改进：在二十条用户消息之后，较早的对话贡献会被自动总结并替换为一条紧凑的系统消息。这样既保持了 token 成本的稳定，又保留了最重要的内容——就像人类记忆会让细节淡化，却保留整体画面一样。',
        blog_v2_h3_4: '可见的进展与不可见的整理工作',
        blog_v2_p4_1: '在幕后，许多组件得到了精炼：代码库被重新组织（文档和 SQL 脚本分别放在独立的文件夹中），所有 Java 类都获得了详细的注释，网站上过时的文本也得到了更新。',
        blog_v2_p4_2: '人物页面也被重新整理：对单个人物角色名称的旧引用被替换为通用表述，以便平台与未来的人物角色保持一致。',
        blog_v2_h3_5: '15 位参与者，新的人物角色，新的声音',
        blog_v2_p5: '共有 15 人参与了这项研究，并与传记师分享了他们的人生故事。这些故事每一个都成为了独立的人物角色——拥有自己的头像、通过 ElevenLabs 合成的专属声音，以及面向三种对话变体的三段式系统提示。平台因此获得了多样性——不同的语言、年龄层和人生轨迹在这里相遇。',
        blog_v2_p_final: 'Oblivio 仍在不断进化——不是一蹴而就的大跃进，而是通过许多细小的改进，每一处都让对话变得更真实、更人性化一点。',

        // Terms page
        terms_label: '法律',
        terms_h1: '使用条款',
        terms_updated: '更新日期：2026 年 1 月',
        terms_highlight: 'Oblivio 是 ZHAW——苏黎世应用科学大学本科毕业论文中的学术研究项目。使用本平台即表示你同意这些使用条款。',
        terms_s1_title: '1. 服务性质',
        terms_s1_p1: 'Oblivio 是一个非商业性的学术平台，作为 ZHAW 本科毕业论文的一部分开发。该服务免费向公众提供，不以盈利为目的。',
        terms_s1_p2: '平台正在积极开发中。功能、可用性和内容可能随时发生变化。不保证永久运营。',
        terms_s2_title: '2. 允许的使用',
        terms_s2_p1: '你可以使用 Oblivio 来：',
        terms_s2_list1: '<li>记录你的个人数字遗产</li><li>与 AI 传记师进行对话</li><li>检索和管理你存储的内容</li>',
        terms_s2_p2: '不允许的使用包括：',
        terms_s2_list2: '<li>自动化批量请求或 API 滥用</li><li>输入违法、冒犯性或有害内容</li><li>试图访问他人数据或绕过安全措施</li><li>未经书面许可进行任何商业用途</li>',
        terms_s3_title: '3. 你的内容',
        terms_s3_p1: '你输入 Oblivio 的所有内容（对话、回答、个人资料信息）的知识产权归你所有。你授权 Oblivio 为服务的技术运营处理和存储这些内容。',
        terms_s3_p2: '出于学术研究目的，对话模式和使用行为可能会以<strong>完全匿名的形式</strong>进行评估。不会也不可能推断出个人身份。',
        terms_s4_title: '4. 免责声明',
        terms_s4_p1: 'Oblivio "按现状"提供。不对不间断可用性、无错误或数据永久存储作任何保证。作为学术项目的一部分，服务可能随时被中止、变更或限制。',
        terms_s4_p2: '传记师的 AI 生成回复仅供个人反思和记录。它们不构成心理、医疗或法律建议。',
        terms_s5_title: '5. 知识产权',
        terms_s5_p1: 'Oblivio 平台的设计、代码、文本及所有其他内容（用户内容除外）受版权保护，归 Dennis Riccardo 所有。未经书面许可，不得使用或复制任何部分。',
        terms_s6_title: '6. 第三方服务商',
        terms_s6_p1: 'Oblivio 使用外部服务（包括 OpenAI、Supabase、Railway 和瑞士托管商），这些服务的隐私和使用条款由各自的服务商负责。使用 Oblivio 即表示你默认同意在运营所需范围内使用这些服务。',
        terms_s7_title: '7. 变更',
        terms_s7_p1: '这些使用条款可能随时调整。重大变更将在平台上公示。变更后继续使用即视为接受。',
        terms_s8_title: '8. 联系方式',
        terms_s8_p1: '关于使用条款的问题请联系：<a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',

        // Privacy page
        priv_label: '法律',
        priv_h1: '隐私政策',
        priv_updated: '更新日期：2026 年 1 月',
        priv_s1_title: '1. 责任方',
        priv_s1_p1: '本平台数据处理的责任方为：',
        priv_s1_p2: '<strong>Dennis Riccardo</strong><br>学生，ZHAW——苏黎世应用科学大学<br>邮箱：<a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s1_p3: 'Oblivio 是本科毕业论文中的学术研究项目，不是商业公司。',
        priv_s2_title: '2. 我们收集哪些数据',
        priv_s2_p1: 'Oblivio 仅收集服务运营所必需的数据：',
        priv_s2_list: '<li><strong>注册数据：</strong>邮箱地址、全名、密码（以 bcrypt 哈希形式存储）</li><li><strong>个人资料数据：</strong>昵称、年龄段、性别、婚姻状况、性格特征、沟通风格——在对话前的问卷中自愿提供</li><li><strong>对话内容：</strong>你与传记师对话中写的所有消息</li><li><strong>语言偏好：</strong>你选择的语言（DE、EN、IT、KO），保存在浏览器 localStorage 中</li>',
        priv_s2_p2: '<strong>不会</strong>收集位置数据、设备指纹、IP 地址（用于个人身份识别）、广告用途的 Cookie 或行为数据。',
        priv_s3_title: '3. 数据处理目的',
        priv_s3_p1: '所收集的数据仅用于以下目的：',
        priv_s3_list: '<li>平台运营和提供传记师对话</li><li>根据你的个人资料信息个性化 AI 传记师</li><li>存储你的数字遗产以供日后检索</li><li>你的账号的身份验证和安全保障</li><li>本科毕业论文中的学术研究和评估（匿名化）</li>',
        priv_s4_title: '4. 向第三方披露',
        priv_s4_p1: '你的数据<strong>不会</strong>被出售、出租或用于广告目的。以下第三方服务商用于平台运营：',
        priv_s4_list: '<li><strong>Supabase</strong>（数据库和身份验证）——数据按照 Supabase 隐私政策处理</li><li><strong>OpenAI</strong>（GPT API）——对话消息被传输以进行处理；OpenAI 根据合同不会将其用于模型训练</li><li><strong>Railway</strong>（后端基础设施）——API 请求处理，不永久存储数据</li><li><strong>瑞士托管商</strong>（网站托管，瑞士）——静态文件分发</li>',
        priv_s5_title: '5. 数据安全',
        priv_s5_p1: '浏览器与服务器之间的所有传输均采用 TLS 加密。密码以 bcrypt 哈希形式存储。Supabase 行级安全 (RLS) 确保没有用户能访问他人的数据。数据库访问仅通过签名的 JWT 令牌进行。',
        priv_s6_title: '6. 你的权利',
        priv_s6_p1: '你有权：',
        priv_s6_list: '<li><strong>知情权：</strong>查询关于你存储了哪些数据</li><li><strong>更正权：</strong>更正不正确的数据</li><li><strong>删除权：</strong>完全且不可逆地删除你的所有数据</li><li><strong>数据可携权：</strong>以机器可读格式提供你的数据</li><li><strong>异议权：</strong>对某些处理目的提出异议</li>',
        priv_s6_p2: '行使这些权利请联系：<a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s7_title: '7. 保留期限',
        priv_s7_p1: '你的数据将在账号活跃期间保存。在收到删除请求后，所有数据将在 7 个工作日内完全删除。学术项目结束后，所有个人数据将被删除；匿名化的评估结果可能保留在毕业论文中。',
        priv_s8_title: '8. 适用法律',
        priv_s8_p1: '本隐私政策受瑞士数据保护法 (revDSG) 约束。由于 Oblivio 也可能吸引来自欧盟的用户，我们尽可能遵循 GDPR 的原则。',

        // Beta Page
        hero_beta_cta: '成为 Beta 测试员',
        beta_cta_title: '塑造明天的未来。',
        beta_cta_desc: 'Oblivio 正处于测试阶段。现在就锁定你的名额，帮助我们打造一个让故事永存的平台。',
        beta_label: '成为测试员',
        beta_title: '成为故事的<br>一部分。',
        beta_subtitle: 'Oblivio 正处于测试阶段。成为首批留存遗产的人，帮助塑造平台的未来。',
        beta_benefit1_title: '抢先体验',
        beta_benefit1_desc: '在 Oblivio 公开发布前抢先试用，第一个体验 AI 如何留存你的遗产。',
        beta_benefit2_title: '塑造未来',
        beta_benefit2_desc: '你的反馈将塑造平台的未来。每一条回复都帮助我们把 Oblivio 做得更好。',
        beta_benefit3_title: '完全免费',
        beta_benefit3_desc: '免费获得完整访问权限。我们相信遗产留存应该人人可及。',
        beta_form_title: '注册并加入我们。',
        beta_form_desc: '注册后，当你的访问权限准备就绪时，我们会联系你。绝无垃圾邮件，我们承诺。',
        beta_name_label: '姓名',
        beta_email_label: '邮箱',
        beta_name_placeholder: '你的名字',
        beta_email_placeholder: 'your@email.com',
        beta_submit: '立即注册',
        beta_submitting: '正在发送...',
        beta_success: '谢谢你！我们会尽快联系你。',
        beta_error: '发生了一个错误，请重试。',
        beta_duplicate: '该邮箱已注册。',
        beta_privacy_note: '注册即表示你同意我们的<a href="terms.html">使用条款</a>和<a href="privacy.html">隐私政策</a>。',

        // Page titles
        page_title_index: 'Oblivio – 超越记忆',
        page_title_about: '关于 Oblivio – Oblivio',
        page_title_features: '技术 – Oblivio',
        page_title_blog: '博客 – Oblivio',
        page_title_faq: '常见问题 – Oblivio',
        page_title_pricing: '价格 – Oblivio',
        page_title_security: '安全 – Oblivio',
        page_title_contact: '联系我们 – Oblivio',
        page_title_journey: '你的旅程 – Oblivio',
        page_title_biographer: '传记师 – Oblivio',
        page_title_login: '登录 – Oblivio',
        page_title_signup: '注册 – Oblivio',
        page_title_privacy: '隐私政策 – Oblivio',
        page_title_terms: '使用条款 – Oblivio',
        page_title_404: '页面未找到 – Oblivio',
        page_title_legacy: '遗产 – Oblivio',

        // Legacy Chat
        legacy_title: '体验遗产',
        legacy_subtitle: '输入访问代码与遗产对话。',
        legacy_code_placeholder: '访问代码',
        legacy_connect_btn: '连接',
        legacy_invalid_code: '无效的代码。请重试。',
        legacy_no_data: '未找到遗产数据。',
        legacy_error: '发生错误。请重试。',
        legacy_loading: '正在连接...',
        legacy_chat_title: '与',
        legacy_chat_subtitle: '与{name}的遗产对话',
        legacy_input_placeholder: '写一条消息...',
        legacy_ended: '对话已结束。',
        legacy_send_error: '消息无法发送。请重试。',
        // Legacy Visitor Info
        legacy_visitor_title: '开始之前',
        legacy_visitor_subtitle: '让对话更个人化。',
        legacy_visitor_name_label: '{name} 应该怎么称呼你？',
        legacy_visitor_name_placeholder: '你的名字',
        legacy_visitor_relation_label: '你与 {name} 是什么关系？',
        legacy_visitor_relation_placeholder: '请选择...',
        legacy_visitor_rel_spouse: '配偶',
        legacy_visitor_rel_child: '孩子',
        legacy_visitor_rel_parent: '父母',
        legacy_visitor_rel_sibling: '兄弟姐妹',
        legacy_visitor_rel_grandchild: '孙辈',
        legacy_visitor_rel_friend: '朋友',
        legacy_visitor_rel_relative: '亲戚',
        legacy_visitor_rel_other: '其他',
        legacy_visitor_gender_label: '性别',
        legacy_visitor_gender_placeholder: '请选择...',
        legacy_visitor_gender_male: '男',
        legacy_visitor_gender_female: '女',
        legacy_visitor_gender_other: '其他',
        legacy_visitor_start: '开始对话',
        legacy_visitor_required: '请填写所有字段。',
        // Legacy Conversation Mode
        legacy_mode_active: '变体 2',
        legacy_mode_passive: '变体 3',
        legacy_mode_analysis: '变体 1',
        legacy_passive_hint: '给 {name} 发一条消息开始对话…',
        legacy_mode_switch_confirm: '切换模式？当前对话将重新开始。',

        // Biographer Completion — Access Code
        bio_complete_code_desc: '将此代码分享给您的亲人：',
        bio_complete_code_copy: '复制代码',
        bio_complete_code_copied: '已复制！',
        bio_complete_code_email: '通过电子邮件分享',
        bio_complete_email_subject: '您的Oblivio访问代码 -',
        bio_complete_email_greeting: '您好',
        bio_complete_email_line1: '传记已成功完成！',
        bio_complete_email_line2: '访问代码：',
        bio_complete_email_line3: '访问此页面与遗产对话：',

        // Journey — Access Code
        journey_your_code: '您的访问代码',
        journey_code_desc: '将此代码分享给您的亲人，让他们可以与您的遗产对话。',
        journey_email_code: '通过电子邮件分享'
};
