// Oblivio translations — tr
window._oblivioLang = {
// Navigation
        nav_home: 'Ana Sayfa',
        nav_features: 'Özellikler',
        nav_philosophy: 'Felsefe',
        nav_journey: 'Yolculuk',
        nav_login: 'Giriş Yap',
        nav_signup: 'Kayıt Ol',
        nav_logout: 'Çıkış Yap',
        nav_back: '← Geri',
        nav_back_home: '← Ana Sayfaya Dön',

        // Hero Section
        hero_subtitle: 'Nesiller boyu yaşayan dijital bir miras. Özünüzü koruyun, bilgeliğinizi paylaşın, anılardan fazlasını bırakın.',
        hero_cta: 'Şimdi Başla',

        // Features Section
        features_title: 'Özü Koruyun',
        features_subtitle: 'Mirasınız, üç adımda şekillenir.',
        feature1_title: 'Kayıt Ol',
        feature1_desc: 'Hesabınızı anında oluşturun. Verileriniz uçtan uca şifreleme ile saklanır — yalnızca size erişilebilir.',
        feature2_title: 'Hikayenizi Anlatın',
        feature2_desc: 'Biyografınız sizi hayatınızın bölümlerinde yönlendirsin — günlük anlardan değerli anılara, en derin değerlerinize ve taşıdığınız bilgeliğe.',
        feature3_title: 'Oblivio\'nuzu Paylaşın',
        feature3_desc: 'Sevdiklerinize kalıcı bir şey sunun — sesinizi, değerlerinizi ve sevginizi bir ömrün ötesinde koruyan yaşayan bir miras.',

        // Philosophy Section
        philosophy_title: 'Hafızanın Ötesinde',
        philosophy_p1: 'Oblivio sadece gerçeklerin ve verilerin saklandığı bir yer değildir. Kişiliğinizin, değerlerinizin ve sevginizin sonsuza dek var olduğu yaşayan bir mirastır.',
        philosophy_p2: 'Her insanın korunmaya değer benzersiz bir bilgeliğe sahip olduğuna inanıyoruz. Çocuklar, torunlar ve bizden sonra gelenler için.',
        philosophy_p3: 'Zaman geçer, ama öz kalır.',

        // Journey Page
        journey_welcome: 'Oblivio\'ya Hoş Geldiniz',
        journey_subtitle: 'Bugün ne yapmak istersiniz?',
        journey_card1_label: 'Sizin İçin',
        journey_card1_title: 'Hikayenizi Anlatın',
        journey_card1_desc: 'Anılarınızı, deneyimlerinizi ve hayat bilgeliğinizi paylaşın. Biyografımız, kişisel hikayenizi en önemli insanlar için bir miras olarak kaydetmenizde size nazikçe rehberlik edecektir.',
        journey_card1_cta: 'Sohbete Başla',
        journey_card2_label: 'Sevdikleriniz İçin',
        journey_card2_title: 'Bir Mirası Deneyimleyin',
        journey_card2_desc: 'Özel birinin mirasıyla diyaloğa girin. Hikayelerini dinleyin, bilgeliklerini keşfedin ve varlıklarını hissedin, ihtiyaç duyduğunuzda.',
        journey_card2_cta: 'Sohbete Başla',
        journey_coming_soon: 'Çok Yakında',

        // Login Page
        login_title: 'Tekrar Hoş Geldiniz',
        login_subtitle: 'Yolculuğunuza devam etmek için giriş yapın',
        login_email: 'E-posta',
        login_password: 'Şifre',
        login_button: 'Giriş Yap',
        login_signing_in: 'Giriş yapılıyor...',
        login_no_account: 'Hesabınız yok mu?',
        login_create_here: 'Buradan oluşturun',
        login_success: 'Giriş başarılı! Yönlendiriliyorsunuz...',

        // Signup Page
        signup_title: 'Hesap Oluştur',
        signup_subtitle: 'Miras yolculuğunuza bugün başlayın',
        signup_name: 'Ad Soyad',
        signup_name_placeholder: 'Adınız ve soyadınız',
        signup_email: 'E-posta',
        signup_email_placeholder: 'sizin@email.com',
        signup_password: 'Şifre',
        signup_password_placeholder: 'Güçlü bir şifre oluşturun',
        signup_password_req: 'En az 6 karakter uzunluğunda',
        signup_confirm: 'Şifreyi Onayla',
        signup_confirm_placeholder: 'Şifrenizi tekrar girin',
        signup_button: 'Hesap Oluştur',
        signup_creating: 'Hesap oluşturuluyor...',
        signup_have_account: 'Zaten hesabınız var mı?',
        signup_signin_here: 'Buradan giriş yapın',
        signup_success: 'Hesap başarıyla oluşturuldu! Giriş sayfasına yönlendiriliyorsunuz...',
        signup_error_match: 'Şifreler eşleşmiyor',
        signup_error_length: 'Şifre en az 6 karakter uzunluğunda olmalıdır',

        // Biographer Page
        bio_title: 'Biyograf',
        bio_subtitle: 'Hikayenizi birlikte koruyalım',
        bio_input_placeholder: 'Cevabınızı buraya yazın...',
        bio_send: 'Gönder',
        bio_complete_title: 'Biyografi Tamamlandı',
        bio_complete: 'Hikayenizi benimle paylaştığınız için teşekkür ederim. Mirasınız özenle hazırlanıyor — Dennis, her şey deneyimlemeniz için hazır olduğunda sizinle iletişime geçecektir.',

        // Biographer Questions
        bio_q1: 'Merhaba! Ben Biyograf, mirasınızı korumak için buradayım. Adınız nedir?',
        bio_q2: 'Çocukluğunuzdan bahsedin. Nerede büyüdünüz ve en güzel anılarınız neler?',
        bio_q3: 'Hayatınızdaki en önemli değerler neler? Hangi ilkeler kararlarınıza yön veriyor?',
        bio_q4: 'Hayatınızda en büyük etkiyi kim bıraktı? Bugün kim olduğunuzu nasıl şekillendirdiler?',
        bio_q5: 'Hayatınızda en çok gurur duyduğunuz başarılar neler?',
        bio_q6: 'Gelecek nesillere aktarmak istediğiniz dersler neler?',
        bio_q7: 'Sevdiklerinize bir tavsiye verebilseydiniz, ne olurdu?',
        bio_q8: 'Hayatta size en çok neşe veren şey ne?',
        bio_q9: 'Hayat hikayeniz hakkında paylaşmak istediğiniz başka bir şey var mı?',

        // Language Selection Modal
        lang_modal_title: 'Dilinizi Seçin',
        lang_modal_subtitle: 'Biyograf ile sohbetiniz için dili seçin',
        lang_modal_continue: 'Devam Et',

        // Footer
        footer_tagline: 'Unutulmayanı koru.<br>Sonsuzluk için bir miras.',
        footer_product: 'Ürün',
        footer_features: 'Özellikler',
        footer_pricing: 'Fiyatlandırma',
        footer_security: 'Güvenlik',
        footer_faq: 'SSS',
        footer_company: 'Şirket',
        footer_about: 'Oblivio Hakkında',
        footer_blog: 'Blog',
        footer_careers: 'Kariyer',
        footer_press: 'Basın',
        footer_legal: 'Hukuki',
        footer_privacy: 'Gizlilik',
        footer_terms: 'Kullanım Şartları',
        footer_imprint: 'Künye',
        footer_contact: 'İletişim',
        footer_rights: '© 2026 Oblivio. Tüm hakları saklıdır.',
        footer_tech: 'Teknoloji',

        // Nav sub-page links
        nav_tech_link: 'Teknoloji',
        nav_about_link: 'Oblivio Hakkında',
        nav_start_link: 'Başla',

        // Security page
        sec_label: 'Güvenlik',
        sec_h1: 'Hikayeniz<br>yalnızca size ait.',
        sec_sub: 'Oblivio ile paylaştığınız, sahip olduğunuz en kişisel şeydir. Biz de buna göre davranırız.',
        sec_c1_title: 'Şifreleme',
        sec_c1_desc: 'Tüm bağlantılar TLS ile şifrelenir. Veriler Supabase\'de durağan şifreleme ile saklanır. Hiç kimse düz metin olarak okuyamaz.',
        sec_c2_title: 'Satır Düzeyinde Güvenlik',
        sec_c2_desc: 'Supabase RLS, her veritabanı sorgusunun yalnızca kendi verilerinizi döndürmesini sağlar ve başka birinin kayıtlarına erişmeyi teknik olarak imkansız kılar.',
        sec_c3_title: 'JWT Kimlik Doğrulama',
        sec_c3_desc: 'Hesabınıza erişim imzalı JSON Web Token\'ları ile güvence altına alınır. Süresi dolmuş veya geçersiz token\'lar otomatik olarak reddedilir.',
        sec_c4_title: 'İsviçre Altyapısı',
        sec_c4_desc: 'Ön yüz, sertifikalı bir İsviçre barındırma sağlayıcısı aracılığıyla işletilir. İsviçre veri koruma yasası (revDSG) tüm veri işleme için asgari standart olarak geçerlidir.',
        sec_c5_title: 'İzleme Yok, Reklam Yok',
        sec_c5_desc: 'Oblivio reklam izleyicisi, üçüncü taraf analiz hizmeti kullanmaz ve kullanıcı verilerini satmaz. Hiç kimseye.',
        sec_c6_title: 'Silme Hakkı',
        sec_c6_desc: 'Verilerinizin silinmesini istediğiniz zaman talep edebilirsiniz. Hesabınız, sohbetleriniz ve mirasınız tamamen ve geri dönüşümsüz olarak kaldırılacaktır.',
        sec_auth_title: 'Kimlik Doğrulama ve Erişim',
        sec_auth_p1: 'Oblivio\'ya erişim yalnızca doğrulanmış bir e-posta adresi ve kendi seçtiğiniz bir şifre ile mümkündür. Şifreler asla düz metin olarak saklanmaz. Supabase Auth, şifre saklama için en güvenli standartlardan biri olan <strong>bcrypt</strong> tabanlı hash kullanır.',
        sec_auth_p2: 'Oturumlar kısa ömürlü JWT token\'ları ile yönetilir. Belirli bir süre sonra bunlar otomatik olarak yenilenir veya geçersiz kılınır, böylece süresi dolmuş oturumlar erişim sağlamaz.',
        sec_auth_box: '<strong>Satır Düzeyinde Güvenlik (RLS)</strong> tüm tablolarda etkindir. Bu şu anlama gelir: uygulama mantığında teknik bir hata oluşsa bile, sunucu düzeyindeki veritabanı hiçbir kullanıcının başka bir kullanıcının verilerine erişemeyeceğini garanti eder.',
        sec_dm_title: 'Veri Minimizasyonu',
        sec_dm_p1: 'Oblivio yalnızca hizmet için gerekli olanı toplar: ad, e-posta adresi, dil tercihi ve Biyograf ile yaptığınız sohbetlerin içeriği. Teknik gereklilik dışında konum verisi, cihaz parmak izi, davranış kalıpları veya diğer meta veriler toplanmaz.',
        sec_dm_p2: 'Sohbet içeriği yalnızca mirasınızı oluşturmak için kullanılır ve başka herhangi bir analize, üçüncü taraf AI model eğitimine veya paylaşıma tabi değildir.',
        sec_ai_title: 'AI İstekleri',
        sec_ai_p: 'Sohbet içeriği işlenmek üzere OpenAI GPT API\'sine iletilir. OpenAI, ticari müşterilerden gelen API isteklerini modellerini eğitmek için kullanmamayı sözleşmeyle taahhüt etmiştir. İletim yalnızca şifreli (TLS 1.3) ve yalnızca işleme süresi boyunca gerçekleşir, OpenAI\'da kalıcı depolama yapılmaz.',

        // Pricing page
        price_label: 'Fiyatlandırma',
        price_h1: 'Hayaller fatura<br>göndermemeli.',
        price_sub: 'Oblivio her kullanıcı için ücretsizdir ve öyle kalacaktır. İşte arkasındaki dürüst hikaye.',
        price_s1_title: 'API\'lerin gerçeği',
        price_s1_p1: 'Biyograf ile her sohbetin arkasında gerçek maliyetler yatar. Yazdığınız her mesaj OpenAI\'ın veri merkezlerine gider ve düşünceli, empatik bir yanıt olarak döner. Saklanan her anı Supabase sunucularında yer kaplar. PROMISE AI\'ya yapılan her çağrı Railway\'de hesaplama kapasitesi tüketir.',
        price_s1_p2: 'Bunlar varsayımsal maliyetler değil. Her sohbette oluşan gerçek API ücretleridir:',
        price_cost1_title: 'OpenAI (GPT API)',
        price_cost1_desc: 'Token maliyetleri, sohbetin derinliğine ve sistem bağlamının uzunluğuna bağlı olarak her sohbet bloğu başına oluşur.',
        price_cost2_title: 'Supabase',
        price_cost2_desc: 'Veritabanı sorguları, kimlik doğrulama ve sohbet geçmişlerinin ve mirasların saklanması.',
        price_cost3_title: 'Railway',
        price_cost3_desc: 'PROMISE arka uç hizmetinin sürekli işletimi, eşzamanlı kullanıcılarda yoğun hesaplama gerektirir.',
        price_cost4_title: 'Web Barındırma (CH)',
        price_cost4_desc: 'Oblivio.ch alan adı üzerinden ön yüzün barındırılması ve sunulması.',
        price_s2_title: 'Neden yine de ücretsiz?',
        price_s2_p1: 'Oblivio bir tutku projesidir, bir iş planından değil, basit bir inançtan doğmuştur: <em>her insan duyulmayı ve hatırlanmayı hak eder.</em> Yalnızca pahalı yazılım karşılayabilenler değil.',
        price_s2_p2: 'Kendi hayatını belgeleme, sesini gelecek nesiller için koruma, bilgeliğini aktarma fikri: bu bir lüks değil. Derinden insani bir ihtiyaç. Oblivio bu ihtiyacın karşılandığı yer olmak istiyor, banka bakiyesinden bağımsız olarak.',
        price_s2_p3: 'ZHAW\'daki akademik araştırma projesi olarak mevcut aşamada, geliştiriciler işletme maliyetlerini üstleniyor. Önemli olan deneyimdir ve eksiksiz, kısıtlamasız ve onurlu olmalıdır.',
        price_plan_label: 'Mevcut Plan',
        price_plan_name: 'Oblivio Ücretsiz',
        price_plan_price: 'CHF 0',
        price_plan_per: '/ ay',
        price_plan_desc: 'Biyografa tam erişim, 10 sohbet bloğunun tamamı, otomatik miras depolama ve dijital miras, kısıtlama olmadan.',
        price_inc1: '10 sohbet bloğu',
        price_inc2: 'Otomatik bilgi depolama',
        price_inc3: 'Dijital miras',
        price_inc4: 'Tüm 8 dil',
        price_inc5: 'Güvenli şifreleme',
        price_inc6: 'Reklam yok',
        price_footnote: 'Oblivio aktif geliştirme aşamasındadır. ElevenLabs ile ses klonlama veya yakınlarla sohbete devam etme gibi gelecek özellikler de bu vaadin ruhunda sunulacaktır: onurla, özenle ve mümkün olduğunca erişilebilir.',

        // FAQ page
        faq_label: 'SSS',
        faq_h1: 'Sık sorulan<br>sorular',
        faq_sub: 'Oblivio hakkında bilmek istediğiniz her şey, açık ve dürüstçe yanıtlandı.',
        faq_cat1: 'Genel',
        faq_q1: 'Oblivio nedir?',
        faq_a1: 'Oblivio, bir AI Biyograf eşliğinde hayat eserinizi belgelemenize olanak tanıyan dijital bir platformdur. Ortaya çıkan sohbetler, içgörüler ve anılar, sevdiklerinizin gelecekte deneyimleyebileceği dijital bir miras olarak saklanır.',
        faq_q2: 'Oblivio kimin için?',
        faq_a2: 'Anlatacak hikayesi olan herkes için, yani herkes. Oblivio özellikle bilgeliklerini, anılarını ve kişiliklerini çocuklara, torunlara ve gelecek nesillere korumak isteyen insanlara yöneliktir.',
        faq_q3: 'Biyograf nasıl çalışır?',
        faq_a3: 'Biyograf sizi on tematik sohbet bloğunda yönlendirir, günlük hayattan anılara, ilişkilere ve değerlere, mirasınıza kadar. Her blok derin bir sohbettir, yeterli anlamlı bilgi toplandığında otomatik olarak özetlenir ve saklanır.',
        faq_q4: 'Oblivio hangi dilleri destekliyor?',
        faq_a4: 'Oblivio şu anda sekiz dili desteklemektedir: Almanca, İngilizce, Fransızca, İtalyanca, Türkçe, Korece, Japonca ve Çince. Biyografi yazarının dilini ilk konuşmanın başında seçersiniz. Biyografi yazarı daha sonra bu dilde tutarlı bir şekilde iletişim kurar.',
        faq_cat2: 'Sohbet ve Biyograf',
        faq_q5: 'Kaç sohbet bloğu var?',
        faq_a5: 'On blok vardır: Günlük Hayat, Duygular, Anılar, İlişkiler, Kişisel Gelişim, Hayaller, Değerler, Miras, Kişisel Mesajlar ve Kapanış. Her blok kendi yaşam alanına adanmıştır ve yalnızca Biyograf yeterli derin yanıtlar topladığında tamamlanır.',
        faq_q6: 'Sohbeti duraklatıp devam edebilir miyim?',
        faq_a6: 'Evet. Sohbet geçmişiniz otomatik olarak Supabase\'de kaydedilir. Tekrar giriş yaptığınızda, mevcut sohbet bloğu dahil kaldığınız yerden devam edersiniz.',
        faq_q7: '10 bloğun sonunda ne olur?',
        faq_a7: 'On bloğun tamamlanmasının ardından eksiksiz dijital mirasınız otomatik olarak kaydedilir. Tüm sohbetlerden özetlenmiş içgörüleri içerir. Gelecek bir sürümde, yakınlar bu mirasla diyaloğa girebilecekler.',
        faq_q8: 'Biyograf gerçekten dinliyor mu, yoksa standart metin mi?',
        faq_a8: 'Biyograf, OpenAI\'ın GPT dil modeli tarafından desteklenmektedir. Yazdığınız her cümleyi okur, tüm sohbetin bağlamını hatırlar ve söylediklerinize gerçekten yanıt veren takip soruları sorar. Bu bir form değil. Gerçek bir sohbet.',
        faq_cat3: 'Gizlilik ve Güvenlik',
        faq_q9: 'Sohbetlerimi kim okuyabilir?',
        faq_a9: 'Sizden başka kimse. Supabase Satır Düzeyinde Güvenlik, her veritabanı sorgusunun teknik olarak kendi verilerinizle sınırlı olmasını sağlar. Hiçbir yönetici, geliştirici veya başka kullanıcı sohbet içeriklerinizi görüntüleyemez.',
        faq_q10: 'Verilerim AI eğitimi için kullanılıyor mu?',
        faq_a10: 'Hayır. OpenAI, ticari müşterilerden gelen API isteklerini model eğitimi için kullanmamayı sözleşmeyle taahhüt etmiştir. Sohbet içerikleriniz yalnızca yanıt oluşturmak için işlenir ve sonrasında saklanmaz.',
        faq_q11: 'Verilerimin silinmesini isteyebilir miyim?',
        faq_a11: 'Evet, istediğiniz zaman. "Veri Silme" konusuyla <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a> adresine e-posta gönderin, tüm verileriniz tamamen ve geri dönüşümsüz olarak kaldırılacaktır.',
        faq_cat4: 'Maliyetler',
        faq_q12: 'Oblivio gerçekten ücretsiz mi?',
        faq_a12: 'Evet. Oblivio, ZHAW\'daki akademik bir araştırma projesidir ve tüm kullanıcılara gizli ücretler, freemium kısıtlamaları ve reklam olmadan tamamen ücretsiz sunulmaktadır. Daha fazla bilgi <a href="pricing.html">fiyatlandırma sayfasında</a>.',
        faq_q13: 'Oblivio kalıcı olarak ücretsiz kalacak mı?',
        faq_a13: 'Bu niyettir. Oblivio bir lisans tezi olarak oluşturulduğundan, işletme maliyetleri yönetilebilir düzeydedir. Proje büyürse, iş modelindeki herhangi bir değişiklik şeffaf bir şekilde bildirilecektir.',

        // Features / Technology page
        tech_label: 'Teknoloji',
        tech_h1: 'Kalıcılığın<br>Mimarisi',
        tech_sub: 'Oblivio, her hikayenin güvenle korunması, her sohbetin canlanması ve her mirasın kalıcı olarak erişilebilir kalması için ileri düzey araştırmayı özenli altyapıyla birleştirir.',
        tech_intro: 'Oblivio\'nun arkasında hazır çözümler değil, onur, güvenlik ve derinlik arasında denge kuran bir sistem oluşturan bilinçli olarak seçilmiş teknolojiler vardır.',
        tech_01_sub: 'Konuşma AI Çerçevesi',
        tech_01_title: 'PROMISE',
        tech_01_p: 'PROMISE, <strong>ZHAW – Zürih Uygulamalı Bilimler Üniversitesi</strong>\'nden durum tabanlı, çok adımlı AI sohbetlerini mümkün kılan bilimsel bir çerçevedir. Oblivio\'nun Biyografı tamamen PROMISE üzerine inşa edilmiştir: on tematik sohbet bloğunun her biri, kendi sistem bağlamı, geçiş koşulları ve otomatik bilgi çıkarımına sahip bağımsız bir durumdur. Arka uç hizmeti <strong>Railway</strong> aracılığıyla sağlanır ve her zaman ölçeklenebilir şekilde erişilebilirdir.',
        tech_01_tag1: 'ZHAW Araştırma',
        tech_01_tag2: 'Durumlu AI',
        tech_02_sub: 'Dil Modeli',
        tech_02_title: 'OpenAI\'dan GPT',
        tech_02_p: 'Biyografın sohbetleri <strong>OpenAI\'ın GPT dil modeli</strong> tarafından desteklenir. OpenAI\'ın modelleri geniş miktarda insan dili üzerinde eğitilmiştir ve bağlama duyarlı, empatik sohbetler yürütebilir. Bu, Oblivio\'nun mekanik hissettirmeyen, aksine dikkatli bir muhatap gibi davranan sohbetler yapmasını sağlar: sabırlı, algılı ve her zaman kişiyle ilgilenen.',
        tech_02_tag1: 'OpenAI',
        tech_02_tag2: 'GPT',
        tech_03_sub: 'Veritabanı ve Kimlik Doğrulama',
        tech_03_title: 'Supabase',
        tech_03_p: 'Tüm kullanıcı verileri, sohbet geçmişleri ve saklanan miraslar, Satır Düzeyinde Güvenlik (RLS) özellikli açık bir PostgreSQL platformu olan <strong>Supabase</strong>\'de saklanır. Bu şu anlama gelir: hiçbir kullanıcı başka birinin verilerine erişemez, ne hatalarla, ne güvenlik açıklarıyla. Kimlik doğrulama şifreli JWT token\'ları ile yapılır ve tüm bağlantılar TLS ile güvence altına alınır.',
        tech_03_tag1: 'PostgreSQL',
        tech_03_tag2: 'Satır Düzeyinde Güvenlik',
        tech_04_sub: 'Arka Uç Altyapısı',
        tech_04_title: 'Railway',
        tech_04_p: 'PROMISE arka uç hizmeti, otomatik dağıtım, ölçeklendirme ve izlemeyi birleştiren modern bir bulut platformu olan <strong>Railway</strong> üzerinde çalışır. Biyograf sistemindeki her değişiklik, manuel sunucu yapılandırması olmadan dakikalar içinde yayına girer. Railway, Oblivio\'nun yük altında bile güvenilir şekilde erişilebilir kalmasını sağlar.',
        tech_04_tag1: 'Otomatik Dağıtım',
        tech_04_tag2: 'Bulut Altyapısı',
        tech_05_sub: 'Ses Sentezi · Planlandı',
        tech_05_title: 'ElevenLabs',
        tech_05_p: 'Oblivio\'nun gelecek bir sürümünde, her dijital miras yalnızca okunabilir değil, aynı zamanda <em>duyulabilir</em> olacaktır. Gerçekçi ses sentezi için lider platform olan <strong>ElevenLabs</strong> ile kendi sesinizi kaydedip klonlamak mümkün olacaktır. Yakınlar artık sadece metin mesajlarını okumakla kalmayacak, sevdiklerinin tanıdık sesini tekrar duyabilecekler.',
        tech_05_tag1: 'Ses Klonlama',
        tech_05_tag2: 'Yol Haritası 2026',
        tech_06_sub: 'Web Barındırma',
        tech_06_title: 'İsviçre Web Barındırma',
        tech_06_p: 'Oblivio\'nun ön yüzü tanınmış bir İsviçre barındırma sağlayıcısı aracılığıyla işletilir. <em>oblivio.ch</em> alan adı ve tüm statik kaynaklar doğrudan İsviçre\'den sunulur. Bu şu anlama gelir: veriler İsviçre\'de kalır, İsviçre veri koruma yasasına (DSG) tabidir ve mükemmel ağ altyapısından yararlanır.',
        tech_06_tag1: 'İsviçre Barındırma',
        tech_06_tag2: 'DSG uyumlu',
        tech_arch_title: 'Her şey nasıl bir araya geliyor',
        tech_arch_lead: 'Girdinizden saklanan anıya: her adım düşünülmüş ve güvence altına alınmıştır.',
        tech_flow1_title: 'Girdi',
        tech_flow1_p: 'Tarayıcıda bir mesaj yazarsınız, HTTPS üzerinden şifreli olarak iletilir.',
        tech_flow2_title: 'PROMISE işler',
        tech_flow2_p: 'Railway arka uç hizmeti mesajı alır, mevcut durumu belirler ve OpenAI GPT\'ye gönderir.',
        tech_flow3_title: 'GPT yanıt verir',
        tech_flow3_p: 'Dil modeli, Biyografın mevcut durumuna göre empatik, bağlama duyarlı bir yanıt üretir.',
        tech_flow4_title: 'Supabase saklar',
        tech_flow4_p: 'Sohbet ve çıkarılan içgörüler, yalnızca size erişilebilir olan kişisel Supabase örneğinizde güvenle saklanır.',

        // Contact page
        contact_label: 'İletişim',
        contact_h1: 'İletişimde<br>kalalım.',
        contact_li_title: 'Dennis Riccardo',
        contact_li_sub: 'Oblivio\'nun Yaratıcısı · ZHAW Öğrencisi',
        contact_li_cta: 'Profili ziyaret et',
        contact_em_title: 'E-posta',
        contact_em_addr: 'riccaden@students.zhaw.ch',
        contact_info: '<strong>Akademik bağlam:</strong> Oblivio, <strong>ZHAW</strong> – Zürih Uygulamalı Bilimler Üniversitesi\'nde bir lisans tezidir. Sorular, geri bildirimler veya işbirliği önerileri memnuniyetle karşılanır.',

        // About page
        about_label: 'Oblivio Hakkında',
        about_h1: 'Bir kişi.<br>Bir fikir.<br>Bir miras.',
        about_sub: 'Oblivio, her insanın duyulmayı ve hatırlanmayı hak ettiği inancından doğdu — kendi ömrünün çok ötesinde.',
        about_badge: 'Lisans Tezi',
        about_inst: '<strong>ZHAW – Zürih Uygulamalı Bilimler Üniversitesi</strong> · Yönetim ve Hukuk Fakültesi · İşletme Bilişim · 2026',
        about_role: 'Geliştirici · Öğrenci',
        about_bio1: 'ZHAW Winterthur\'da İşletme Bilişim okuyorum, bu program baştan beri beni büyüledi çünkü sevdiğim iki dünyayı birleştiriyor: teknolojinin mantıksal hassasiyeti ve iş dünyasının stratejik düşüncesi.',
        about_bio2: 'Bunun yanı sıra, İsviçre\'nin en büyük sağlık sigortacılarından birinde Proje Yöneticisi olarak çalışıyorum. Orada her gün karmaşık sistemlerin nasıl organize edildiğini, insanların nasıl yönetildiğini ve değişimin nasıl sürdürülebilir şekilde uygulandığını öğreniyorum.',
        about_bio3: 'Oblivio benim lisans tezim. Ama bundan daha fazlası: temsil ettiğim her şeyin bir araya geldiği proje. AI ve modern altyapı ile teknik uygulama. İnsan tarafı: sohbetler, anılar, zaman ötesinde bağlantı ihtiyacı. Ve teknolojinin insanlara hizmet etmesi gerektiği inancı, tam tersi değil.',
        about_bio4: 'Oblivio ile amacım yalnızca çalışan değil, aynı zamanda doğru hissettiren bir şey inşa etmekti. Var olan en mahrem şeyi onurla ele alan bir platform: bir insanın kendi hayatı.',
        about_values_title: 'Oblivio\'yu ne yönlendiriyor',
        about_v1_title: 'Onur',
        about_v1_p: 'Her hikaye saygıyla muamele edilmeyi hak eder, bir veri noktası olarak değil, bir insanın hayat eseri olarak.',
        about_v2_title: 'Erişilebilirlik',
        about_v2_p: 'Kendi hayatını korumak bir para meselesi olmamalı. Oblivio ücretsiz ve bilinçli olarak öyle.',
        about_v3_title: 'Derinlik',
        about_v3_p: 'Yüzeysel cevaplar yüzeysel anılara yol açar. Biyograf, en önemli olan şey yüzeye çıkana kadar sormaya devam eder.',

        // Blog page
        blog_label: 'Blog',
        blog_h1: 'Oblivio nasıl<br>doğdu.',
        blog_sub: 'Fikirden platforma giden yolda kararların, sapmaların ve içgörülerin dürüst bir anlatımı.',
        blog_date: 'İlkbahar 2026',
        blog_tag1: 'Lisans Tezi',
        blog_tag2: 'Geliştirme',
        blog_art_h2: 'Fikirden yaşayan platforma: Oblivio\'nun geliştirme hikayesi',
        blog_art_lead: 'Kendinize sorduğunuzda ne başlar: bir insandan geriye ne kalır, gittiğinde? Oblivio bu soruyla başladı ve başlangıçta beklediğimden daha fazla teknik karar içeren bir cevapla sonuçlandı.',
        blog_h3_1: 'Başlangıç sorusu',
        blog_p1_1: 'Oblivio fikri bir masada değil, kişisel bir sessizlik anında doğdu: kaybettiğim birine hâlâ ne sormak isterdim? Ve tersine: artık burada olmadığımda kendim ne bırakmak isterdim?',
        blog_p1_2: 'Bu sorular beni lisans tezime götürdü. Hedef iddialıydı: her insanın hayatını dijital bir miras biçiminde belgelemesine olanak tanıyan AI destekli bir platform — derin, kişisel ve kalıcı.',
        blog_quote: '"Bir form değil. Bir anket değil. Gerçekten dinleyen bir sohbet."',
        blog_h3_2: 'PROMISE: Çekirdek',
        blog_p2_1: 'Oblivio\'nun teknolojik omurgası <strong>PROMISE</strong>\'dir, ZHAW\'da geliştirilen durum tabanlı bir sohbet çerçevesi. Basit chatbot dizileri yerine, PROMISE gerçek sohbet durumlarını mümkün kılar: on biyograf bloğunun her biri, kendi sistem bağlamı, geçiş koşulları ve otomatik bilgi çıkarımına sahip kendi durumudur.',
        blog_p2_2: 'Temel zorluk: bir blok ne zaman bir sonrakine geçmeli? İlk çözüm çift koşuldu: kullanıcı açıkça "devam" demeli VE guard yeterli konunun ele alındığını onaylamalıydı. Kulağa makul geliyor, ancak ciddi bir hataya yol açtı.',
        blog_technote: '<strong>Hata:</strong> <code>Transition(List.of(trigger, guard), ...)</code> — VE mantığı. Uzun bir sohbetten sonra kullanıcı "hayır" dediğinde (Trigger = true) (Guard = true), <code>TransferUtterancesAction</code> tetiklendi — ve tüm sohbet geçmişi sonraki tüm durumlara aktarıldığı için, TÜM guard\'lar aynı anda true olarak değerlendi. Blok 1 doğrudan "Biyografi Tamamlandı"ya atladı.<br><br><strong>Çözüm:</strong> <code>Transition(List.of(guard), ...)</code> — Yalnızca Guard. Trigger yok. Geçiş, yeterli anlamlı cevap toplandığında otomatik olarak gerçekleşir.',
        blog_h3_3: 'Bir yerine on blok',
        blog_p3_1: 'Biyografın orijinal versiyonu tek bir durumdu, yapı olmadan sonsuz bir sohbet akışı. Sorun: tematik rehberlik olmadan, hayatın birçok alanına dokunulmadı. Kullanıcılar çocukluk anılarından bahsetti, ama asla değerlerinden değil. İşlerinden, ama asla hayallerinden değil.',
        blog_p3_2: 'Çözüm, on tematik bloğa geçiş oldu. Her blok, belirli bir yaşam alanını tam olarak keşfetmek için tasarlanmıştır ve yalnızca o zaman otomatik olarak bir sonrakine geçer.',
        blog_h3_4: 'Ön yüz: işlev ve onur arasında',
        blog_p4_1: 'Oblivio\'nun tasarımı net bir önermeyi takip etti: bir uygulama gibi değil, bir mektup gibi hissettirmeli. Renk paleti (krem, kömür, pas kırmızısı, yosun yeşili) sıcaklık ve kalıcılık iletmek için bilinçli olarak seçildi.',
        blog_p4_2: 'Blok 1\'den sonra görünen ve kullanıcıya Blok 1\'den 10\'a kadar eşlik eden ilerleme çubuğu küçük ama önemli bir UX kararıydı: görünür ilerleme, sohbeti kesintiye uğratmadan yönlendirme sağlar.',
        blog_h3_5: 'Blok 0 anketi',
        blog_p5_1: 'Gerçek biyograf başlamadan önce, kullanıcı kısa bir anketten geçer: ad, yaş grubu, cinsiyet, medeni durum, kişilik özellikleri ve iletişim tarzı. Bu bilgi biyografa bağlam olarak aktarılır.',
        blog_p5_2: 'Bu "Blok 0" yedi dilde mevcuttur ve hızlı, göze batmayan ve dürüst hissettirmek üzere tasarlanmıştır.',
        blog_h3_6: 'Supabase, Railway ve İsviçre Barındırma',
        blog_p6_1: 'Oblivio\'nun altyapısı basit bir ilkeye göre seçildi: her bileşen kendi kategorisinde en iyi olmalı, birlikte iyi çalışmalı ve gereksiz karmaşıklık eklememeli.',
        blog_p6_2: 'Railway özellikle değerli kanıtlamıştır: Java arka ucundaki her değişiklik dakikalar içinde yayına girer. Bu, iterasyon hızını önemli ölçüde artırmıştır.',
        blog_h3_7: 'Şimdiye kadar elde edilenler',
        blog_p7_1: 'Oblivio orijinal vizyonun ötesine geçmiştir: miras sohbeti aktiftir — sevdikleriniz saklanan mirasla diyaloğa girmek için bir erişim kodu kullanabilir. ElevenLabs ses sentezi Biyografa duyulabilir bir ses verir.',
        blog_p7_2: 'Oblivio tamamlandı, ama bitmedi. Üzerinde yapılan her sohbetle zenginleşen bir platformdur.',
        blog_date_v2: '9 Mayıs 2026',
        blog_tag_v2_1: 'Güncelleme',
        blog_tag_v2_2: 'Yineleme',
        blog_v2_h2: 'Dört dilden sekiz dile: büyük yenileme',
        blog_v2_lead: 'Son haftalarda Oblivio büyüdü. Sadece persona sayısında değil, aynı zamanda işlevlerinin derinliğinde de. İşte en önemli değişikliklere genel bir bakış.',
        blog_v2_h3_1: 'Dört yerine sekiz dil',
        blog_v2_p1: 'Oblivio artık sekiz dili destekliyor: Almanca, İngilizce, Fransızca, İtalyanca, Türkçe, Korece, Japonca ve Çince. Uluslararası erişimi daha da genişletmek için sekizinci dil olarak Türkçe eklendi. Bunun için tüm arayüz metinleri, Biyograf anketi ve blok talimatları tamamlandı.',
        blog_v2_h3_2: 'Üç sohbet varyantı',
        blog_v2_p2_1: 'Miras personalarına artık üç farklı modda yaklaşılabilir: Varyant 1, radar grafiği, iletişim DNA\'sı ve yaşam örüntülerini içeren tam bir kişilik analizi sunar. Varyant 2, personanın sohbeti aktif olarak başlatmasına izin verir. Varyant 3, ziyaretçinin ilk mesajını sessizce bekler.',
        blog_v2_p2_2: 'Her varyant farklı bir duygusal duruma uygundur: derin anlayış, düşük başlangıç engeli veya sohbetin nasıl başlayacağı üzerinde tam kontrol.',
        blog_v2_h3_3: 'Otomatik bağlam sıkıştırma',
        blog_v2_p3: 'PROMISE arka ucundaki teknik bir iyileştirme: yirmi kullanıcı mesajından sonra eski sohbet katkıları otomatik olarak özetlenir ve kompakt bir sistem mesajıyla değiştirilir. Böylece token maliyetleri sabit kalırken en önemli içerikler korunur — tıpkı insan hafızasının ayrıntıları soldurup genel resmi koruması gibi.',
        blog_v2_h3_4: 'Görünür ilerleme ve görünmeyen temizlik',
        blog_v2_p4_1: 'Perde arkasında birçok bileşen iyileştirildi: depo yeniden yapılandırıldı (dokümantasyon ve SQL betikleri için ayrı klasörler), tüm Java sınıflarına ayrıntılı yorumlar eklendi ve web sitesindeki güncel olmayan metinler güncellendi.',
        blog_v2_p4_2: 'Kişiler sayfası da yeniden düzenlendi: belirli persona adlarına yapılan eski atıflar genel ifadelerle değiştirildi, böylece platform gelecekteki personalarla da tutarlı kalır.',
        blog_v2_h3_5: '15 katılımcı, yeni personalar, yeni sesler',
        blog_v2_p5: 'Toplamda 15 kişi çalışmaya katıldı ve hayat hikayelerini Biyograf ile paylaştı. Bu hikayelerin her biri kendi personasına dönüştü — kendi profil resmiyle, ElevenLabs aracılığıyla kendi sesiyle ve üç sohbet varyantı için üç bölümlü bir sistem komutuyla. Platform bu sayede çeşitlilik kazandı — farklı diller, yaş grupları ve yaşam yolları burada bir araya geliyor.',
        blog_v2_p_final: 'Oblivio gelişmeye devam ediyor — büyük bir hamleyle değil, her biri sohbeti biraz daha gerçek ve biraz daha insani kılan birçok küçük iyileştirmeyle.',

        // Terms page
        terms_label: 'Hukuki',
        terms_h1: 'Kullanım Şartları',
        terms_updated: 'Tarih: Ocak 2026',
        terms_highlight: 'Oblivio, ZHAW – Zürih Uygulamalı Bilimler Üniversitesi\'ndeki bir lisans tezi kapsamında akademik bir araştırma projesidir. Bu platformu kullanarak bu kullanım şartlarını kabul etmiş olursunuz.',
        terms_s1_title: '1. Hizmetin niteliği',
        terms_s1_p1: 'Oblivio, ZHAW\'daki bir lisans tezinin parçası olarak geliştirilen ticari olmayan, akademik bir platformdur. Hizmet, halka ücretsiz ve kâr amacı gütmeden sunulmaktadır.',
        terms_s1_p2: 'Platform aktif geliştirme aşamasındadır. Özellikler, kullanılabilirlik ve içerik her zaman değişebilir. Kalıcı işletim garantisi yoktur.',
        terms_s2_title: '2. İzin verilen kullanım',
        terms_s2_p1: 'Oblivio\'yu şunlar için kullanabilirsiniz:',
        terms_s2_list1: '<li>Kişisel dijital mirasınızı belgeleme</li><li>AI biyograf ile sohbet yapma</li><li>Saklanan içeriğinizi alma ve yönetme</li>',
        terms_s2_p2: 'Şunlar için kullanım yasaktır:',
        terms_s2_list2: '<li>Otomatik toplu istekler veya API kötüye kullanımı</li><li>Yasadışı, saldırgan veya zararlı içerik girme</li><li>Başkalarının verilerine erişme veya güvenlik önlemlerini aşma girişimleri</li><li>Yazılı izin olmadan her türlü ticari amaç</li>',
        terms_s3_title: '3. İçeriğiniz',
        terms_s3_p1: 'Oblivio\'ya girdiğiniz tüm içerikler (sohbetler, yanıtlar, profil bilgileri) fikri mülkiyetiniz olarak kalır. Oblivio\'ya bu içeriği hizmetin teknik işletimi için işleme ve saklama hakkı verirsiniz.',
        terms_s3_p2: 'Akademik araştırma için sohbet kalıpları ve kullanım davranışı <strong>tamamen anonim biçimde</strong> değerlendirilebilir. Bireysel kişilere ilişkin çıkarımlar ne amaçlanmaktadır ne de mümkündür.',
        terms_s4_title: '4. Sorumluluk reddi',
        terms_s4_p1: 'Oblivio "olduğu gibi" sunulur. Kesintisiz kullanılabilirlik, hatasızlık veya kalıcı veri saklama garantisi verilmez. Akademik bir projenin parçası olarak, hizmet herhangi bir zamanda durdurulabilir, değiştirilebilir veya kısıtlanabilir.',
        terms_s4_p2: 'Biyografın AI tarafından oluşturulan yanıtları yalnızca kişisel yansıma ve belgeleme amaçlıdır. Psikolojik, tıbbi veya hukuki tavsiye niteliği taşımaz.',
        terms_s5_title: '5. Fikri mülkiyet',
        terms_s5_p1: 'Oblivio platformunun tasarımı, kodu, metinleri ve tüm diğer içerikleri (kullanıcı içeriği hariç) telif hakkıyla korunur ve Dennis Riccardo\'nun mülkiyetindedir.',
        terms_s6_title: '6. Üçüncü taraf sağlayıcılar',
        terms_s6_p1: 'Oblivio, gizlilik ve kullanım şartlarından ilgili sağlayıcıların sorumlu olduğu harici hizmetleri (OpenAI, Supabase, Railway ve İsviçre barındırma sağlayıcısı dahil) kullanır.',
        terms_s7_title: '7. Değişiklikler',
        terms_s7_p1: 'Bu kullanım şartları herhangi bir zamanda ayarlanabilir. Önemli değişiklikler platformda belirtilecektir. Bir değişiklikten sonra kullanıma devam etmek kabul anlamına gelir.',
        terms_s8_title: '8. İletişim',
        terms_s8_p1: 'Bu kullanım şartları hakkında sorular için: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',

        // Privacy page
        priv_label: 'Hukuki',
        priv_h1: 'Gizlilik Politikası',
        priv_updated: 'Tarih: Ocak 2026',
        priv_s1_title: '1. Sorumlu taraf',
        priv_s1_p1: 'Bu platformdaki veri işlemeden sorumlu olan:',
        priv_s1_p2: '<strong>Dennis Riccardo</strong><br>Öğrenci, ZHAW – Zürih Uygulamalı Bilimler Üniversitesi<br>E-posta: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s1_p3: 'Oblivio, bir lisans tezi kapsamında akademik bir araştırma projesidir. Ticari bir şirket değildir.',
        priv_s2_title: '2. Hangi verileri topluyoruz',
        priv_s2_p1: 'Oblivio yalnızca hizmetin işletimi için gerekli olan verileri toplar:',
        priv_s2_list: '<li><strong>Kayıt verileri:</strong> E-posta adresi, ad soyad, şifre (bcrypt hash olarak saklanır)</li><li><strong>Profil verileri:</strong> Takma ad, yaş grubu, cinsiyet, medeni durum, kişilik özellikleri, iletişim tarzı – sohbet öncesi ankette gönüllü olarak sağlanır</li><li><strong>Sohbet içeriği:</strong> Biyograf ile sohbetinizde yazdığınız tüm mesajlar</li><li><strong>Dil tercihi:</strong> Seçtiğiniz dil, tarayıcı localStorage\'da saklanır</li>',
        priv_s2_p2: '<strong>Hayır,</strong> konum verisi, cihaz parmak izi, IP adresleri (kişi tanımlama için), reklam amaçlı çerezler veya davranışsal veriler toplanmaz.',
        priv_s3_title: '3. Veri işlemenin amacı',
        priv_s3_p1: 'Toplanan veriler yalnızca aşağıdaki amaçlar için kullanılır:',
        priv_s3_list: '<li>Platformun işletimi ve biyograf sohbetinin sağlanması</li><li>Profil bilgilerinize göre AI biyografın kişiselleştirilmesi</li><li>Dijital mirasınızın daha sonra erişim için saklanması</li><li>Hesabınızın kimlik doğrulaması ve güvence altına alınması</li><li>Lisans tezi kapsamında akademik araştırma ve değerlendirme (anonim)</li>',
        priv_s4_title: '4. Üçüncü taraflara açıklama',
        priv_s4_p1: 'Verileriniz reklam amaçlı olarak <strong>satılmaz, kiralanmaz veya aktarılmaz</strong>. Platformun işletimi için aşağıdaki üçüncü taraf sağlayıcılar kullanılır:',
        priv_s4_list: '<li><strong>Supabase</strong> (veritabanı ve kimlik doğrulama)</li><li><strong>OpenAI</strong> (GPT API) – sohbet mesajları işlenmek üzere iletilir; OpenAI bunları sözleşme uyarınca model eğitimi için kullanmaz</li><li><strong>Railway</strong> (arka uç altyapısı)</li><li><strong>İsviçre barındırma sağlayıcısı</strong> (web barındırma)</li>',
        priv_s5_title: '5. Veri güvenliği',
        priv_s5_p1: 'Tarayıcı ve sunucu arasındaki tüm iletimler TLS şifrelidir. Şifreler bcrypt hash olarak saklanır. Supabase Satır Düzeyinde Güvenlik (RLS) hiçbir kullanıcının başka birinin verilerine erişememesini sağlar.',
        priv_s6_title: '6. Haklarınız',
        priv_s6_p1: 'Şu haklara sahipsiniz:',
        priv_s6_list: '<li><strong>Bilgi:</strong> Hakkınızda hangi verilerin saklandığını talep edin</li><li><strong>Düzeltme:</strong> Yanlış verilerin düzeltilmesi</li><li><strong>Silme:</strong> Tüm verilerinizin eksiksiz ve geri dönüşümsüz silinmesi</li><li><strong>Veri taşınabilirliği:</strong> Verilerinizin makine tarafından okunabilir formatta sağlanması</li><li><strong>İtiraz:</strong> Belirli işleme amaçlarına itiraz</li>',
        priv_s6_p2: 'Bu hakları kullanmak için iletişim: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s7_title: '7. Saklama süresi',
        priv_s7_p1: 'Verileriniz hesabınız aktif olduğu sürece saklanır. Silme talebinden sonra tüm veriler 7 iş günü içinde tamamen kaldırılır.',
        priv_s8_title: '8. Uygulanacak hukuk',
        priv_s8_p1: 'Bu gizlilik politikası İsviçre veri koruma yasasına (revDSG) tabidir. Oblivio AB\'den de kullanıcıları çekebileceğinden, GDPR ilkeleri mümkün olduğunca gözetilir.',

        // Beta Page
        hero_beta_cta: 'Beta Test Kullanıcısı Ol',
        beta_cta_title: 'Yarının Geleceğini Şekillendirin.',
        beta_cta_desc: 'Oblivio test aşamasında. Yerinizi şimdi alın ve hikayeleri ölümsüz kılan bir platform inşa etmemize yardımcı olun.',
        beta_label: 'Test Kullanıcısı Ol',
        beta_title: 'Hikayenin<br>Parçası Ol.',
        beta_subtitle: 'Oblivio test aşamasında. Mirasınızı korumak ve platformun geleceğini şekillendirmek için ilk olanlar arasında yer alın.',
        beta_benefit1_title: 'Erken Erişim',
        beta_benefit1_desc: 'Oblivio\'yu halka açılmadan önce deneyin ve AI\'ın mirasınızı nasıl koruduğunu ilk deneyimleyen siz olun.',
        beta_benefit2_title: 'Geleceği Şekillendirin',
        beta_benefit2_desc: 'Geri bildiriminiz platformun geleceğini şekillendirir. Her yanıt Oblivio\'yu daha iyi yapmamıza yardımcı olur.',
        beta_benefit3_title: 'Ücretsiz',
        beta_benefit3_desc: 'Ücretsiz tam erişim. Miras korumanın herkes için erişilebilir olması gerektiğine inanıyoruz.',
        beta_form_title: 'Kaydolun ve bize katılın.',
        beta_form_desc: 'Kaydolun, erişiminiz hazır olduğunda sizinle iletişime geçeceğiz. Spam yok, söz.',
        beta_name_label: 'Ad',
        beta_email_label: 'E-posta',
        beta_name_placeholder: 'Adınız',
        beta_email_placeholder: 'sizin@email.com',
        beta_submit: 'Şimdi Kaydol',
        beta_submitting: 'Gönderiliyor...',
        beta_success: 'Teşekkürler! Sizinle iletişime geçeceğiz.',
        beta_error: 'Bir hata oluştu. Lütfen tekrar deneyin.',
        beta_duplicate: 'Bu e-posta zaten kayıtlı.',
        beta_privacy_note: 'Kaydolarak <a href="terms.html">Kullanım Şartlarımızı</a> ve <a href="privacy.html">Gizlilik Politikamızı</a> kabul etmiş olursunuz.',

        // Page titles
        page_title_index: 'Oblivio – Hafızanın Ötesinde',
        page_title_about: 'Oblivio Hakkında – Oblivio',
        page_title_features: 'Teknoloji – Oblivio',
        page_title_blog: 'Blog – Oblivio',
        page_title_faq: 'SSS – Oblivio',
        page_title_pricing: 'Fiyatlandırma – Oblivio',
        page_title_security: 'Güvenlik – Oblivio',
        page_title_contact: 'İletişim – Oblivio',
        page_title_journey: 'Yolculuğunuz – Oblivio',
        page_title_biographer: 'Biyograf – Oblivio',
        page_title_login: 'Giriş Yap – Oblivio',
        page_title_signup: 'Kayıt Ol – Oblivio',
        page_title_privacy: 'Gizlilik Politikası – Oblivio',
        page_title_terms: 'Kullanım Şartları – Oblivio',
        page_title_404: 'Sayfa Bulunamadı – Oblivio',
        page_title_legacy: 'Miras – Oblivio',

        // Legacy Chat
        legacy_title: 'Bir Mirası Deneyimleyin',
        legacy_subtitle: 'Bir mirasla konuşmak için erişim kodunu girin.',
        legacy_code_placeholder: 'Erişim kodu',
        legacy_connect_btn: 'Bağlan',
        legacy_invalid_code: 'Geçersiz kod. Lütfen tekrar deneyin.',
        legacy_no_data: 'Miras verisi bulunamadı.',
        legacy_error: 'Bir hata oluştu. Lütfen tekrar deneyin.',
        legacy_loading: 'Bağlanıyor...',
        legacy_chat_title: 'Sohbet',
        legacy_chat_subtitle: '{name} mirasıyla bir sohbet',
        legacy_input_placeholder: 'Bir mesaj yazın...',
        legacy_ended: 'Sohbet sona erdi.',
        legacy_send_error: 'Mesaj gönderilemedi. Lütfen tekrar deneyin.',
        // Legacy Visitor Info
        legacy_visitor_title: 'Başlamadan önce',
        legacy_visitor_subtitle: 'Sohbetin daha kişisel hissettirmesi için.',
        legacy_visitor_name_label: '{name} size ne desin?',
        legacy_visitor_name_placeholder: 'Adınız',
        legacy_visitor_relation_label: '{name} ile ilişkiniz nedir?',
        legacy_visitor_relation_placeholder: 'Lütfen seçin...',
        legacy_visitor_rel_spouse: 'Eş',
        legacy_visitor_rel_child: 'Çocuk',
        legacy_visitor_rel_parent: 'Ebeveyn',
        legacy_visitor_rel_sibling: 'Kardeş',
        legacy_visitor_rel_grandchild: 'Torun',
        legacy_visitor_rel_friend: 'Arkadaş',
        legacy_visitor_rel_relative: 'Akraba',
        legacy_visitor_rel_other: 'Diğer',
        legacy_visitor_gender_label: 'Cinsiyet',
        legacy_visitor_gender_placeholder: 'Lütfen seçin...',
        legacy_visitor_gender_male: 'Erkek',
        legacy_visitor_gender_female: 'Kadın',
        legacy_visitor_gender_other: 'Diğer',
        legacy_visitor_start: 'Sohbete başla',
        legacy_visitor_required: 'Lütfen tüm alanları doldurun.',
        // Legacy Conversation Mode
        legacy_mode_active: 'Varyant 2',
        legacy_mode_passive: 'Varyant 3',
        legacy_mode_analysis: 'Varyant 1',
        legacy_passive_hint: '{name} ile sohbeti başlatmak için bir mesaj yazın…',
        legacy_mode_switch_confirm: 'Mod değiştirilsin mi? Mevcut sohbet yeniden başlatılacak.',

        // Biographer Completion — Access Code
        bio_complete_code_desc: 'Bu kodu sevdiklerinizle paylaşın:',
        bio_complete_code_copy: 'Kodu kopyala',
        bio_complete_code_copied: 'Kopyalandı!',
        bio_complete_code_email: 'E-posta ile paylaş',
        bio_complete_email_subject: 'Oblivio erişim kodunuz:',
        bio_complete_email_greeting: 'Merhaba',
        bio_complete_email_line1: 'Biyografi başarıyla tamamlandı!',
        bio_complete_email_line2: 'Erişim kodu:',
        bio_complete_email_line3: 'Mirasla konuşmak için bu sayfayı ziyaret edin:',

        // Journey — Access Code
        journey_your_code: 'Erişim Kodunuz',
        journey_code_desc: 'Sevdiklerinizin mirasınızla konuşabilmesi için bu kodu paylaşın.',
        journey_email_code: 'E-posta ile paylaş'
};
