// Oblivio translations — ja
window._oblivioLang = {
// Navigation
        nav_home: 'ホーム',
        nav_features: '機能',
        nav_philosophy: 'フィロソフィー',
        nav_journey: 'ジャーニー',
        nav_login: 'ログイン',
        nav_signup: '新規登録',
        nav_logout: 'ログアウト',
        nav_back: '← 戻る',
        nav_back_home: '← ホームに戻る',

        // Hero Section
        hero_subtitle: '世代を超えて生き続けるデジタルレガシー。あなたの本質を残し、知恵を分かち合い、思い出以上のものを遺しましょう。',
        hero_cta: '今すぐ始める',

        // Features Section
        features_title: '本質を残す',
        features_subtitle: '3つのステップで築くあなたのレガシー。',
        feature1_title: '新規登録',
        feature1_desc: '数分でアカウントを作成できます。あなたのデータはエンドツーエンド暗号化で保存され、アクセスできるのはあなただけです。',
        feature2_title: 'あなたの物語を語る',
        feature2_desc: '私たちのバイオグラファーが、日常の何気ない瞬間や大切な思い出から、心の奥にある価値観や人生の知恵まで、あなたの人生の章をたどるお手伝いをします。',
        feature3_title: 'Oblivioを共有する',
        feature3_desc: '大切な人に、時を超えて残るものを贈りましょう。あなたの声、価値観、そして愛を、一生涯を超えて届ける生きたレガシーです。',

        // Philosophy Section
        philosophy_title: '記憶を超えて',
        philosophy_p1: 'Oblivioは単なるデータの保管庫ではありません。あなたの人柄、価値観、そして愛がいつまでも息づく、生きたレガシーです。',
        philosophy_p2: '私たちは、すべての人が残すに値する唯一無二の知恵を持っていると信じています。子どもたちへ、孫たちへ、そしてこれから先のすべての人へ。',
        philosophy_p3: '時は流れても、本質は残ります。',

        // Journey Page
        journey_welcome: 'Oblivioへようこそ',
        journey_subtitle: '今日は何をしますか？',
        journey_card1_label: 'あなたのために',
        journey_card1_title: 'あなたの物語を語る',
        journey_card1_desc: 'あなたの思い出、経験、そして人生の知恵を共有しましょう。バイオグラファーが丁寧にガイドしながら、大切な人たちへのレガシーとしてあなたの物語を記録します。',
        journey_card1_cta: '会話を始める',
        journey_card2_label: '大切な人のために',
        journey_card2_title: 'レガシーを体験する',
        journey_card2_desc: '特別な方が遺したレガシーと対話しましょう。その方の物語を聞き、知恵を発見し、いつでもその存在を感じることができます。',
        journey_card2_cta: '会話を始める',
        journey_coming_soon: '近日公開',

        // Login Page
        login_title: 'おかえりなさい',
        login_subtitle: 'ログインしてジャーニーを続けましょう',
        login_email: 'メールアドレス',
        login_password: 'パスワード',
        login_button: 'ログイン',
        login_signing_in: 'ログイン中...',
        login_no_account: 'アカウントをお持ちでないですか？',
        login_create_here: 'こちらから作成',
        login_success: 'ログインに成功しました。リダイレクト中...',

        // Signup Page
        signup_title: 'アカウント作成',
        signup_subtitle: '今日からレガシーの旅を始めましょう',
        signup_name: '氏名',
        signup_name_placeholder: 'あなたのお名前',
        signup_email: 'メールアドレス',
        signup_email_placeholder: 'your@email.com',
        signup_password: 'パスワード',
        signup_password_placeholder: '安全なパスワードを作成',
        signup_password_req: '6文字以上で入力してください',
        signup_confirm: 'パスワード確認',
        signup_confirm_placeholder: 'パスワードを再入力',
        signup_button: 'アカウント作成',
        signup_creating: 'アカウント作成中...',
        signup_have_account: 'すでにアカウントをお持ちですか？',
        signup_signin_here: 'こちらからログイン',
        signup_success: 'アカウントが正常に作成されました。ログインページへリダイレクト中...',
        signup_error_match: 'パスワードが一致しません',
        signup_error_length: 'パスワードは6文字以上で入力してください',

        // Biographer Page
        bio_title: 'バイオグラファー',
        bio_subtitle: '一緒にあなたの物語を残しましょう',
        bio_input_placeholder: 'ここに回答を入力してください...',
        bio_send: '送信',
        bio_complete_title: '伝記が完成しました',
        bio_complete: 'あなたの物語を共有してくださり、ありがとうございます。レガシーは丁寧に準備されています — すべての準備が整い次第、Dennisからご連絡いたします。',

        // Biographer Questions
        bio_q1: 'こんにちは！バイオグラファーです。あなたのレガシーを残すお手伝いをいたします。まず、お名前をお聞かせください。',
        bio_q2: 'あなたの子ども時代について教えてください。どこで育ちましたか？一番大切な思い出は何ですか？',
        bio_q3: 'あなたの人生で最も大切にしている価値観は何ですか？どのような信念が日々の判断の指針になっていますか？',
        bio_q4: 'あなたの人生に最も大きな影響を与えた人は誰ですか？その方は今のあなたをどのように形づくりましたか？',
        bio_q5: '人生で最も誇りに思っている成果は何ですか？',
        bio_q6: '未来の世代に伝えたい教訓はありますか？',
        bio_q7: '大切な人にひとつだけアドバイスを贈るとしたら、何を伝えますか？',
        bio_q8: '人生で最も喜びを感じるのはどんなときですか？',
        bio_q9: 'あなたの人生の物語について、他に共有したいことはありますか？',

        // Language Selection Modal
        lang_modal_title: '言語を選択してください',
        lang_modal_subtitle: 'バイオグラファーとの会話で使用する言語を選択してください',
        lang_modal_continue: '続ける',

        // Footer
        footer_tagline: '忘れられないものを残す。<br>永遠のレガシー。',
        footer_product: 'プロダクト',
        footer_features: '機能',
        footer_pricing: '料金',
        footer_security: 'セキュリティ',
        footer_faq: 'よくある質問',
        footer_company: '会社情報',
        footer_about: 'Oblivioについて',
        footer_blog: 'ブログ',
        footer_careers: '採用情報',
        footer_press: 'プレス',
        footer_legal: '法的情報',
        footer_privacy: 'プライバシーポリシー',
        footer_terms: '利用規約',
        footer_imprint: '運営者情報',
        footer_contact: 'お問い合わせ',
        footer_rights: '© 2026 Oblivio. All rights reserved.',
        footer_tech: 'テクノロジー',

        // Nav sub-page links
        nav_tech_link: 'テクノロジー',
        nav_about_link: 'Oblivioについて',
        nav_start_link: 'スタート',

        // Security page
        sec_label: 'セキュリティ',
        sec_h1: 'あなたの物語は<br>あなただけのものです。',
        sec_sub: 'Oblivioに共有いただく内容は、あなたにとって最もプライベートなものです。私たちはそれにふさわしい扱いをいたします。',
        sec_c1_title: '暗号化',
        sec_c1_desc: 'すべての通信はTLS暗号化されています。データはSupabaseに保存時暗号化で保管されます。誰も平文で読むことはできません。',
        sec_c2_title: 'Row Level Security',
        sec_c2_desc: 'Supabase RLSにより、すべてのデータベースクエリがあなた自身のデータのみを返すことが保証されます。他のユーザーのデータへのアクセスは技術的に不可能です。',
        sec_c3_title: 'JWT認証',
        sec_c3_desc: 'アカウントへのアクセスは、署名付きJSON Web Tokenによって保護されています。期限切れまたは無効なトークンは自動的に拒否されます。',
        sec_c4_title: 'スイスのインフラ',
        sec_c4_desc: 'フロントエンドは認定されたスイスのホスティングプロバイダーを通じて運営されています。すべてのデータ処理にはスイスのデータ保護法（revDSG）が最低基準として適用されます。',
        sec_c5_title: 'トラッキングなし、広告なし',
        sec_c5_desc: 'Oblivioは広告トラッカー、サードパーティの分析サービスを一切使用せず、ユーザーデータを誰にも販売しません。',
        sec_c6_title: '削除する権利',
        sec_c6_desc: 'いつでもデータの削除をリクエストできます。アカウント、会話内容、レガシーは完全かつ不可逆的に削除されます。',
        sec_auth_title: '認証とアクセス',
        sec_auth_p1: 'Oblivioへのアクセスは、確認済みのメールアドレスと自分で設定したパスワードの組み合わせによってのみ行われます。パスワードは平文で保存されることはありません。Supabase Authは、パスワード保存の最も安全な標準のひとつである<strong>bcrypt</strong>ベースのハッシュを使用しています。',
        sec_auth_p2: 'セッションは有効期限の短いJWTトークンで管理されます。一定期間後、トークンは自動的に更新または無効化されるため、期限切れのセッションではアクセスできません。',
        sec_auth_box: '<strong>Row Level Security (RLS)</strong>はすべてのテーブルで有効になっています。これは、アプリケーションロジックに技術的なエラーが発生した場合でも、サーバーレベルでデータベースが他のユーザーのデータへのアクセスを確実に防ぐことを意味します。',
        sec_dm_title: 'データ最小化',
        sec_dm_p1: 'Oblivioが収集するのは、サービスに必要なデータのみです：氏名、メールアドレス、言語設定、バイオグラファーとの会話内容。技術的に必要な範囲を超えた位置データ、デバイスフィンガープリント、行動パターン、その他のメタデータは収集しません。',
        sec_dm_p2: '会話内容はレガシーの生成にのみ使用され、その他の分析、サードパーティのAIモデルトレーニング、または共有の対象にはなりません。',
        sec_ai_title: 'AIリクエスト',
        sec_ai_p: '会話内容は処理のためにOpenAI GPT APIに送信されます。OpenAIは、ビジネス顧客からのAPIリクエストを自社モデルのトレーニングに使用しないことを契約で約束しています。送信は暗号化（TLS 1.3）でのみ行われ、処理期間中のみで、OpenAIでの永続的な保存はありません。',

        // Pricing page
        price_label: '料金',
        price_h1: '夢に<br>請求書は送りません。',
        price_sub: 'Oblivioはすべてのユーザーに無料で提供され、今後もそうあり続けます。その背景にある正直な話をお伝えします。',
        price_s1_title: 'APIの真実',
        price_s1_p1: 'バイオグラファーとの会話の裏には、実際のコストがかかっています。あなたが書くメッセージはOpenAIのデータセンターに送られ、思慮深く共感的な応答として返ってきます。保存されるすべての記憶はSupabaseサーバー上のスペースを占めます。PROMISE AIへのすべてのリクエストはRailway上の計算リソースを消費します。',
        price_s1_p2: 'これらは仮定上のコストではありません。会話のたびに発生する実際のAPI料金です：',
        price_cost1_title: 'OpenAI (GPT API)',
        price_cost1_desc: '会話ブロックごとにトークンコストが発生し、会話の深さとシステムコンテキストの長さによって変動します。',
        price_cost2_title: 'Supabase',
        price_cost2_desc: 'データベースクエリ、認証、会話履歴とレガシーの保存。',
        price_cost3_title: 'Railway',
        price_cost3_desc: 'PROMISEバックエンドサービスの継続的な運用。同時ユーザー数が多いと計算負荷が高くなります。',
        price_cost4_title: 'ウェブホスティング (CH)',
        price_cost4_desc: 'oblivio.chドメインを通じたフロントエンドのホスティングと配信。',
        price_s2_title: 'それでも無料である理由',
        price_s2_p1: 'Oblivioは情熱から生まれたプロジェクトです。ビジネスプランからではなく、シンプルな信念から生まれました：<em>すべての人は聞いてもらい、記憶される権利がある。</em>高価なソフトウェアを買える人だけではなく。',
        price_s2_p2: '自分の人生を記録し、未来の世代に自分の声を残し、知恵を伝えるという考えは、贅沢ではありません。それは深く人間的なニーズです。Oblivioは、銀行口座の残高に関係なく、このニーズに応える場所でありたいと思っています。',
        price_s2_p3: 'ZHAWの学術研究プロジェクトである現段階では、開発者がランニングコストを負担しています。大切なのは体験そのものであり、それは完全で、制限がなく、尊厳のあるものでなければなりません。',
        price_plan_label: '現在のプラン',
        price_plan_name: 'Oblivio Free',
        price_plan_price: 'CHF 0',
        price_plan_per: '/ 月',
        price_plan_desc: 'バイオグラファーへのフルアクセス、全10会話ブロック、自動レガシー保存、デジタルレガシー、すべて制限なし。',
        price_inc1: '10の会話ブロック',
        price_inc2: '自動ナレッジ保存',
        price_inc3: 'デジタルレガシー',
        price_inc4: '全8言語',
        price_inc5: '安全な暗号化',
        price_inc6: '広告なし',
        price_footnote: 'Oblivioは現在も開発が進んでいます。ElevenLabsによるボイスクローニングや親族との会話の継続など、今後の機能もこの約束の精神に基づいて導入されます：尊厳を持ち、丁寧に、そしてできる限りアクセスしやすく。',

        // FAQ page
        faq_label: 'よくある質問',
        faq_h1: 'よくある<br>ご質問',
        faq_sub: 'Oblivioについて知りたいことすべてに、明確かつ正直にお答えします。',
        faq_cat1: '一般',
        faq_q1: 'Oblivioとは何ですか？',
        faq_a1: 'Oblivioは、AIバイオグラファーに導かれながら自分の人生を記録できるデジタルプラットフォームです。生まれた会話、洞察、思い出は、大切な方が将来体験できるデジタルレガシーとして保存されます。',
        faq_q2: 'Oblivioは誰のためのものですか？',
        faq_a2: '語るべき物語を持つすべての人のためのものです。つまり、すべての人です。Oblivioは特に、自分の知恵、思い出、人柄を子どもや孫、そして未来の世代に残したいと願う方に向けています。',
        faq_q3: 'バイオグラファーはどのように機能しますか？',
        faq_a3: 'バイオグラファーは、日常生活から思い出、人間関係、価値観、レガシーまで、10のテーマ別会話ブロックを通じてあなたをガイドします。各ブロックは深い会話であり、十分に意味のある情報が集まると自動的にまとめられ、保存されます。',
        faq_q4: 'Oblivioはどの言語に対応していますか？',
        faq_a4: 'Oblivioは現在、8つの言語をサポートしています：ドイツ語、英語、フランス語、イタリア語、トルコ語、韓国語、日本語、中国語。最初の会話の開始時に伝記作家の言語を選択します。伝記作家はその後、その言語で一貫してコミュニケーションを取ります。',
        faq_cat2: '会話とバイオグラファー',
        faq_q5: '会話ブロックはいくつありますか？',
        faq_a5: '10のブロックがあります：日常生活、感情、思い出、人間関係、成長、夢、価値観、レガシー、個人的なメッセージ、締めくくり。各ブロックは独自の人生の領域に特化しており、バイオグラファーが十分に深い回答を集めた場合にのみ完了します。',
        faq_q6: '会話を一時停止して後で再開できますか？',
        faq_a6: 'はい。会話履歴はSupabaseに自動的に保存されます。再度ログインすると、現在の会話ブロックを含め、中断したところから続けることができます。',
        faq_q7: '全10ブロック完了後はどうなりますか？',
        faq_a7: '全10ブロックが完了すると、あなたの完全なデジタルレガシーが自動的に保存されます。すべての会話から得られた洞察のまとめが含まれています。将来のバージョンでは、親族がこのレガシーと対話できるようになります。',
        faq_q8: 'バイオグラファーは本当に聞いてくれるのですか、それとも定型文ですか？',
        faq_a8: 'バイオグラファーはOpenAIのGPT言語モデルによって動作しています。あなたが書いた一文一文を読み、会話全体のコンテキストを記憶し、あなたの発言に真に応答するフォローアップの質問をします。フォームではありません。本当の会話です。',
        faq_cat3: 'プライバシーとセキュリティ',
        faq_q9: '私の会話を読めるのは誰ですか？',
        faq_a9: 'あなただけです。Supabase Row Level Securityにより、すべてのデータベースクエリが技術的にあなた自身のデータに制限されます。管理者、開発者、他のユーザーがあなたの会話内容を閲覧することはできません。',
        faq_q10: '私のデータはAIトレーニングに使用されますか？',
        faq_a10: 'いいえ。OpenAIは、ビジネス顧客からのAPIリクエストをモデルトレーニングに使用しないことを契約で約束しています。会話内容は応答生成のためにのみ処理され、その後は保存されません。',
        faq_q11: 'データの削除をリクエストできますか？',
        faq_a11: 'はい、いつでも可能です。件名に「Data Deletion」と記載して<a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>にメールをお送りください。すべてのデータが完全かつ不可逆的に削除されます。',
        faq_cat4: '費用',
        faq_q12: 'Oblivioは本当に無料ですか？',
        faq_a12: 'はい。OblivioはZHAWの学術研究プロジェクトであり、隠れた料金、フリーミアム制限、広告なしで、すべてのユーザーに完全無料で提供されています。詳しくは<a href="pricing.html">料金ページ</a>をご覧ください。',
        faq_q13: 'Oblivioは永久に無料ですか？',
        faq_a13: 'それが私たちの意図です。Oblivioは学士論文として作成されたため、ランニングコストは管理可能です。プロジェクトが成長した場合、ビジネスモデルの変更は透明性を持って伝えられます。',

        // Features / Technology page
        tech_label: 'テクノロジー',
        tech_h1: '永遠のための<br>アーキテクチャ',
        tech_sub: 'Oblivioは最先端の研究と思慮深いインフラを組み合わせ、すべての物語が安全に保存され、すべての会話が生き生きとし、すべてのレガシーが永続的にアクセス可能であることを実現します。',
        tech_intro: 'Oblivioの背後にあるのは既製のソリューションではなく、尊厳、セキュリティ、深さのバランスを取るシステムを共に構築する、意識的に選ばれたテクノロジーです。',
        tech_01_sub: '会話AIフレームワーク',
        tech_01_title: 'PROMISE',
        tech_01_p: 'PROMISEは<strong>ZHAW（チューリッヒ応用科学大学）</strong>の科学フレームワークで、状態ベースのマルチステップAI会話を可能にします。Oblivioのバイオグラファーは完全にPROMISE上に構築されています：10のテーマ別会話ブロックのそれぞれが、独自のシステムコンテキスト、遷移条件、自動ナレッジ抽出を持つ独立した状態です。バックエンドサービスは<strong>Railway</strong>を通じて提供され、常にスケーラブルにアクセス可能です。',
        tech_01_tag1: 'ZHAW研究',
        tech_01_tag2: 'ステートフルAI',
        tech_02_sub: '言語モデル',
        tech_02_title: 'GPT by OpenAI',
        tech_02_p: 'バイオグラファーの会話は<strong>OpenAIのGPT言語モデル</strong>によって動作しています。OpenAIのモデルは膨大な量の人間の言語で訓練されており、文脈に応じた共感的な会話を行うことができます。これにより、Oblivioは機械的ではなく、注意深い対話相手のように感じられる会話を実現します：忍耐強く、洞察力があり、常にその人に関心を持って。',
        tech_02_tag1: 'OpenAI',
        tech_02_tag2: 'GPT',
        tech_03_sub: 'データベース &amp; 認証',
        tech_03_title: 'Supabase',
        tech_03_p: 'すべてのユーザーデータ、会話履歴、保存されたレガシーは<strong>Supabase</strong>に保存されます。SupabaseはRow Level Security (RLS)を備えたオープンなPostgreSQLプラットフォームです。つまり、エラーによっても脆弱性によっても、あるユーザーが他のユーザーのデータにアクセスすることはできません。認証は暗号化されたJWTトークンで行われ、すべての接続はTLSで保護されています。',
        tech_03_tag1: 'PostgreSQL',
        tech_03_tag2: 'Row Level Security',
        tech_04_sub: 'バックエンドインフラ',
        tech_04_title: 'Railway',
        tech_04_p: 'PROMISEバックエンドサービスは<strong>Railway</strong>上で稼働しています。Railwayは自動デプロイ、スケーリング、モニタリングを兼ね備えたモダンなクラウドプラットフォームです。バイオグラファーシステムへのすべての変更は、手動のサーバー設定なしに数分以内にライブになります。Railwayにより、Oblivioは負荷がかかった状態でも安定的にアクセス可能です。',
        tech_04_tag1: '自動デプロイ',
        tech_04_tag2: 'クラウドインフラ',
        tech_05_sub: '音声合成 · 計画中',
        tech_05_title: 'ElevenLabs',
        tech_05_p: 'Oblivioの将来のバージョンでは、すべてのデジタルレガシーが読めるだけでなく、<em>聴ける</em>ようになります。リアルな音声合成のリーディングプラットフォームである<strong>ElevenLabs</strong>を使用して、自分の声を録音・クローニングできるようになります。親族はテキストメッセージを読むだけでなく、大切な人の親しみのある声を再び聴くことができるようになります。',
        tech_05_tag1: 'ボイスクローニング',
        tech_05_tag2: 'ロードマップ 2026',
        tech_06_sub: 'ウェブホスティング',
        tech_06_title: 'スイスのウェブホスティング',
        tech_06_p: 'Oblivioのフロントエンドは著名なスイスのホスティングプロバイダーを通じて運営されています。ドメイン<em>oblivio.ch</em>とすべての静的リソースはスイスから直接配信されます。つまり、データはスイスに留まり、スイスのデータ保護法（DSG）が適用され、優れたネットワークインフラの恩恵を受けます。',
        tech_06_tag1: 'スイスホスティング',
        tech_06_tag2: 'DSG準拠',
        tech_arch_title: 'すべてがどのように連携するか',
        tech_arch_lead: 'あなたの入力から保存された記憶まで：すべてのステップが考慮され、保護されています。',
        tech_flow1_title: '入力',
        tech_flow1_p: 'ブラウザでメッセージを入力します。HTTPS経由で暗号化されて送信されます。',
        tech_flow2_title: 'PROMISEが処理',
        tech_flow2_p: 'Railwayバックエンドサービスがメッセージを受け取り、現在の状態を判断し、OpenAI GPTに送信します。',
        tech_flow3_title: 'GPTが応答',
        tech_flow3_p: '言語モデルがバイオグラファーの現在の状態に基づいて、共感的で文脈に応じた応答を生成します。',
        tech_flow4_title: 'Supabaseが保存',
        tech_flow4_p: '会話と抽出された洞察は、あなただけがアクセスできる個人のSupabaseインスタンスに安全に保存されます。',

        // Contact page
        contact_label: 'お問い合わせ',
        contact_h1: 'お気軽に<br>ご連絡ください。',
        contact_li_title: 'Dennis Riccardo',
        contact_li_sub: 'Oblivio開発者 · ZHAW学生',
        contact_li_cta: 'プロフィールを見る',
        contact_em_title: 'メール',
        contact_em_addr: 'riccaden@students.zhaw.ch',
        contact_info: '<strong>学術的背景：</strong>Oblivioは<strong>ZHAW</strong>（チューリッヒ応用科学大学）における学士論文です。ご質問、フィードバック、コラボレーションのご提案を歓迎いたします。',

        // About page
        about_label: 'Oblivioについて',
        about_h1: 'ひとりの人間。<br>ひとつのアイデア。<br>ひとつのレガシー。',
        about_sub: 'Oblivioは、すべての人が聞いてもらい、記憶されるに値するという信念から生まれました。自らの生涯をはるかに超えて。',
        about_badge: '学士論文',
        about_inst: '<strong>ZHAW（チューリッヒ応用科学大学）</strong> · 経営法学部 · ビジネスインフォマティクス · 2026',
        about_role: '開発者 · 学生',
        about_bio1: '私はヴィンタートゥールのZHAWでビジネスインフォマティクスを学んでいます。テクノロジーの論理的な精密さとビジネスの戦略的思考という、私が愛する2つの世界をつなぐこのプログラムに最初から魅了されてきました。',
        about_bio2: 'それと並行して、スイス最大級の健康保険会社でプロジェクトマネージャーとして働いています。そこでは、複雑なシステムがどのように組織され、人々がどのように導かれ、変革がどのように持続的に実施されるかを日々学んでいます。それは、実際の人々の幸福というケアを中心に大きく回っている世界です。',
        about_bio3: 'Oblivioは私の学士論文です。しかしそれ以上に、私が大切にするすべてが集まるプロジェクトです。AIとモダンなインフラによる技術的実装。会話、思い出、時を超えたつながりへの欲求という人間的な側面。そして、テクノロジーは人間に奉仕すべきであり、その逆ではないという信念。',
        about_bio4: 'Oblivioでの私の目標は、ただ機能するだけでなく、正しく感じられるものを作ることでした。最も親密なもの、つまり人間自身の人生を、尊厳を持って扱うプラットフォームです。',
        about_values_title: 'Oblivioを動かすもの',
        about_v1_title: '尊厳',
        about_v1_p: 'すべての物語は敬意を持って扱われるべきです。データポイントとしてではなく、ひとりの人間の人生の成果として。',
        about_v2_title: 'アクセシビリティ',
        about_v2_p: '自分の人生を残すことは、お金の問題であってはなりません。Oblivioは無料です。それは意図的な選択です。',
        about_v3_title: '深さ',
        about_v3_p: '表面的な回答は表面的な記憶を生みます。バイオグラファーは、最も大切なものが浮かび上がるまで問い続けます。',

        // Blog page
        blog_label: 'ブログ',
        blog_h1: 'Oblivioは<br>こうして生まれた。',
        blog_sub: 'アイデアからプラットフォームへの道のりにおける決断、回り道、気づきの正直な記録。',
        blog_date: '2026年春',
        blog_tag1: '学士論文',
        blog_tag2: '開発',
        blog_art_h2: 'アイデアから生きたプラットフォームへ：Oblivioの開発ストーリー',
        blog_art_lead: '「人がいなくなったとき、何が残るのか？」と自問したとき、何が始まるのでしょうか。Oblivioはこの問いから始まり、当初予想していたよりも多くの技術的決断を含む答えにたどり着きました。',
        blog_h3_1: '出発点となった問い',
        blog_p1_1: 'Oblivioのアイデアはデスクの前ではなく、個人的な静寂の瞬間に生まれました。失った人にまだ何を聞きたいだろうか？そして逆に、自分がいなくなったとき、何を残したいだろうか？',
        blog_p1_2: 'これらの問いが私の学士論文へとつながりました。目標は野心的でした：すべての人がデジタルレガシーの形で自分の人生を記録できるAI搭載プラットフォーム。深く、個人的で、永続的な。',
        blog_quote: '「フォームではない。アンケートでもない。本当に聴いてくれる会話。」',
        blog_h3_2: 'PROMISE：核心',
        blog_p2_1: 'Oblivioの技術的バックボーンは<strong>PROMISE</strong>です。ZHAWで開発された状態ベースの会話フレームワークです。単純なチャットボットシーケンスではなく、PROMISEは真の会話状態を可能にします：10のバイオグラファーブロックのそれぞれが、独自のシステムコンテキスト、遷移条件、自動ナレッジ抽出を持つ独立した状態です。',
        blog_p2_2: '中心的な課題：ブロックはいつ次に移行するのか？最初の解決策は二重条件でした：ユーザーが明示的に「続ける」と言い、かつガードが十分なトピックがカバーされたことを確認する必要がありました。合理的に聞こえますが、深刻なバグにつながりました。',
        blog_technote: '<strong>バグ：</strong> <code>Transition(List.of(trigger, guard), ...)</code> — AND論理。長い会話の後（Guard = true）にユーザーが「いいえ」と言った場合（Trigger = true）、<code>TransferUtterancesAction</code>が発火し、会話履歴全体が後続のすべての状態に転送されたため、すべてのガードが同時にtrueと評価されました。ブロック1が「伝記完了」に直接ジャンプしました。<br><br><strong>解決策：</strong> <code>Transition(List.of(guard), ...)</code> — ガードのみ。トリガーなし。十分に意味のある回答が集まると自動的に切り替わります。',
        blog_h3_3: 'ひとつではなく10のブロック',
        blog_p3_1: 'バイオグラファーのオリジナルバージョンは単一の状態、構造のない終わりのない会話フローでした。問題は、テーマ別のガイダンスがないと、人生の多くの領域が触れられないままになることでした。ユーザーは子ども時代の思い出については語りましたが、自分の価値観については決して語りませんでした。仕事については語りましたが、夢については決して語りませんでした。',
        blog_p3_2: '解決策は10のテーマ別ブロックへの切り替えでした：Ice-Breaker (Geschmack & Vorlieben)、Alltag & Lebenswelt、Kommunikationsstil、Erinnerungen & Schlüsselerlebnisse、Emotionen & Beziehungsmuster、Beziehungen & Fremdbild、Werte & Überzeugungen、Macken & Widersprüche、Vermächtnis & Zukunft、そしてAbschluss。各ブロックは人生の特定の領域を完全に探求するよう設計されており、それが完了した場合にのみ自動的に次へ切り替わります。',
        blog_h3_4: 'フロントエンド：機能と尊厳の間で',
        blog_p4_1: 'Oblivioのデザインは明確な前提に従いました：アプリのようではなく、手紙のように感じられること。カラーパレット（クリーム、チャコール、錆赤、モスグリーン）は、温かさと永続性を伝えるために意図的に選ばれました。Crimson ProとDM Serif Displayのフォントがインターフェースに文学的な雰囲気をもたらします。',
        blog_p4_2: 'ブロック1の後に表示され、ブロック1から10までユーザーに寄り添うプログレスバーは、小さいながらも重要なUX上の決断でした：目に見える進捗は会話を中断することなくオリエンテーションを提供します。その状態は<code>localStorage</code>に保存されるため、リフレッシュ後も維持されます。',
        blog_h3_5: 'ブロック0のアンケート',
        blog_p5_1: '実際のバイオグラファーが始まる前に、ユーザーは短いアンケートを通過します：名前、年齢層、性別、婚姻状況、性格特性、コミュニケーションスタイル。この情報はコンテキストとしてバイオグラファーに渡されます。バイオグラファーは相手が誰であるかを知り、トーン、質問、反応をそれに応じて適応させることができます。',
        blog_p5_2: 'この「ブロック0」は7言語（ドイツ語、英語、フランス語、イタリア語、韓国語、日本語、中国語）で利用可能で、素早く、控えめで、正直に感じられるように設計されました。事前の同意フォームは、何が保存され、なぜ保存されるかを明確に伝えます。',
        blog_h3_6: 'Supabase、Railway、スイスホスティング',
        blog_p6_1: 'Oblivioのインフラは、シンプルな原則に従って選ばれました：各コンポーネントがそのカテゴリーで最良であり、うまく連携し、不必要な複雑さを加えないこと。認証とデータベースにはSupabase。git pushのたびに自動デプロイされるPROMISEバックエンドサービスにはRailway。フロントエンドホスティングにはスイスのプロバイダー。',
        blog_p6_2: 'Railwayは特に価値がありました：Javaバックエンドへのすべての変更（新しいガード、新しいプロンプト、新しい言語サポート）が数分以内にライブになります。これにより、イテレーション速度が大幅に向上しました。',
        blog_h3_7: 'すでに達成されたこと',
        blog_p7_1: 'Oblivioは当初のビジョンを超えて成長しました：レガシーチャットが稼働しています — 親族はアクセスコードを使って保存されたレガシーと対話できます。ElevenLabsの音声合成がバイオグラファーに聴ける声を与え、Web Speech APIのおかげでユーザーは音声入力で回答を口述することもできます。',
        blog_p7_2: 'Oblivioは完成していますが、終わりではありません。それは、行われるすべての会話によってより豊かになるプラットフォームです。',
        blog_date_v2: '2026年5月9日',
        blog_tag_v2_1: 'アップデート',
        blog_tag_v2_2: 'イテレーション',
        blog_v2_h2: '4言語から8言語へ：大規模な改修',
        blog_v2_lead: 'ここ数週間でOblivioは成長しました。ペルソナの数だけでなく、機能の深さにおいても。ここでは、最も重要な変更点の概要を紹介します。',
        blog_v2_h3_1: '4言語ではなく8言語に',
        blog_v2_p1: 'Oblivioは現在、ドイツ語、英語、フランス語、イタリア語、トルコ語、韓国語、日本語、中国語の8言語をサポートしています。国際的なリーチをさらに拡大するため、8番目の言語としてトルコ語が追加されました。そのために、すべてのUIテキスト、バイオグラファーのアンケート、ブロック指示が補完されました。',
        blog_v2_h3_2: '3つの会話バリエーション',
        blog_v2_p2_1: 'レガシーペルソナには、3つの異なるモードでアプローチできるようになりました。バリエーション1は、レーダーチャート、コミュニケーションDNA、人生パターンを含む完全な性格分析を提供します。バリエーション2は、ペルソナが積極的に会話を始めます。バリエーション3は、訪問者の最初のメッセージを静かに待ちます。',
        blog_v2_p2_2: '各バリエーションは、異なる感情的状況に適しています：深い理解、低い参入障壁、または会話の始まり方に対する完全なコントロール。',
        blog_v2_h3_3: '自動コンテキスト圧縮',
        blog_v2_p3: 'PROMISEバックエンドの技術的改善：ユーザーメッセージが20件を超えると、古い会話の貢献は自動的に要約され、コンパクトなシステムメッセージに置き換えられます。これにより、トークンコストを一定に保ちながら、最も重要な内容を保持できます — 人間の記憶が詳細を薄れさせながらも全体像を保持するのと似ています。',
        blog_v2_h3_4: '目に見える進歩と目に見えない整理作業',
        blog_v2_p4_1: '舞台裏では、多くのコンポーネントが洗練されました：リポジトリが再構成され（ドキュメントとSQLスクリプト用の別フォルダ）、すべてのJavaクラスに詳細なコメントが追加され、ウェブサイトの古いテキストが更新されました。',
        blog_v2_p4_2: '人物ページも改訂されました：個々のペルソナ名への古い言及は一般的な表現に置き換えられ、将来のペルソナに対してもプラットフォームが一貫性を保つようにしました。',
        blog_v2_h3_5: '15人の参加者、新しいペルソナ、新しい声',
        blog_v2_p5: '合計15人がこの研究に参加し、自分の人生の物語をバイオグラファーと共有しました。これらの物語のそれぞれが、それぞれのペルソナになりました — それぞれのプロフィール写真、ElevenLabsによるそれぞれの声、そして3つの会話バリエーションのための3部構成のシステムプロンプトを伴って。これによりプラットフォームは多様性を獲得しました — さまざまな言語、年齢層、人生の道のりがここで出会います。',
        blog_v2_p_final: 'Oblivioは進化し続けています — 大きな一足飛びではなく、それぞれが会話をもう少し本物に、もう少し人間らしくする多くの小さな改善を通じて。',

        // Terms page
        terms_label: '法的情報',
        terms_h1: '利用規約',
        terms_updated: '施行日：2026年1月',
        terms_highlight: 'Oblivioは、ZHAW（チューリッヒ応用科学大学）における学士論文の一環として作成された学術研究プロジェクトです。本プラットフォームの利用により、この利用規約に同意したものとみなされます。',
        terms_s1_title: '1. サービスの性質',
        terms_s1_p1: 'Oblivioは、ZHAWの学士論文の一環として開発された非営利の学術プラットフォームです。本サービスは無料で、営利目的なく一般に公開されています。',
        terms_s1_p2: '本プラットフォームは現在も開発中です。機能、可用性、コンテンツは随時変更される可能性があります。永続的な運用の保証はありません。',
        terms_s2_title: '2. 許可される利用',
        terms_s2_p1: 'Oblivioは以下の目的で利用できます：',
        terms_s2_list1: '<li>個人的なデジタルレガシーの記録</li><li>AIバイオグラファーとの会話</li><li>保存されたコンテンツの取得と管理</li>',
        terms_s2_p2: '以下の目的での利用は禁止されています：',
        terms_s2_list2: '<li>自動化された大量リクエストまたはAPIの不正利用</li><li>違法、攻撃的、または有害なコンテンツの入力</li><li>他者のデータへのアクセスまたはセキュリティ対策の回避の試み</li><li>書面による許可のない商業目的でのあらゆる利用</li>',
        terms_s3_title: '3. あなたのコンテンツ',
        terms_s3_p1: 'Oblivioに入力したすべてのコンテンツ（会話、回答、プロフィール情報）はあなたの知的財産です。サービスの技術的運用のために、このコンテンツを処理・保存する権利をOblivioに付与するものとします。',
        terms_s3_p2: '学術研究のため、会話パターンと利用行動は<strong>完全に匿名化された形式</strong>で評価される場合があります。個人の特定は意図されておらず、技術的にも不可能です。',
        terms_s4_title: '4. 免責事項',
        terms_s4_p1: 'Oblivioは「現状のまま」提供されます。中断のない可用性、エラーのないこと、データの永続的な保存について保証はありません。学術プロジェクトの一環として、本サービスはいつでも中止、変更、制限される可能性があります。',
        terms_s4_p2: 'バイオグラファーのAI生成による応答は、個人的な振り返りと記録のためにのみ提供されます。心理的、医学的、法的なアドバイスを構成するものではありません。',
        terms_s5_title: '5. 知的財産権',
        terms_s5_p1: 'Oblivioプラットフォームのデザイン、コード、テキスト、その他すべてのコンテンツ（ユーザーコンテンツを除く）は著作権で保護されており、Dennis Riccardoの所有物です。書面による許可なしの使用や複製（部分的なものを含む）は禁止されています。',
        terms_s6_title: '6. サードパーティプロバイダー',
        terms_s6_p1: 'Oblivioは外部サービス（OpenAI、Supabase、Railway、スイスのホスティングプロバイダーを含む）を使用しており、それぞれのプライバシーポリシーと利用規約はそれぞれのプロバイダーが責任を負います。Oblivioの利用により、運用に必要な範囲でこれらのサービスの利用に暗黙的に同意するものとします。',
        terms_s7_title: '7. 変更',
        terms_s7_p1: 'この利用規約はいつでも改定される場合があります。重要な変更はプラットフォーム上で告知されます。変更後の継続利用は承諾とみなされます。',
        terms_s8_title: '8. お問い合わせ',
        terms_s8_p1: 'この利用規約に関するご質問は：<a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',

        // Privacy page
        priv_label: '法的情報',
        priv_h1: 'プライバシーポリシー',
        priv_updated: '施行日：2026年1月',
        priv_s1_title: '1. 責任者',
        priv_s1_p1: '本プラットフォームにおけるデータ処理の責任者：',
        priv_s1_p2: '<strong>Dennis Riccardo</strong><br>ZHAW（チューリッヒ応用科学大学）学生<br>メール：<a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s1_p3: 'Oblivioは学士論文の一環として行われる学術研究プロジェクトです。商業企業ではありません。',
        priv_s2_title: '2. 収集するデータ',
        priv_s2_p1: 'Oblivioはサービスの運用に必要なデータのみを収集します：',
        priv_s2_list: '<li><strong>登録データ：</strong>メールアドレス、氏名、パスワード（bcryptハッシュとして保存）</li><li><strong>プロフィールデータ：</strong>ニックネーム、年齢層、性別、婚姻状況、性格特性、コミュニケーションスタイル — 会話前のアンケートで任意に提供</li><li><strong>会話コンテンツ：</strong>バイオグラファーとの会話で入力したすべてのメッセージ</li><li><strong>言語設定：</strong>選択した言語（DE、EN、IT、KO）、ブラウザのlocalStorageに保存</li>',
        priv_s2_p2: '位置データ、デバイスフィンガープリント、IPアドレス（個人特定目的）、広告目的のCookie、行動データは<strong>一切</strong>収集しません。',
        priv_s3_title: '3. データ処理の目的',
        priv_s3_p1: '収集されたデータは以下の目的でのみ使用されます：',
        priv_s3_list: '<li>プラットフォームの運用およびバイオグラファー会話の提供</li><li>プロフィール情報に基づくAIバイオグラファーのパーソナライズ</li><li>後日取得するためのデジタルレガシーの保存</li><li>アカウントの認証と保護</li><li>学士論文における学術研究と評価（匿名化）</li>',
        priv_s4_title: '4. 第三者への開示',
        priv_s4_p1: 'あなたのデータは販売、貸与、広告目的での第三者への提供は<strong>一切</strong>行いません。プラットフォームの運用のために以下のサードパーティプロバイダーを使用しています：',
        priv_s4_list: '<li><strong>Supabase</strong>（データベースと認証） — データはSupabaseのプライバシーポリシーに従って処理されます</li><li><strong>OpenAI</strong>（GPT API） — 会話メッセージは処理のために送信されます。OpenAIは契約に基づきこれらをモデルトレーニングに使用しません</li><li><strong>Railway</strong>（バックエンドインフラ） — 永続的なデータ保存なしでのAPIリクエスト処理</li><li><strong>スイスのホスティングプロバイダー</strong>（ウェブホスティング、スイス） — 静的ファイルの配信</li>',
        priv_s5_title: '5. データセキュリティ',
        priv_s5_p1: 'ブラウザとサーバー間のすべての通信はTLS暗号化されています。パスワードはbcryptハッシュとして保存されます。Supabase Row Level Security (RLS)により、あるユーザーが他のユーザーのデータにアクセスすることはできません。データベースへのアクセスは署名付きJWTトークンを通じてのみ行われます。',
        priv_s6_title: '6. あなたの権利',
        priv_s6_p1: 'あなたには以下の権利があります：',
        priv_s6_list: '<li><strong>情報開示：</strong>あなたについて保存されているデータの開示を請求すること</li><li><strong>訂正：</strong>誤ったデータの訂正</li><li><strong>削除：</strong>すべてのデータの完全かつ不可逆的な削除</li><li><strong>データポータビリティ：</strong>機械可読形式でのデータの提供</li><li><strong>異議申し立て：</strong>特定の処理目的に対する異議</li>',
        priv_s6_p2: 'これらの権利を行使するには：<a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s7_title: '7. 保存期間',
        priv_s7_p1: 'あなたのデータは、アカウントが有効な間保存されます。削除リクエスト後、すべてのデータは7営業日以内に完全に削除されます。学術プロジェクトの終了後、すべての個人データは削除されます。匿名化された評価結果は学士論文に残る場合があります。',
        priv_s8_title: '8. 準拠法',
        priv_s8_p1: 'このプライバシーポリシーはスイスのデータ保護法（revDSG）に準拠します。OblivioはEUからのユーザーも対象となる可能性があるため、GDPRの原則も可能な限り遵守しています。',

        // Beta Page
        hero_beta_cta: 'ベータテスターになる',
        beta_cta_title: '明日の未来を形づくる。',
        beta_cta_desc: 'Oblivioはテスト段階にあります。今すぐ参加して、物語を不滅にするプラットフォームの構築にご協力ください。',
        beta_label: 'テスターになる',
        beta_title: '物語の<br>一部になる。',
        beta_subtitle: 'Oblivioはテスト段階にあります。いち早くレガシーを残し、プラットフォームの未来を一緒に形づくりましょう。',
        beta_benefit1_title: '早期アクセス',
        beta_benefit1_desc: '一般公開前にOblivioをお試しいただけます。AIがあなたのレガシーをどのように残すかを、最初に体験してください。',
        beta_benefit2_title: '未来を形づくる',
        beta_benefit2_desc: 'あなたのフィードバックがプラットフォームの未来を形づくります。すべてのご意見がOblivioの改善に役立ちます。',
        beta_benefit3_title: '完全無料',
        beta_benefit3_desc: '費用なしでフルアクセス。レガシーの保存は、すべての人にとってアクセス可能であるべきだと私たちは信じています。',
        beta_form_title: '登録してご参加ください。',
        beta_form_desc: 'ご登録いただくと、アクセスの準備ができ次第ご連絡いたします。スパムは送りません、お約束します。',
        beta_name_label: 'お名前',
        beta_email_label: 'メールアドレス',
        beta_name_placeholder: 'あなたのお名前',
        beta_email_placeholder: 'your@email.com',
        beta_submit: '今すぐ登録',
        beta_submitting: '送信中...',
        beta_success: 'ありがとうございます！追ってご連絡いたします。',
        beta_error: 'エラーが発生しました。もう一度お試しください。',
        beta_duplicate: 'このメールアドレスはすでに登録されています。',
        beta_privacy_note: '登録することにより、<a href="terms.html">利用規約</a>および<a href="privacy.html">プライバシーポリシー</a>に同意したものとみなされます。',

        // Page titles
        page_title_index: 'Oblivio – 記憶を超えて',
        page_title_about: 'Oblivioについて – Oblivio',
        page_title_features: 'テクノロジー – Oblivio',
        page_title_blog: 'ブログ – Oblivio',
        page_title_faq: 'FAQ – Oblivio',
        page_title_pricing: '料金 – Oblivio',
        page_title_security: 'セキュリティ – Oblivio',
        page_title_contact: 'お問い合わせ – Oblivio',
        page_title_journey: 'あなたの旅 – Oblivio',
        page_title_biographer: 'バイオグラファー – Oblivio',
        page_title_login: 'ログイン – Oblivio',
        page_title_signup: '新規登録 – Oblivio',
        page_title_privacy: 'プライバシーポリシー – Oblivio',
        page_title_terms: '利用規約 – Oblivio',
        page_title_404: 'ページが見つかりません – Oblivio',
        page_title_legacy: 'レガシー – Oblivio',

        // Legacy Chat
        legacy_title: 'レガシーを体験する',
        legacy_subtitle: 'レガシーと話すにはアクセスコードを入力してください。',
        legacy_code_placeholder: 'アクセスコード',
        legacy_connect_btn: '接続',
        legacy_invalid_code: '無効なコードです。もう一度お試しください。',
        legacy_no_data: 'レガシーデータが見つかりません。',
        legacy_error: 'エラーが発生しました。もう一度お試しください。',
        legacy_loading: '接続中...',
        legacy_chat_title: '対話相手：',
        legacy_chat_subtitle: '{name}のレガシーとの対話',
        legacy_input_placeholder: 'メッセージを入力...',
        legacy_ended: '会話は終了しました。',
        legacy_send_error: 'メッセージを送信できませんでした。もう一度お試しください。',
        // Legacy Visitor Info
        legacy_visitor_title: '始める前に',
        legacy_visitor_subtitle: '会話をより個人的にするために。',
        legacy_visitor_name_label: '{name} はあなたを何と呼べばいいですか？',
        legacy_visitor_name_placeholder: 'あなたの名前',
        legacy_visitor_relation_label: '{name} とのご関係は？',
        legacy_visitor_relation_placeholder: '選択してください...',
        legacy_visitor_rel_spouse: '配偶者',
        legacy_visitor_rel_child: '子ども',
        legacy_visitor_rel_parent: '親',
        legacy_visitor_rel_sibling: 'きょうだい',
        legacy_visitor_rel_grandchild: '孫',
        legacy_visitor_rel_friend: '友人',
        legacy_visitor_rel_relative: '親戚',
        legacy_visitor_rel_other: 'その他',
        legacy_visitor_gender_label: '性別',
        legacy_visitor_gender_placeholder: '選択してください...',
        legacy_visitor_gender_male: '男性',
        legacy_visitor_gender_female: '女性',
        legacy_visitor_gender_other: 'その他',
        legacy_visitor_start: '会話を始める',
        legacy_visitor_required: 'すべての項目を入力してください。',
        // Legacy Conversation Mode
        legacy_mode_active: 'バリアント2',
        legacy_mode_passive: 'バリアント3',
        legacy_mode_analysis: 'バリアント1',
        legacy_passive_hint: '{name} にメッセージを送って会話を始めましょう…',
        legacy_mode_switch_confirm: 'モードを切り替えますか？現在の会話は再開されます。',

        // Biographer Completion — Access Code
        bio_complete_code_desc: 'このコードを大切な人と共有してください：',
        bio_complete_code_copy: 'コードをコピー',
        bio_complete_code_copied: 'コピーしました！',
        bio_complete_code_email: 'メールで共有',
        bio_complete_email_subject: 'Oblivioアクセスコード -',
        bio_complete_email_greeting: 'こんにちは',
        bio_complete_email_line1: '伝記が正常に完成しました！',
        bio_complete_email_line2: 'アクセスコード：',
        bio_complete_email_line3: 'このページにアクセスしてレガシーと対話してください：',

        // Journey — Access Code
        journey_your_code: 'あなたのアクセスコード',
        journey_code_desc: '大切な人があなたのレガシーと対話できるよう、このコードを共有してください。',
        journey_email_code: 'メールで共有'
};
