// Oblivio translations — en
window._oblivioLang = {
// Navigation
        nav_home: 'Home',
        nav_features: 'Features',
        nav_philosophy: 'Philosophy',
        nav_journey: 'Journey',
        nav_login: 'Sign In',
        nav_signup: 'Sign Up',
        nav_logout: 'Logout',
        nav_back: '← Back',
        nav_back_home: '← Back to Home',

        // Hero Section
        hero_subtitle: 'A digital legacy that lives across generations. Preserve your essence, share your wisdom, leave more than just memories.',
        hero_cta: 'Start Now',

        // Features Section
        features_title: 'Preserve the Essence',
        features_subtitle: 'Your legacy, shaped in three steps.',
        feature1_title: 'Sign Up',
        feature1_desc: 'Set up your account in moments. Your data is stored with end-to-end encryption — accessible to you alone.',
        feature2_title: 'Tell Your Story',
        feature2_desc: 'Let our Biographer guide you through the chapters of your life — from everyday moments and cherished memories to your deepest values and the wisdom you carry.',
        feature3_title: 'Share Your Oblivio',
        feature3_desc: 'Offer those closest to you something that endures — a living legacy that preserves your voice, your values, and your love far beyond a lifetime.',

        // Philosophy Section
        philosophy_title: 'More Than Memory',
        philosophy_p1: 'Oblivio is not just a repository for facts and data. It is a living legacy, a place where your personality, your values, and your love remain forever present.',
        philosophy_p2: 'We believe that every person possesses unique wisdom worth preserving. For children, grandchildren, and all those who come after us.',
        philosophy_p3: 'Time passes, but the essential remains.',

        // Journey Page
        journey_welcome: 'Welcome to Oblivio',
        journey_subtitle: 'What would you like to do today?',
        journey_card1_label: 'For You',
        journey_card1_title: 'Tell Your Story',
        journey_card1_desc: 'Share your memories, experiences, and life wisdom. Our Biographer will gently guide you through capturing your personal story as a legacy for the people who matter most to you.',
        journey_card1_cta: 'Start Conversation',
        journey_card2_label: 'For Loved Ones',
        journey_card2_title: 'Experience a Legacy',
        journey_card2_desc: 'Enter a dialogue with the legacy of someone special. Hear their stories, discover their wisdom, and feel their presence, whenever you need it.',
        journey_card2_cta: 'Start Conversation',
        journey_coming_soon: 'Coming Soon',

        // Login Page
        login_title: 'Welcome Back',
        login_subtitle: 'Sign in to continue your journey',
        login_email: 'Email',
        login_password: 'Password',
        login_button: 'Sign In',
        login_signing_in: 'Signing In...',
        login_no_account: "Don't have an account?",
        login_create_here: 'Create one here',
        login_success: 'Login successful! Redirecting...',

        // Signup Page
        signup_title: 'Create Account',
        signup_subtitle: 'Begin your legacy journey today',
        signup_name: 'Full Name',
        signup_name_placeholder: 'Your full name',
        signup_email: 'Email',
        signup_email_placeholder: 'your@email.com',
        signup_password: 'Password',
        signup_password_placeholder: 'Create a strong password',
        signup_password_req: 'At least 6 characters long',
        signup_confirm: 'Confirm Password',
        signup_confirm_placeholder: 'Confirm your password',
        signup_button: 'Create Account',
        signup_creating: 'Creating Account...',
        signup_have_account: 'Already have an account?',
        signup_signin_here: 'Sign in here',
        signup_success: 'Account created successfully! Redirecting to login...',
        signup_error_match: 'Passwords do not match',
        signup_error_length: 'Password must be at least 6 characters long',

        // Biographer Page
        bio_title: 'The Biographer',
        bio_subtitle: "Let's preserve your story together",
        bio_input_placeholder: 'Type your answer here...',
        bio_send: 'Send',
        bio_complete_title: 'Biography Complete',
        bio_complete: 'Thank you for sharing your story with me. Your legacy is now being carefully prepared — Dennis will reach out to you as soon as everything is ready for you to experience it.',

        // Biographer Questions
        bio_q1: "Hello! I'm the Biographer, and I'm here to help you preserve your legacy. What's your full name?",
        bio_q2: 'Tell me about your childhood. Where did you grow up, and what are your fondest memories?',
        bio_q3: 'What are the most important values in your life? What principles guide your decisions?',
        bio_q4: 'Who has had the biggest influence on your life? How did they shape who you are today?',
        bio_q5: 'What accomplishments are you most proud of in your life?',
        bio_q6: "What lessons have you learned that you'd like to pass on to future generations?",
        bio_q7: 'If you could give one piece of advice to your loved ones, what would it be?',
        bio_q8: 'What brings you the most joy in life?',
        bio_q9: "Is there anything else you'd like to share about your life story?",

        // Language Selection Modal
        lang_modal_title: 'Choose Your Language',
        lang_modal_subtitle: 'Select the language for your conversation with the Biographer',
        lang_modal_continue: 'Continue',

        // Footer
        footer_tagline: 'Preserve what is unforgettable.<br>A legacy for eternity.',
        footer_product: 'Product',
        footer_features: 'Features',
        footer_pricing: 'Pricing',
        footer_security: 'Security',
        footer_faq: 'FAQ',
        footer_company: 'Company',
        footer_about: 'About Oblivio',
        footer_blog: 'Blog',
        footer_careers: 'Careers',
        footer_press: 'Press',
        footer_legal: 'Legal',
        footer_privacy: 'Privacy',
        footer_terms: 'Terms of Service',
        footer_imprint: 'Imprint',
        footer_contact: 'Contact',
        footer_rights: '© 2026 Oblivio. All rights reserved.',
        footer_tech: 'Technology',

        // Nav sub-page links
        nav_tech_link: 'Technology',
        nav_about_link: 'About Oblivio',
        nav_start_link: 'Start',

        // Security page
        sec_label: 'Security',
        sec_h1: 'Your story<br>belongs to you alone.',
        sec_sub: 'What you share with Oblivio is the most personal thing you have. We treat it accordingly.',
        sec_c1_title: 'Encryption',
        sec_c1_desc: 'All connections are TLS-encrypted. Data is stored in Supabase with encryption at rest. No one can read it in plain text.',
        sec_c2_title: 'Row Level Security',
        sec_c2_desc: 'Supabase RLS ensures every database query returns only your own data, making it technically impossible to access someone else\'s records.',
        sec_c3_title: 'JWT Authentication',
        sec_c3_desc: 'Access to your account is secured by signed JSON Web Tokens. Expired or invalid tokens are automatically rejected.',
        sec_c4_title: 'Swiss Infrastructure',
        sec_c4_desc: 'The frontend is operated through a certified Swiss hosting provider. Swiss data protection law (revDSG) applies as the minimum standard for all data processing.',
        sec_c5_title: 'No Tracking, No Ads',
        sec_c5_desc: 'Oblivio uses no advertising trackers, no third-party analytics services, and sells no user data. To anyone.',
        sec_c6_title: 'Right to Deletion',
        sec_c6_desc: 'You can request deletion of your data at any time. Your account, conversations, and legacy will be completely and irreversibly removed.',
        sec_auth_title: 'Authentication &amp; Access',
        sec_auth_p1: 'Access to Oblivio is exclusively via a verified email address combined with a self-chosen password. Passwords are never stored in plain text. Supabase Auth uses <strong>bcrypt</strong>-based hashing, one of the most secure standards for password storage.',
        sec_auth_p2: 'Sessions are managed by short-lived JWT tokens. After a certain period, these are automatically renewed or invalidated, so expired sessions grant no access.',
        sec_auth_box: '<strong>Row Level Security (RLS)</strong> is enabled on all tables. This means: even if a technical error occurs in the application logic, the database at server level ensures that no user can access another user\'s data.',
        sec_dm_title: 'Data Minimisation',
        sec_dm_p1: 'Oblivio collects only what is necessary for the service: name, email address, language preference, and the content of your conversations with the Biographer. No location data, device fingerprints, behavioural patterns, or other metadata beyond technical necessity is collected.',
        sec_dm_p2: 'Conversation content is used exclusively for generating your legacy and is not subject to any other analysis, third-party AI model training, or sharing.',
        sec_ai_title: 'AI Requests',
        sec_ai_p: 'Conversation content is transmitted to the OpenAI GPT API for processing. OpenAI has contractually committed to not using API requests from business customers for training their models. Transmission is exclusively encrypted (TLS 1.3) and only for the duration of processing, with no permanent storage at OpenAI.',

        // Pricing page
        price_label: 'Pricing',
        price_h1: 'Dreams shouldn\'t<br>send invoices.',
        price_sub: 'Oblivio is and remains free for every user. Here\'s the honest story behind it.',
        price_s1_title: 'The truth about APIs',
        price_s1_p1: 'Behind every conversation with the Biographer lie real costs. Every message you write travels to OpenAI\'s data centres and returns as a thoughtful, empathetic response. Every stored memory occupies space on Supabase servers. Every call to the PROMISE AI consumes computing capacity on Railway.',
        price_s1_p2: 'These are not hypothetical costs. They are real API fees incurred with every conversation:',
        price_cost1_title: 'OpenAI (GPT API)',
        price_cost1_desc: 'Token costs arise per conversation block, depending on the depth of the conversation and the length of the system context.',
        price_cost2_title: 'Supabase',
        price_cost2_desc: 'Database queries, authentication, and storage of conversation histories and legacies.',
        price_cost3_title: 'Railway',
        price_cost3_desc: 'Ongoing operation of the PROMISE backend service, compute-intensive under concurrent users.',
        price_cost4_title: 'Web Hosting (CH)',
        price_cost4_desc: 'Hosting and delivery of the frontend via the oblivio.ch domain.',
        price_s2_title: 'Why free anyway?',
        price_s2_p1: 'Oblivio is a passion project, born not from a business plan, but from a simple conviction: <em>every person deserves to be heard and remembered.</em> Not only those who can afford expensive software.',
        price_s2_p2: 'The idea of documenting one\'s own life, preserving one\'s voice for future generations, passing on one\'s wisdom: that is no luxury. It is a deeply human need. Oblivio wants to be the place where this need is met, regardless of bank balance.',
        price_s2_p3: 'In the current phase as an academic research project at ZHAW, the developers bear the running costs. What matters is the experience, and it shall be complete, unrestricted, and dignified.',
        price_plan_label: 'Current Plan',
        price_plan_name: 'Oblivio Free',
        price_plan_price: 'CHF 0',
        price_plan_per: '/ month',
        price_plan_desc: 'Full access to the Biographer, all 10 conversation blocks, automatic legacy storage and digital legacy, without restrictions.',
        price_inc1: '10 conversation blocks',
        price_inc2: 'Automatic knowledge storage',
        price_inc3: 'Digital legacy',
        price_inc4: 'All 8 languages',
        price_inc5: 'Secure encryption',
        price_inc6: 'No advertising',
        price_footnote: 'Oblivio is in active development. Future features, such as voice cloning with ElevenLabs or continuing the conversation with relatives, will also be introduced in the spirit of this promise: with dignity, care, and as accessible as possible.',

        // FAQ page
        faq_label: 'FAQ',
        faq_h1: 'Frequently asked<br>questions',
        faq_sub: 'Everything you want to know about Oblivio, answered clearly and honestly.',
        faq_cat1: 'General',
        faq_q1: 'What is Oblivio?',
        faq_a1: 'Oblivio is a digital platform where you can document your life\'s work, guided by an AI Biographer. The resulting conversations, insights, and memories are stored as a digital legacy that your loved ones can experience in the future.',
        faq_q2: 'Who is Oblivio for?',
        faq_a2: 'For anyone who has a story to tell, which means everyone. Oblivio is especially aimed at people who wish to preserve their wisdom, memories, and personality for children, grandchildren, and future generations.',
        faq_q3: 'How does the Biographer work?',
        faq_a3: 'The Biographer guides you through ten thematic conversation blocks, from your daily life through memories, relationships, and values to your legacy. Each block is a deep conversation, automatically summarised and stored once enough meaningful information has been gathered.',
        faq_q4: 'What languages does Oblivio support?',
        faq_a4: 'Oblivio currently supports eight languages: German, English, French, Italian, Turkish, Korean, Japanese, and Chinese. You choose the language of the Biographer at the start of your first conversation. The Biographer then communicates consistently in that language.',
        faq_cat2: 'Conversation &amp; Biographer',
        faq_q5: 'How many conversation blocks are there?',
        faq_a5: 'There are ten blocks: Daily Life, Emotions, Memories, Relationships, Personal Growth, Dreams, Values, Legacy, Personal Messages, and Closing. Each block dedicates itself to its own area of life and is only completed once the Biographer has gathered enough profound answers.',
        faq_q6: 'Can I pause and resume the conversation?',
        faq_a6: 'Yes. Your conversation history is automatically saved in Supabase. When you log in again, you continue from where you left off, including the current conversation block.',
        faq_q7: 'What happens at the end of all 10 blocks?',
        faq_a7: 'After completing all ten blocks, your complete digital legacy is automatically saved. It contains the summarised insights from all conversations. In a future version, relatives will be able to enter into dialogue with this legacy.',
        faq_q8: 'Does the Biographer really listen, or is it standard text?',
        faq_a8: 'The Biographer is powered by a GPT language model from OpenAI. It reads every sentence you write, remembers the context of the entire conversation, and asks follow-up questions that genuinely respond to what you have said. It is not a form. It is a real conversation.',
        faq_cat3: 'Privacy &amp; Security',
        faq_q9: 'Who can read my conversations?',
        faq_a9: 'No one but you. Supabase Row Level Security ensures that every database query is technically restricted to your own data. No administrator, developer, or other user can view your conversation contents.',
        faq_q10: 'Is my data used for AI training?',
        faq_a10: 'No. OpenAI contractually commits to not using API requests from business customers for training models. Your conversation contents are processed exclusively for generating responses and not stored thereafter.',
        faq_q11: 'Can I have my data deleted?',
        faq_a11: 'Yes, at any time. Send an email to <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a> with the subject "Data Deletion", and all your data will be completely and irreversibly removed.',
        faq_cat4: 'Costs',
        faq_q12: 'Is Oblivio really free?',
        faq_a12: 'Yes. Oblivio is an academic research project at ZHAW and is fully available to all users free of charge, with no hidden fees, no freemium restrictions, and no advertising. More on the <a href="pricing.html">pricing page</a>.',
        faq_q13: 'Will Oblivio remain permanently free?',
        faq_a13: 'That is the intention. Since Oblivio was created as a bachelor\'s thesis, running costs are manageable. Should the project grow, any change to the business model will be communicated transparently.',

        // Features / Technology page
        tech_label: 'Technology',
        tech_h1: 'The Architecture<br>of the Everlasting',
        tech_sub: 'Oblivio combines cutting-edge research with thoughtful infrastructure, so every story is safely preserved, every conversation comes alive, and every legacy remains permanently accessible.',
        tech_intro: 'Behind Oblivio stand no off-the-shelf solutions, but consciously chosen technologies that together create a system balancing dignity, security, and depth.',
        tech_01_sub: 'Conversational AI Framework',
        tech_01_title: 'PROMISE',
        tech_01_p: 'PROMISE is a scientific framework from <strong>ZHAW – Zurich University of Applied Sciences</strong>, enabling state-based, multi-step AI conversations. Oblivio\'s Biographer is built entirely on PROMISE: each of the ten thematic conversation blocks is an independent state with its own system context, transition conditions, and automatic knowledge extraction. The backend service is provided via <strong>Railway</strong> and is scalably accessible at all times.',
        tech_01_tag1: 'ZHAW Research',
        tech_01_tag2: 'Stateful AI',
        tech_02_sub: 'Language Model',
        tech_02_title: 'GPT by OpenAI',
        tech_02_p: 'The Biographer\'s conversations are powered by a <strong>GPT language model from OpenAI</strong>. OpenAI\'s models were trained on vast amounts of human language and are capable of conducting context-sensitive, empathetic conversations. This allows Oblivio to hold conversations that don\'t feel mechanical, but like an attentive counterpart: patient, perceptive, and always interested in the person.',
        tech_02_tag1: 'OpenAI',
        tech_02_tag2: 'GPT',
        tech_03_sub: 'Database &amp; Authentication',
        tech_03_title: 'Supabase',
        tech_03_p: 'All user data, conversation histories, and stored legacies are stored in <strong>Supabase</strong>, an open PostgreSQL platform with Row Level Security (RLS). This means: no user can access another\'s data, not through errors, not through vulnerabilities. Authentication is via encrypted JWT tokens, and all connections are TLS-secured.',
        tech_03_tag1: 'PostgreSQL',
        tech_03_tag2: 'Row Level Security',
        tech_04_sub: 'Backend Infrastructure',
        tech_04_title: 'Railway',
        tech_04_p: 'The PROMISE backend service runs on <strong>Railway</strong>, a modern cloud platform combining automatic deployment, scaling, and monitoring. Every change to the Biographer system is live within minutes, without manual server configuration. Railway ensures Oblivio remains reliably accessible even under load.',
        tech_04_tag1: 'Auto-Deploy',
        tech_04_tag2: 'Cloud Infrastructure',
        tech_05_sub: 'Voice Synthesis · Planned',
        tech_05_title: 'ElevenLabs',
        tech_05_p: 'In a future version of Oblivio, every digital legacy shall be not only readable, but <em>hearable</em>. With <strong>ElevenLabs</strong>, the leading platform for realistic voice synthesis, it will be possible to record and clone one\'s own voice. Relatives will then be able not just to read text messages, but to hear the familiar voice of their loved ones again.',
        tech_05_tag1: 'Voice Cloning',
        tech_05_tag2: 'Roadmap 2026',
        tech_06_sub: 'Web Hosting',
        tech_06_title: 'Swiss Web Hosting',
        tech_06_p: 'Oblivio\'s frontend is operated through a renowned Swiss hosting provider. The domain <em>oblivio.ch</em> and all static resources are delivered directly from Switzerland. This means: data stays in Switzerland, is subject to Swiss data protection law (DSG), and benefits from excellent network infrastructure.',
        tech_06_tag1: 'Swiss Hosting',
        tech_06_tag2: 'DSG-compliant',
        tech_arch_title: 'How it all fits together',
        tech_arch_lead: 'From your input to the stored memory: every step is considered and secured.',
        tech_flow1_title: 'Input',
        tech_flow1_p: 'You write a message in the browser, transmitted encrypted over HTTPS.',
        tech_flow2_title: 'PROMISE processes',
        tech_flow2_p: 'The Railway backend service receives the message, determines the current state, and sends it to OpenAI GPT.',
        tech_flow3_title: 'GPT responds',
        tech_flow3_p: 'The language model generates an empathetic, context-sensitive response based on the Biographer\'s current state.',
        tech_flow4_title: 'Supabase stores',
        tech_flow4_p: 'Conversation and extracted insights are securely stored in your personal Supabase instance, accessible only to you.',

        // Contact page
        contact_label: 'Contact',
        contact_h1: 'Let\'s stay<br>in touch.',
        contact_li_title: 'Dennis Riccardo',
        contact_li_sub: 'Creator of Oblivio · Student at ZHAW',
        contact_li_cta: 'Visit profile',
        contact_em_title: 'Email',
        contact_em_addr: 'riccaden@students.zhaw.ch',
        contact_info: '<strong>Academic context:</strong> Oblivio is a bachelor\'s thesis at <strong>ZHAW</strong> – Zurich University of Applied Sciences. Questions, feedback, or collaboration proposals are warmly welcome.',

        // About page
        about_label: 'About Oblivio',
        about_h1: 'One person.<br>One idea.<br>One legacy.',
        about_sub: 'Oblivio was born from the conviction that every person deserves to be heard and remembered, far beyond their own lifetime.',
        about_badge: 'Bachelor\'s Thesis',
        about_inst: '<strong>ZHAW – Zurich University of Applied Sciences</strong> · School of Management and Law · Business Informatics · 2026',
        about_role: 'Developer · Student',
        about_bio1: 'I study Business Informatics at ZHAW in Winterthur, a program that has fascinated me from the start because it connects two worlds I love: the logical precision of technology and the strategic thinking of business.',
        about_bio2: 'Alongside that, I work as a Project Manager at one of Switzerland\'s largest health insurers. There I learn daily how complex systems are organized, how people are led, and how change is implemented sustainably. It is a world that revolves greatly around care, the wellbeing of real people.',
        about_bio3: 'Oblivio is my bachelor\'s thesis. But more than that: it is the project where everything I stand for comes together. The technical implementation with AI and modern infrastructure. The human side: conversations, memories, the need for connection across time. And the conviction that technology should serve people, not the other way around.',
        about_bio4: 'My goal with Oblivio was to build something that not only works, but feels right. A platform that handles with dignity the most intimate thing there is: a person\'s own life.',
        about_values_title: 'What drives Oblivio',
        about_v1_title: 'Dignity',
        about_v1_p: 'Every story deserves to be treated with respect, not as a data point, but as the life\'s work of a human being.',
        about_v2_title: 'Accessibility',
        about_v2_p: 'Preserving one\'s own life should not be a question of money. Oblivio is free, and deliberately so.',
        about_v3_title: 'Depth',
        about_v3_p: 'Superficial answers lead to superficial memories. The biographer keeps asking until what matters most comes to the surface.',

        // Blog page
        blog_label: 'Blog',
        blog_h1: 'How Oblivio<br>was born.',
        blog_sub: 'An honest account of decisions, detours and insights on the path from idea to platform.',
        blog_date: 'Spring 2026',
        blog_tag1: 'Bachelor\'s Thesis',
        blog_tag2: 'Development',
        blog_art_h2: 'From idea to living platform: the development story of Oblivio',
        blog_art_lead: 'What begins when you ask yourself: what remains of a person when they are gone? Oblivio began with this question, and ended with an answer that contains more technical decisions than I had initially expected.',
        blog_h3_1: 'The starting question',
        blog_p1_1: 'The idea for Oblivio was not born at a desk, but in a moment of personal stillness: what would I still want to ask a person I have lost? And conversely: what would I myself like to leave behind when I am no longer here?',
        blog_p1_2: 'These questions led me to my bachelor\'s thesis. The goal was ambitious: an AI-powered platform that enables every person to document their life in the form of a digital legacy, deep, personal and lasting.',
        blog_quote: '"Not a form. Not a questionnaire. A conversation that actually listens."',
        blog_h3_2: 'PROMISE: The core',
        blog_p2_1: 'The technological backbone of Oblivio is <strong>PROMISE</strong>, a state-based conversation framework developed at ZHAW. Instead of simple chatbot sequences, PROMISE enables real conversation states: each of the ten biographer blocks is its own state with its own system context, transition conditions and automatic knowledge extraction.',
        blog_p2_2: 'The central challenge: when does a block transition to the next? The first solution was a double condition: the user had to explicitly say "continue", AND the guard had to confirm that enough topics had been covered. That sounds reasonable, but led to a serious bug.',
        blog_technote: '<strong>Bug:</strong> <code>Transition(List.of(trigger, guard), ...)</code> — AND logic. When the user said "no" (Trigger = true) after a long conversation (Guard = true), <code>TransferUtterancesAction</code> was triggered — and since the entire conversation history was transferred to all subsequent states, ALL guards simultaneously evaluated as true. Block 1 jumped directly to "Biography Complete".<br><br><strong>Solution:</strong> <code>Transition(List.of(guard), ...)</code> — Guard alone. No trigger. The switch happens automatically once enough meaningful answers have been collected.',
        blog_h3_3: 'Ten blocks instead of one',
        blog_p3_1: 'The original version of the biographer was a single state, an endless conversation flow without structure. The problem: without thematic guidance, many areas of life went untouched. Users spoke about childhood memories, but never about their values. About their work, but never about their dreams.',
        blog_p3_2: 'The solution was switching to ten thematic blocks: Ice-Breaker (Geschmack & Vorlieben), Alltag & Lebenswelt, Kommunikationsstil, Erinnerungen & Schlüsselerlebnisse, Emotionen & Beziehungsmuster, Beziehungen & Fremdbild, Werte & Überzeugungen, Macken & Widersprüche, Vermächtnis & Zukunft and Abschluss. Each block is designed to fully explore a specific area of life, and only then automatically switches to the next.',
        blog_h3_4: 'Frontend: between function and dignity',
        blog_p4_1: 'The design of Oblivio followed a clear premise: it should not feel like an app, but like a letter. The color palette (cream, charcoal, rust red, moss green) was deliberately chosen to convey warmth and permanence. The fonts Crimson Pro and DM Serif Display bring literature into the interface.',
        blog_p4_2: 'The progress bar, which appears after Block 1 and accompanies the user from Block 1 to 10, was a small but significant UX decision: visible progress provides orientation without interrupting the conversation. Its state is saved in <code>localStorage</code> so it is preserved after a refresh.',
        blog_h3_5: 'The Block 0 questionnaire',
        blog_p5_1: 'Before the actual biographer begins, the user goes through a short questionnaire: name, age group, gender, marital status, personality traits and communication style. This information is passed to the biographer as context. It then knows who it is dealing with, and can adapt its tone, questions and reactions accordingly.',
        blog_p5_2: 'This "Block 0" is available in seven languages (German, English, French, Italian, Korean, Japanese and Chinese) and was designed to feel quick, unobtrusive and honest. The consent form beforehand clearly communicates what is stored and why.',
        blog_h3_6: 'Supabase, Railway & Swiss Hosting',
        blog_p6_1: 'The infrastructure of Oblivio was chosen according to a simple principle: each component should be the best in its category, work well together, and add no unnecessary complexity. Supabase for authentication and database. Railway for the PROMISE backend service with auto-deploy on every git push. A Swiss provider for frontend hosting.',
        blog_p6_2: 'Railway has proven particularly valuable: every change to the Java backend (new guards, new prompts, new language support) is live within minutes. This has significantly increased iteration speed.',
        blog_h3_7: 'What has already been achieved',
        blog_p7_1: 'Oblivio has grown beyond the original vision: the legacy chat is active — loved ones can use an access code to enter into dialogue with the stored legacy. ElevenLabs voice synthesis gives the Biographer an audible voice, and thanks to the Web Speech API, users can also dictate their answers via voice input.',
        blog_p7_2: 'Oblivio is done, but not finished. It is a platform that becomes richer with every conversation conducted on it.',
        blog_date_v2: '9 May 2026',
        blog_tag_v2_1: 'Update',
        blog_tag_v2_2: 'Iteration',
        blog_v2_h2: 'From four to eight languages: the major overhaul',
        blog_v2_lead: 'Over the past weeks, Oblivio has grown. Not only in the number of personas, but also in the depth of its features. Here is an overview of the most important changes.',
        blog_v2_h3_1: 'Eight languages instead of four',
        blog_v2_p1: 'Oblivio now supports eight languages: German, English, French, Italian, Turkish, Korean, Japanese and Chinese. Turkish was added as the eighth language to further expand international reach. To make this happen, all UI texts, the Biographer questionnaire and the block instructions were extended.',
        blog_v2_h3_2: 'Three conversation variants',
        blog_v2_p2_1: 'The legacy personas can now be approached in three different modes: Variant 1 includes a full personality analysis with radar chart, communication DNA and life patterns. Variant 2 lets the persona actively open the conversation. Variant 3 waits silently for the visitor\'s first message.',
        blog_v2_p2_2: 'Each variant suits a different emotional situation: deep understanding, a low barrier to entry, or full control over how the conversation begins.',
        blog_v2_h3_3: 'Automatic context compaction',
        blog_v2_p3: 'A technical improvement in the PROMISE backend: after twenty user messages, older conversation entries are automatically summarised and replaced with a compact system message. This keeps token costs constant while preserving the most important content — similar to how human memory lets details fade but retains the overall picture.',
        blog_v2_h3_4: 'Visible progress and invisible clean-up',
        blog_v2_p4_1: 'Behind the scenes, many components were refined: the repository was restructured (separate folders for documentation and SQL scripts), all Java classes received detailed comments, and outdated texts on the website were updated.',
        blog_v2_p4_2: 'The persons page was also reworked: older references to individual persona names were replaced with generic phrasing so that the platform remains consistent with future personas as well.',
        blog_v2_h3_5: '15 participants, new personas, new voices',
        blog_v2_p5: 'A total of 15 people took part in the study and shared their life stories with the Biographer. Each of these stories became its own persona — with its own profile picture, its own voice via ElevenLabs, and a three-part system prompt for the three conversation variants. The platform has gained in diversity through this — different languages, age groups and life paths meet here.',
        blog_v2_p_final: 'Oblivio keeps evolving — not in one big leap, but through many small improvements, each of which makes the conversation a little more real and a little more human.',

        // Terms page
        terms_label: 'Legal',
        terms_h1: 'Terms of Use',
        terms_updated: 'As of: January 2026',
        terms_highlight: 'Oblivio is an academic research project within a bachelor\'s thesis at ZHAW – Zurich University of Applied Sciences. By using this platform you agree to these terms of use.',
        terms_s1_title: '1. Nature of the service',
        terms_s1_p1: 'Oblivio is a non-commercial, academic platform developed as part of a bachelor\'s thesis at ZHAW. The service is available to the public free of charge and without profit motive.',
        terms_s1_p2: 'The platform is under active development. Features, availability and content may change at any time. There is no guarantee of permanent operation.',
        terms_s2_title: '2. Permitted use',
        terms_s2_p1: 'You may use Oblivio to:',
        terms_s2_list1: '<li>Document your personal digital legacy</li><li>Conduct conversations with the AI biographer</li><li>Retrieve and manage your stored content</li>',
        terms_s2_p2: 'Not permitted is use for:',
        terms_s2_list2: '<li>Automated mass requests or API abuse</li><li>Entering illegal, offensive or harmful content</li><li>Attempts to access others\' data or circumvent security measures</li><li>Commercial purposes of any kind without written permission</li>',
        terms_s3_title: '3. Your content',
        terms_s3_p1: 'All content you enter into Oblivio (conversations, answers, profile information) remains intellectual property. You grant Oblivio the right to process and store this content for the technical operation of the service.',
        terms_s3_p2: 'For academic research, conversation patterns and usage behaviour may be evaluated in <strong>fully anonymized form</strong>. Inferences about individual persons are neither intended nor possible.',
        terms_s4_title: '4. Disclaimer',
        terms_s4_p1: 'Oblivio is provided "as is". No guarantee is given for uninterrupted availability, freedom from errors, or permanent storage of data. As part of an academic project, the service may be discontinued, changed or restricted at any time.',
        terms_s4_p2: 'The AI-generated responses of the biographer serve exclusively for personal reflection and documentation. They do not constitute psychological, medical or legal advice.',
        terms_s5_title: '5. Intellectual property',
        terms_s5_p1: 'Design, code, texts and all other content of the Oblivio platform (with the exception of user content) are protected by copyright and are the property of Dennis Riccardo. Use or reproduction, even in part, without written permission is not permitted.',
        terms_s6_title: '6. Third-party providers',
        terms_s6_p1: 'Oblivio uses external services (including OpenAI, Supabase, Railway and a Swiss hosting provider) for whose privacy and terms of use the respective providers are responsible. By using Oblivio you implicitly agree to the use of these services insofar as they are necessary for operation.',
        terms_s7_title: '7. Changes',
        terms_s7_p1: 'These terms of use may be adjusted at any time. Significant changes will be indicated on the platform. Continued use after a change constitutes acceptance.',
        terms_s8_title: '8. Contact',
        terms_s8_p1: 'For questions about these terms of use: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',

        // Privacy page
        priv_label: 'Legal',
        priv_h1: 'Privacy Policy',
        priv_updated: 'As of: January 2026',
        priv_s1_title: '1. Responsible party',
        priv_s1_p1: 'Responsible for data processing on this platform is:',
        priv_s1_p2: '<strong>Dennis Riccardo</strong><br>Student, ZHAW – Zurich University of Applied Sciences<br>Email: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s1_p3: 'Oblivio is an academic research project within a bachelor\'s thesis. It is not a commercial company.',
        priv_s2_title: '2. What data we collect',
        priv_s2_p1: 'Oblivio collects exclusively the data necessary for the operation of the service:',
        priv_s2_list: '<li><strong>Registration data:</strong> Email address, full name, password (stored as bcrypt hash)</li><li><strong>Profile data:</strong> Nickname, age group, gender, marital status, personality traits, communication style – voluntarily provided in the questionnaire before the conversation</li><li><strong>Conversation content:</strong> All messages you write in conversation with the biographer</li><li><strong>Language preference:</strong> Your chosen language (DE, EN, IT, KO), stored in browser localStorage</li>',
        priv_s2_p2: '<strong>No</strong> location data, device fingerprints, IP addresses (for person identification), cookies for advertising purposes or behavioral data are collected.',
        priv_s3_title: '3. Purpose of data processing',
        priv_s3_p1: 'The collected data is used exclusively for the following purposes:',
        priv_s3_list: '<li>Operation of the platform and provision of the biographer conversation</li><li>Personalization of the AI biographer based on your profile information</li><li>Storage of your digital legacy for later retrieval</li><li>Authentication and securing of your account</li><li>Academic research and evaluation within the bachelor\'s thesis (anonymized)</li>',
        priv_s4_title: '4. Disclosure to third parties',
        priv_s4_p1: 'Your data is <strong>not</strong> sold, rented or passed on for advertising purposes. The following third-party providers are used for the operation of the platform:',
        priv_s4_list: '<li><strong>Supabase</strong> (database and authentication) – data is processed in accordance with Supabase privacy policies</li><li><strong>OpenAI</strong> (GPT API) – conversation messages are transmitted for processing; OpenAI does not use these for model training in accordance with the contract</li><li><strong>Railway</strong> (backend infrastructure) – processing of API requests without permanent data storage</li><li><strong>Swiss hosting provider</strong> (web hosting, Switzerland) – delivery of static files</li>',
        priv_s5_title: '5. Data security',
        priv_s5_p1: 'All transmissions between browser and server are TLS encrypted. Passwords are stored as bcrypt hash. Supabase Row Level Security (RLS) ensures that no user can access another\'s data. Database access is exclusively via signed JWT tokens.',
        priv_s6_title: '6. Your rights',
        priv_s6_p1: 'You have the right to:',
        priv_s6_list: '<li><strong>Information:</strong> Request what data is stored about you</li><li><strong>Rectification:</strong> Correction of incorrect data</li><li><strong>Deletion:</strong> Complete and irreversible deletion of all your data</li><li><strong>Data portability:</strong> Provision of your data in a machine-readable format</li><li><strong>Objection:</strong> Objection to certain processing purposes</li>',
        priv_s6_p2: 'To exercise these rights contact: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s7_title: '7. Retention period',
        priv_s7_p1: 'Your data will be stored as long as your account is active. After a deletion request, all data will be completely removed within 7 business days. After the conclusion of the academic project, all personal data will be deleted; anonymized evaluation results may remain in the bachelor\'s thesis.',
        priv_s8_title: '8. Applicable law',
        priv_s8_p1: 'This privacy policy is governed by Swiss data protection law (revDSG). Since Oblivio may also attract users from the EU, the principles of the GDPR are observed as far as possible.',

        // Beta Page
        hero_beta_cta: 'Become a Beta Tester',
        beta_cta_title: 'Shape the Future of Tomorrow.',
        beta_cta_desc: 'Oblivio is in its testing phase. Secure your spot now and help us build a platform that makes stories immortal.',
        beta_label: 'Become a Tester',
        beta_title: 'Be Part of<br>the Story.',
        beta_subtitle: 'Oblivio is in its testing phase. Be among the first to preserve your legacy and help shape the future of the platform.',
        beta_benefit1_title: 'Early Access',
        beta_benefit1_desc: 'Try Oblivio before it goes public and be the first to experience how AI preserves your legacy.',
        beta_benefit2_title: 'Shape the Future',
        beta_benefit2_desc: 'Your feedback shapes the future of the platform. Every response helps us make Oblivio better.',
        beta_benefit3_title: 'Free of Charge',
        beta_benefit3_desc: 'Full access at no cost. We believe legacy preservation should be accessible to everyone.',
        beta_form_title: 'Sign up and join us.',
        beta_form_desc: 'Register and we\'ll contact you as soon as your access is ready. No spam, promised.',
        beta_name_label: 'Name',
        beta_email_label: 'Email',
        beta_name_placeholder: 'Your name',
        beta_email_placeholder: 'your@email.com',
        beta_submit: 'Sign Up Now',
        beta_submitting: 'Sending...',
        beta_success: 'Thank you! We\'ll be in touch.',
        beta_error: 'An error occurred. Please try again.',
        beta_duplicate: 'This email is already registered.',
        beta_privacy_note: 'By signing up you agree to our <a href="terms.html">Terms of Service</a> and <a href="privacy.html">Privacy Policy</a>.',

        // Page titles
        page_title_index: 'Oblivio – Beyond Memory',
        page_title_about: 'About Oblivio – Oblivio',
        page_title_features: 'Technology – Oblivio',
        page_title_blog: 'Blog – Oblivio',
        page_title_faq: 'FAQ – Oblivio',
        page_title_pricing: 'Pricing – Oblivio',
        page_title_security: 'Security – Oblivio',
        page_title_contact: 'Contact – Oblivio',
        page_title_journey: 'Your Journey – Oblivio',
        page_title_biographer: 'Biographer – Oblivio',
        page_title_login: 'Sign In – Oblivio',
        page_title_signup: 'Sign Up – Oblivio',
        page_title_privacy: 'Privacy Policy – Oblivio',
        page_title_terms: 'Terms of Service – Oblivio',
        page_title_404: 'Page Not Found – Oblivio',
        page_title_legacy: 'Legacy – Oblivio',

        // Legacy Chat
        legacy_title: 'Experience a Legacy',
        legacy_subtitle: 'Enter the access code to speak with a legacy.',
        legacy_code_placeholder: 'Access code',
        legacy_connect_btn: 'Connect',
        legacy_invalid_code: 'Invalid code. Please try again.',
        legacy_no_data: 'No legacy data found.',
        legacy_error: 'An error occurred. Please try again.',
        legacy_loading: 'Connecting...',
        legacy_chat_title: 'Conversation with',
        legacy_chat_subtitle: 'A conversation with the legacy of {name}',
        legacy_input_placeholder: 'Write a message...',
        legacy_ended: 'The conversation has ended.',
        legacy_send_error: 'Message could not be sent. Please try again.',
        // Legacy Visitor Info
        legacy_visitor_title: 'Before we begin',
        legacy_visitor_subtitle: 'So the conversation feels more personal.',
        legacy_visitor_name_label: 'What should {name} call you?',
        legacy_visitor_name_placeholder: 'Your name',
        legacy_visitor_relation_label: 'What is your relationship to {name}?',
        legacy_visitor_relation_placeholder: 'Please choose...',
        legacy_visitor_rel_spouse: 'Spouse',
        legacy_visitor_rel_child: 'Child',
        legacy_visitor_rel_parent: 'Parent',
        legacy_visitor_rel_sibling: 'Sibling',
        legacy_visitor_rel_grandchild: 'Grandchild',
        legacy_visitor_rel_friend: 'Friend',
        legacy_visitor_rel_relative: 'Relative',
        legacy_visitor_rel_other: 'Other',
        legacy_visitor_gender_label: 'Gender',
        legacy_visitor_gender_placeholder: 'Please choose...',
        legacy_visitor_gender_male: 'Male',
        legacy_visitor_gender_female: 'Female',
        legacy_visitor_gender_other: 'Other',
        legacy_visitor_start: 'Start conversation',
        legacy_visitor_required: 'Please fill in all fields.',
        // Legacy Conversation Mode
        legacy_mode_active: 'Variant 2',
        legacy_mode_passive: 'Variant 3',
        legacy_mode_analysis: 'Variant 1',
        legacy_passive_hint: 'Write a message to {name} to start the conversation…',
        legacy_mode_switch_confirm: 'Switch mode? The current conversation will be restarted.',

        // Biographer Completion — Access Code
        bio_complete_code_desc: 'Share this code with loved ones:',
        bio_complete_code_copy: 'Copy code',
        bio_complete_code_copied: 'Copied!',
        bio_complete_code_email: 'Share via email',
        bio_complete_email_subject: 'Your Oblivio access code for',
        bio_complete_email_greeting: 'Hello',
        bio_complete_email_line1: 'The biography has been successfully completed!',
        bio_complete_email_line2: 'Access code:',
        bio_complete_email_line3: 'Visit this page to speak with the legacy:',

        // Journey — Access Code
        journey_your_code: 'Your Access Code',
        journey_code_desc: 'Share this code with your loved ones so they can speak with your legacy.',
        journey_email_code: 'Share via email'
};
