// Oblivio translations — ko
window._oblivioLang = {
// Navigation
        nav_home: '홈',
        nav_features: '특징',
        nav_philosophy: '철학',
        nav_journey: '여정',
        nav_login: '로그인',
        nav_signup: '회원가입',
        nav_logout: '로그아웃',
        nav_back: '← 뒤로',
        nav_back_home: '← 홈으로',

        // Hero Section
        hero_subtitle: '세대를 넘어 살아있는 디지털 유산. 당신의 본질을 보존하고, 지혜를 공유하며, 추억 이상을 남기세요.',
        hero_cta: '시작하기',

        // Features Section
        features_title: '본질을 보존하다',
        features_subtitle: '세 단계로 완성하는 영원한 유산.',
        feature1_title: '회원가입',
        feature1_desc: '몇 순간 만에 계정을 설정하세요. 모든 데이터는 암호화되어 오직 당신만이 접근할 수 있습니다.',
        feature2_title: '이야기를 들려주세요',
        feature2_desc: '전기 작가와 함께 삶의 장들을 걸어가세요. 소중한 기억과 일상의 순간부터, 꿈과 당신이 진정으로 소중히 여기는 가치까지.',
        feature3_title: 'Oblivio를 공유하세요',
        feature3_desc: '가장 소중한 이들에게 오래도록 남을 무언가를 전하세요. 당신의 목소리, 가치관, 그리고 사랑을 세대를 넘어 간직하는 살아있는 유산입니다.',

        // Philosophy Section
        philosophy_title: '기억 이상',
        philosophy_p1: 'Oblivio는 단순한 사실과 데이터의 저장소가 아닙니다. 당신의 성격, 가치관, 사랑이 영원히 존재하는 살아있는 유산입니다.',
        philosophy_p2: '우리는 모든 사람이 보존할 가치가 있는 독특한 지혜를 가지고 있다고 믿습니다. 자녀, 손주, 그리고 우리 다음에 올 모든 사람들을 위해.',
        philosophy_p3: '시간은 흐르지만, 본질은 남습니다.',

        // Journey Page
        journey_welcome: 'Oblivio에 오신 것을 환영합니다',
        journey_subtitle: '오늘 무엇을 하시겠습니까?',
        journey_card1_label: '당신을 위해',
        journey_card1_title: '당신의 이야기를 들려주세요',
        journey_card1_desc: '당신의 추억, 경험, 삶의 지혜를 나눠주세요. 우리의 전기 작가가 당신의 개인적인 이야기를 소중히 기록하도록 함께합니다, 소중한 사람들을 위한 유산으로.',
        journey_card1_cta: '대화 시작하기',
        journey_card2_label: '사랑하는 이들을 위해',
        journey_card2_title: '유산을 경험하기',
        journey_card2_desc: '특별한 사람의 유산과 대화하세요. 그들의 이야기를 듣고, 지혜를 발견하고, 그들의 따뜻함을 느끼세요, 필요할 때 언제든지.',
        journey_card2_cta: '대화 시작',
        journey_coming_soon: '곧 출시',

        // Login Page
        login_title: '다시 오신 것을 환영합니다',
        login_subtitle: '로그인하여 여정을 계속하세요',
        login_email: '이메일',
        login_password: '비밀번호',
        login_button: '로그인',
        login_signing_in: '로그인 중...',
        login_no_account: '계정이 없으신가요?',
        login_create_here: '여기서 만들기',
        login_success: '로그인 성공! 리디렉션 중...',

        // Signup Page
        signup_title: '계정 만들기',
        signup_subtitle: '오늘 유산 여정을 시작하세요',
        signup_name: '전체 이름',
        signup_name_placeholder: '전체 이름',
        signup_email: '이메일',
        signup_email_placeholder: 'your@email.kr',
        signup_password: '비밀번호',
        signup_password_placeholder: '강력한 비밀번호 만들기',
        signup_password_req: '최소 6자 이상',
        signup_confirm: '비밀번호 확인',
        signup_confirm_placeholder: '비밀번호 확인',
        signup_button: '계정 만들기',
        signup_creating: '계정 생성 중...',
        signup_have_account: '이미 계정이 있으신가요?',
        signup_signin_here: '여기서 로그인',
        signup_success: '계정이 성공적으로 생성되었습니다! 로그인으로 리디렉션 중...',
        signup_error_match: '비밀번호가 일치하지 않습니다',
        signup_error_length: '비밀번호는 최소 6자 이상이어야 합니다',

        // Biographer Page
        bio_title: '전기 작가',
        bio_subtitle: '함께 당신의 이야기를 보존합시다',
        bio_input_placeholder: '여기에 답변을 입력하세요...',
        bio_send: '보내기',
        bio_complete_title: '전기 완성',
        bio_complete: '이야기를 공유해 주셔서 감사합니다. 유산이 정성껏 준비되고 있습니다 — 모든 준비가 완료되면 Dennis가 연락드리겠습니다.',

        // Language Selection Modal
        lang_modal_title: '언어를 선택하세요',
        lang_modal_subtitle: '전기 작가와의 대화 언어를 선택하세요',
        lang_modal_continue: '계속',

        // Footer
        footer_tagline: '잊을 수 없는 것을 보존하세요.<br>영원한 유산.',
        footer_product: '제품',
        footer_features: '특징',
        footer_pricing: '가격',
        footer_security: '보안',
        footer_faq: 'FAQ',
        footer_company: '회사',
        footer_about: 'Oblivio 소개',
        footer_blog: '블로그',
        footer_careers: '채용',
        footer_press: '언론',
        footer_legal: '법률',
        footer_privacy: '개인정보',
        footer_terms: '서비스 약관',
        footer_imprint: '저작권',
        footer_contact: '연락처',
        footer_rights: '© 2026 Oblivio. 모든 권리 보유.',
        footer_tech: '기술',
        nav_tech_link: '기술',
        nav_about_link: 'Oblivio 소개',
        nav_start_link: '시작',
        sec_label: '보안',
        sec_h1: '당신의 이야기는<br>오직 당신의 것입니다.',
        sec_sub: 'Oblivio와 공유하는 것은 당신이 가진 가장 소중한 것입니다. 우리는 그에 맞게 다룹니다.',
        sec_c1_title: '암호화',
        sec_c1_desc: '모든 연결은 TLS로 암호화됩니다. 데이터는 Supabase에 저장 시 암호화되어 누구도 평문으로 읽을 수 없습니다.',
        sec_c2_title: 'Row Level Security',
        sec_c2_desc: 'Supabase RLS는 모든 데이터베이스 쿼리가 본인의 데이터만 반환하도록 보장합니다. 다른 사람의 데이터에 접근하는 것은 기술적으로 불가능합니다.',
        sec_c3_title: 'JWT 인증',
        sec_c3_desc: '계정 접근은 서명된 JSON Web Token으로 보호됩니다. 만료되거나 유효하지 않은 토큰은 자동으로 거부됩니다.',
        sec_c4_title: '스위스 인프라',
        sec_c4_desc: '프론트엔드는 인증된 스위스 호스팅 제공업체를 통해 운영됩니다. 스위스 데이터 보호법(revDSG)이 모든 데이터 처리의 최소 기준으로 적용됩니다.',
        sec_c5_title: '추적 없음, 광고 없음',
        sec_c5_desc: 'Oblivio는 광고 추적기, 제3자 분석 서비스를 사용하지 않으며 누구에게도 사용자 데이터를 판매하지 않습니다.',
        sec_c6_title: '삭제 권리',
        sec_c6_desc: '언제든지 데이터 삭제를 요청할 수 있습니다. 계정, 대화, 유산이 완전하고 취소 불가능하게 삭제됩니다.',
        sec_auth_title: '인증 및 접근',
        sec_auth_p1: 'Oblivio에 대한 접근은 검증된 이메일 주소와 자체 선택한 비밀번호를 통해서만 가능합니다. 비밀번호는 절대 평문으로 저장되지 않습니다. Supabase Auth는 <strong>bcrypt</strong> 기반 해싱을 사용하며, 이는 비밀번호 저장의 가장 안전한 표준 중 하나입니다.',
        sec_auth_p2: '세션은 단기 JWT 토큰으로 관리됩니다. 일정 기간 후 자동으로 갱신되거나 무효화되어 만료된 세션은 접근을 허용하지 않습니다.',
        sec_auth_box: '<strong>Row Level Security (RLS)</strong>가 모든 테이블에서 활성화되어 있습니다. 즉, 애플리케이션 로직에서 기술적 오류가 발생하더라도, 데이터베이스 서버 수준에서 사용자가 다른 사람의 데이터에 접근하지 못하도록 보장합니다.',
        sec_dm_title: '데이터 최소화',
        sec_dm_p1: 'Oblivio는 서비스에 필요한 것만 수집합니다: 이름, 이메일 주소, 언어 기본 설정, 그리고 전기 작가와의 대화 내용. 위치 데이터, 기기 지문, 행동 패턴 또는 기술적 필요 이상의 메타데이터는 수집되지 않습니다.',
        sec_dm_p2: '대화 내용은 유산 생성에만 사용되며 다른 분석, 제3자 AI 모델 학습 또는 공유의 대상이 되지 않습니다.',
        sec_ai_title: 'AI 요청',
        sec_ai_p: '대화 내용은 처리를 위해 OpenAI GPT API로 전송됩니다. OpenAI는 비즈니스 고객의 API 요청을 모델 학습에 사용하지 않겠다고 계약상 약속했습니다. 전송은 암호화(TLS 1.3)되어 처리 기간 동안만 이루어지며 OpenAI에는 영구적으로 저장되지 않습니다.',
        price_label: '가격',
        price_h1: '꿈은 청구서를<br>보내지 않아야 합니다.',
        price_sub: 'Oblivio는 모든 사용자에게 무료이며 앞으로도 그럴 것입니다. 그 솔직한 이야기가 여기 있습니다.',
        price_s1_title: 'API에 대한 진실',
        price_s1_p1: '전기 작가와의 모든 대화 뒤에는 실제 비용이 있습니다. 당신이 쓰는 모든 메시지는 OpenAI의 데이터 센터로 이동하여 사려 깊고 공감적인 답변으로 돌아옵니다. 저장된 모든 기억은 Supabase 서버의 공간을 차지합니다.',
        price_s1_p2: '이것은 가상의 비용이 아닙니다. 모든 대화에서 발생하는 실제 API 요금입니다:',
        price_cost1_title: 'OpenAI (GPT API)',
        price_cost1_desc: '대화 블록당 토큰 비용이 발생합니다, 대화의 깊이와 시스템 컨텍스트 길이에 따라 다릅니다.',
        price_cost2_title: 'Supabase',
        price_cost2_desc: '데이터베이스 쿼리, 인증, 대화 기록 및 유산 저장.',
        price_cost3_title: 'Railway',
        price_cost3_desc: 'PROMISE 백엔드 서비스의 지속적인 운영, 동시 사용자 시 컴퓨팅 집약적.',
        price_cost4_title: '웹 호스팅 (CH)',
        price_cost4_desc: 'oblivio.ch 도메인을 통한 프론트엔드 호스팅 및 제공.',
        price_s2_title: '그런데 왜 무료인가요?',
        price_s2_p1: 'Oblivio는 사업 계획에서 나온 것이 아니라 단순한 확신에서 탄생한 열정 프로젝트입니다: <em>모든 사람은 들려지고 기억될 자격이 있습니다.</em> 비싼 소프트웨어를 감당할 수 있는 사람만이 아니라.',
        price_s2_p2: '자신의 삶을 기록하고, 미래 세대를 위해 자신의 목소리를 보존하고, 지혜를 전달한다는 아이디어: 그것은 사치가 아닙니다. 그것은 깊이 인간적인 필요입니다. Oblivio는 잔고에 관계없이 이 필요가 충족되는 곳이 되고자 합니다.',
        price_s2_p3: 'ZHAW의 학술 연구 프로젝트로서의 현재 단계에서, 개발자들이 운영 비용을 부담합니다. 중요한 것은 경험입니다. 그리고 그것은 완전하고, 제한 없으며, 품위 있어야 합니다.',
        price_plan_label: '현재 플랜',
        price_plan_name: 'Oblivio 무료',
        price_plan_price: 'CHF 0',
        price_plan_per: '/ 월',
        price_plan_desc: '전기 작가, 모든 10개 대화 블록, 자동 유산 저장 및 디지털 레거시에 완전히 접근, 제한 없이.',
        price_inc1: '10개 대화 블록',
        price_inc2: '자동 지식 저장',
        price_inc3: '디지털 레거시',
        price_inc4: '8개 언어 모두',
        price_inc5: '보안 암호화',
        price_inc6: '광고 없음',
        price_footnote: 'Oblivio는 활발히 개발 중입니다. ElevenLabs를 이용한 음성 복제나 가족이 대화를 이어가는 것과 같은 미래 기능들도 이 약속의 정신에 따라 도입될 것입니다: 품위, 신중함, 가능한 한 접근 가능하게.',
        faq_label: 'FAQ',
        faq_h1: '자주 묻는<br>질문',
        faq_sub: 'Oblivio에 대해 알고 싶은 모든 것, 명확하고 솔직하게 답변됩니다.',
        faq_cat1: '일반',
        faq_q1: 'Oblivio는 무엇인가요?',
        faq_a1: 'Oblivio는 AI 전기 작가의 안내를 받아 자신의 삶의 작품을 기록할 수 있는 디지털 플랫폼입니다. 생성된 대화, 통찰 및 기억은 디지털 유산으로 저장되어 사랑하는 사람들이 미래에 경험할 수 있습니다.',
        faq_q2: 'Oblivio는 누구를 위한 것인가요?',
        faq_a2: '이야기를 들려줄 사람이라면 누구나, 즉 모든 사람을 위한 것입니다. Oblivio는 특히 자녀, 손주, 미래 세대를 위해 자신의 지혜, 기억, 성격을 보존하고자 하는 사람들을 대상으로 합니다.',
        faq_q3: '전기 작가는 어떻게 작동하나요?',
        faq_a3: '전기 작가는 열 가지 주제별 대화 블록을 통해 안내합니다. 일상에서 기억, 관계, 가치를 거쳐 유산까지. 각 블록은 깊은 대화로, 충분한 의미 있는 정보가 수집되면 자동으로 요약되고 저장됩니다.',
        faq_q4: 'Oblivio는 어떤 언어를 지원하나요?',
        faq_a4: 'Oblivio는 현재 8개 언어를 지원합니다: 독일어, 영어, 프랑스어, 이탈리아어, 터키어, 한국어, 일본어, 중국어. 첫 대화 시작 시 전기 작가의 언어를 선택할 수 있습니다. 전기 작가는 그 후 일관되게 해당 언어로 소통합니다.',
        faq_cat2: '대화 &amp; 전기 작가',
        faq_q5: '대화 블록이 몇 개나 있나요?',
        faq_a5: '열 개의 블록이 있습니다: 일상, 감정, 기억, 관계, 개인 성장, 꿈, 가치, 유산, 개인 메시지, 마무리. 각 블록은 자신만의 삶의 영역에 전념하며 전기 작가가 충분한 심층적인 답변을 수집했을 때만 완료됩니다.',
        faq_q6: '대화를 중단하고 나중에 재개할 수 있나요?',
        faq_a6: '네. 대화 기록은 Supabase에 자동으로 저장됩니다. 다시 로그인하면 현재 대화 블록을 포함하여 중단한 곳에서 계속합니다.',
        faq_q7: '10개 블록 모두 끝나면 어떻게 되나요?',
        faq_a7: '열 개 블록을 모두 완료하면 완전한 디지털 유산이 자동으로 저장됩니다. 모든 대화의 요약된 통찰이 포함됩니다. 미래 버전에서는 가족이 이 유산과 대화를 나눌 수 있게 됩니다.',
        faq_q8: '전기 작가가 정말 귀 기울여 듣나요, 아니면 표준 텍스트인가요?',
        faq_a8: '전기 작가는 OpenAI의 GPT 언어 모델로 구동됩니다. 당신이 쓴 모든 문장을 읽고, 전체 대화의 맥락을 기억하며, 당신이 말한 것에 진정으로 반응하는 후속 질문을 합니다. 양식이 아닙니다. 진짜 대화입니다.',
        faq_cat3: '개인정보 &amp; 보안',
        faq_q9: '누가 내 대화를 읽을 수 있나요?',
        faq_a9: '당신 외에는 아무도 없습니다. Supabase Row Level Security는 모든 데이터베이스 쿼리가 기술적으로 자신의 데이터로 제한되도록 보장합니다. 어떤 관리자, 개발자 또는 다른 사용자도 대화 내용을 볼 수 없습니다.',
        faq_q10: '내 데이터가 AI 학습에 사용되나요?',
        faq_a10: '아니요. OpenAI는 비즈니스 고객의 API 요청을 모델 학습에 사용하지 않겠다고 계약상 약속합니다. 대화 내용은 응답 생성에만 처리되며 그 후에는 저장되지 않습니다.',
        faq_q11: '데이터를 삭제할 수 있나요?',
        faq_a11: '네, 언제든지. 제목 "데이터 삭제"로 <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>에 이메일을 보내면, 모든 데이터가 완전하고 취소 불가능하게 제거됩니다.',
        faq_cat4: '비용',
        faq_q12: 'Oblivio가 정말 무료인가요?',
        faq_a12: '네. Oblivio는 ZHAW의 학술 연구 프로젝트이며 모든 사용자에게 완전히 무료로 제공됩니다, 숨겨진 요금 없음, 프리미엄 제한 없음, 광고 없음. <a href="pricing.html">가격 페이지</a>에서 더 알아보세요.',
        faq_q13: 'Oblivio는 영구적으로 무료로 유지될까요?',
        faq_a13: '그것이 의도입니다. Oblivio가 학사 논문으로 만들어졌기 때문에 운영 비용은 관리 가능합니다. 프로젝트가 성장하면 비즈니스 모델의 변경은 투명하게 공지될 것입니다.',
        tech_label: '기술',
        tech_h1: '영원의<br>건축',
        tech_sub: 'Oblivio는 최첨단 연구와 사려 깊은 인프라를 결합합니다. 모든 이야기가 안전하게 보존되고, 모든 대화가 생동감 있으며, 모든 유산이 영구적으로 접근 가능하도록.',
        tech_intro: 'Oblivio 뒤에는 기성 솔루션이 아니라 함께 존엄성, 보안, 깊이를 균형 있게 맞추는 시스템을 만드는 의식적으로 선택된 기술들이 있습니다.',
        tech_01_sub: '대화형 AI 프레임워크',
        tech_01_title: 'PROMISE',
        tech_01_p: 'PROMISE는 <strong>ZHAW – 취리히 응용과학대학교</strong>의 과학적 프레임워크로, 상태 기반 다단계 AI 대화를 가능하게 합니다. Oblivio의 전기 작가는 전적으로 PROMISE를 기반으로 합니다: 열 개의 주제별 대화 블록 각각은 고유한 시스템 컨텍스트, 전환 조건, 자동 지식 추출을 갖춘 독립적인 상태입니다. 백엔드 서비스는 <strong>Railway</strong>를 통해 제공됩니다.',
        tech_01_tag1: 'ZHAW Research',
        tech_01_tag2: 'Stateful AI',
        tech_02_sub: '언어 모델',
        tech_02_title: 'OpenAI GPT',
        tech_02_p: '전기 작가의 대화는 <strong>OpenAI의 GPT 언어 모델</strong>로 구동됩니다. OpenAI의 모델은 방대한 양의 인간 언어로 훈련되어 맥락에 민감하고 공감적인 대화를 나눌 수 있습니다. 이를 통해 Oblivio는 기계적으로 느껴지지 않고 주의 깊은 상대방처럼 (인내심 있고, 예리하며, 항상 사람에게 관심을 갖는) 대화를 나눌 수 있습니다.',
        tech_02_tag1: 'OpenAI',
        tech_02_tag2: 'GPT',
        tech_03_sub: '데이터베이스 &amp; 인증',
        tech_03_title: 'Supabase',
        tech_03_p: '모든 사용자 데이터, 대화 기록, 저장된 유산은 Row Level Security(RLS)가 있는 오픈 PostgreSQL 플랫폼인 <strong>Supabase</strong>에 저장됩니다. 이는 어떤 사용자도 다른 사람의 데이터에 접근할 수 없음을 의미합니다, 오류나 취약점을 통해서도. 인증은 암호화된 JWT 토큰을 통해 이루어집니다.',
        tech_03_tag1: 'PostgreSQL',
        tech_03_tag2: 'Row Level Security',
        tech_04_sub: '백엔드 인프라',
        tech_04_title: 'Railway',
        tech_04_p: 'PROMISE 백엔드 서비스는 자동 배포, 스케일링, 모니터링을 결합한 현대적인 클라우드 플랫폼인 <strong>Railway</strong>에서 실행됩니다. 전기 작가 시스템의 모든 변경은 수동 서버 구성 없이 몇 분 내에 라이브됩니다.',
        tech_04_tag1: 'Auto-Deploy',
        tech_04_tag2: 'Cloud Infrastructure',
        tech_05_sub: '음성 합성 · 예정',
        tech_05_title: 'ElevenLabs',
        tech_05_p: 'Oblivio의 미래 버전에서는 모든 디지털 유산이 읽을 수 있을 뿐만 아니라 <em>들을 수 있도록</em> 할 것입니다. 현실적인 음성 합성의 선도적 플랫폼인 <strong>ElevenLabs</strong>를 통해 자신의 목소리를 녹음하고 복제할 수 있게 됩니다. 가족은 문자 메시지를 읽는 것뿐만 아니라 사랑하는 사람의 익숙한 목소리를 다시 들을 수 있게 됩니다.',
        tech_05_tag1: 'Voice Cloning',
        tech_05_tag2: 'Roadmap 2026',
        tech_06_sub: '웹 호스팅',
        tech_06_title: '스위스 웹 호스팅',
        tech_06_p: 'Oblivio의 프론트엔드는 유명한 스위스 호스팅 제공업체를 통해 운영됩니다. 도메인 <em>oblivio.ch</em>와 모든 정적 리소스는 스위스에서 직접 제공됩니다. 이는 데이터가 스위스에 남아 스위스 데이터 보호법(DSG)을 따르고 우수한 네트워크 인프라의 혜택을 받음을 의미합니다.',
        tech_06_tag1: '스위스 호스팅',
        tech_06_tag2: 'DSG 준수',
        tech_arch_title: '모든 것이 어떻게 맞춰지는가',
        tech_arch_lead: '입력에서 저장된 기억까지: 모든 단계가 고려되고 보안이 유지됩니다.',
        tech_flow1_title: '입력',
        tech_flow1_p: '브라우저에서 메시지를 작성합니다. HTTPS를 통해 암호화되어 전송됩니다.',
        tech_flow2_title: 'PROMISE 처리',
        tech_flow2_p: 'Railway 백엔드 서비스가 메시지를 받아 현재 상태를 결정하고 OpenAI GPT로 전송합니다.',
        tech_flow3_title: 'GPT 응답',
        tech_flow3_p: '언어 모델이 전기 작가의 현재 상태를 기반으로 공감적이고 맥락에 민감한 응답을 생성합니다.',
        tech_flow4_title: 'Supabase 저장',
        tech_flow4_p: '대화와 추출된 통찰이 개인 Supabase 인스턴스에 안전하게 저장됩니다, 오직 당신만 접근 가능.',
        contact_label: '연락처',
        contact_h1: '연락을<br>유지해요.',
        contact_li_title: 'Dennis Riccardo',
        contact_li_sub: 'Oblivio 창작자 · ZHAW 학생',
        contact_li_cta: '프로필 방문',
        contact_em_title: '이메일',
        contact_em_addr: 'riccaden@students.zhaw.ch',
        contact_info: '<strong>학술 맥락:</strong> Oblivio는 <strong>ZHAW</strong> – 취리히 응용과학대학교에서의 학사 논문입니다. 질문, 피드백 또는 협업 제안을 환영합니다.',

        // About page
        about_label: 'Oblivio 소개',
        about_h1: '한 사람.<br>하나의 아이디어.<br>하나의 유산.',
        about_sub: 'Oblivio는 모든 사람이 자신의 삶을 훨씬 넘어 들리고 기억될 자격이 있다는 확신에서 탄생했습니다.',
        about_badge: '학사 논문',
        about_inst: '<strong>ZHAW – 취리히 응용과학대학교</strong> · 경영학과 · 경영정보학 · 2026',
        about_role: '개발자 · 학생',
        about_bio1: '저는 빈터투어 ZHAW에서 경영정보학을 공부합니다. 제가 사랑하는 두 세계를 연결하기 때문에 처음부터 매료된 전공입니다: 기술의 논리적 정밀함과 비즈니스의 전략적 사고.',
        about_bio2: '동시에 스위스 최대 건강보험회사 중 하나에서 프로젝트 매니저로 일합니다. 그곳에서 복잡한 시스템이 어떻게 조직되고, 사람들이 어떻게 이끌리며, 변화가 어떻게 지속 가능하게 실행되는지 매일 배웁니다. 그것은 배려에 관한 세계, 실제 사람들의 복지에 관한 세계입니다.',
        about_bio3: 'Oblivio는 제 학사 논문입니다. 하지만 그 이상: 제가 지지하는 모든 것이 모이는 프로젝트입니다. AI와 현대 인프라를 통한 기술적 구현. 인간적인 측면: 대화, 기억, 시간을 넘나드는 연결의 필요. 그리고 기술이 사람을 섬겨야 한다는 확신, 그 반대가 아닌.',
        about_bio4: 'Oblivio로 제 목표는 단순히 작동하는 것뿐만 아니라 올바르게 느껴지는 것을 만드는 것이었습니다. 가장 친밀한 것을 품위 있게 다루는 플랫폼: 사람의 삶 그 자체.',
        about_values_title: 'Oblivio를 이끄는 것',
        about_v1_title: '품위',
        about_v1_p: '모든 이야기는 존중받을 자격이 있습니다, 데이터 포인트가 아니라 한 인간의 삶의 작품으로.',
        about_v2_title: '접근성',
        about_v2_p: '자신의 삶을 보존하는 것은 돈의 문제가 되어서는 안 됩니다. Oblivio는 무료이며, 의도적으로 그렇습니다.',
        about_v3_title: '깊이',
        about_v3_p: '피상적인 답변은 피상적인 기억으로 이어집니다. 전기 작가는 본질이 드러날 때까지 계속 묻습니다.',

        // Blog page
        blog_label: '블로그',
        blog_h1: 'Oblivio가<br>탄생한 이야기.',
        blog_sub: '아이디어에서 플랫폼까지의 여정에서 내린 결정, 우회로, 통찰에 대한 솔직한 이야기.',
        blog_date: '2026년 봄',
        blog_tag1: '학사 논문',
        blog_tag2: '개발',
        blog_art_h2: '아이디어에서 살아있는 플랫폼으로: Oblivio의 개발 이야기',
        blog_art_lead: '스스로에게 묻기 시작하면 무슨 일이 생길까: 사람이 떠나면 무엇이 남는가? Oblivio는 이 질문으로 시작했고, 처음에 예상했던 것보다 더 많은 기술적 결정을 담은 답으로 끝났습니다.',
        blog_h3_1: '출발점의 질문',
        blog_p1_1: 'Oblivio의 아이디어는 책상에서 태어난 것이 아니라 개인적인 고요의 순간에 태어났습니다: 내가 잃은 사람에게 무엇을 더 묻고 싶을까? 그리고 반대로: 내가 더 이상 여기 없을 때 무엇을 남기고 싶을까?',
        blog_p1_2: '이 질문들이 저를 학사 논문으로 이끌었습니다. 목표는 야심찼습니다: AI 기반 플랫폼으로 모든 사람이 디지털 유산의 형태로 자신의 삶을 기록할 수 있게, 깊고, 개인적이며, 지속적으로.',
        blog_quote: '"양식이 아닙니다. 설문지가 아닙니다. 실제로 귀 기울이는 대화입니다."',
        blog_h3_2: 'PROMISE: 핵심',
        blog_p2_1: 'Oblivio의 기술적 근간은 <strong>PROMISE</strong>로, ZHAW에서 개발된 상태 기반 대화 프레임워크입니다. 단순한 챗봇 시퀀스 대신 PROMISE는 진정한 대화 상태를 가능하게 합니다: 10개의 전기 작가 블록 각각이 자체 시스템 컨텍스트, 전환 조건, 자동 지식 추출을 가진 자체 상태입니다.',
        blog_p2_2: '핵심 과제: 블록이 언제 다음으로 전환하는가? 첫 번째 해결책은 이중 조건이었습니다: 사용자가 명시적으로 "계속"이라고 말해야 했고, 가드도 충분한 주제가 다루어졌다고 확인해야 했습니다. 합리적으로 들리지만 심각한 버그를 초래했습니다.',
        blog_technote: '<strong>버그:</strong> <code>Transition(List.of(trigger, guard), ...)</code> — AND 논리. 사용자가 긴 대화 후 "아니오"라고 말하면(트리거 = true), <code>TransferUtterancesAction</code>이 트리거되었습니다 — 전체 대화 기록이 모든 후속 상태로 전달되었기 때문에 모든 가드가 동시에 true로 평가되었습니다. 블록 1이 "Biography Complete"로 직접 점프했습니다.<br><br><strong>해결책:</strong> <code>Transition(List.of(guard), ...)</code> — 가드만. 트리거 없음. 충분한 의미 있는 답변이 수집되면 자동으로 전환됩니다.',
        blog_h3_3: '하나 대신 열 개의 블록',
        blog_p3_1: '전기 작가의 원래 버전은 단일 상태, 구조 없는 끝없는 대화 흐름이었습니다. 문제: 주제적 안내 없이 삶의 많은 영역이 다루어지지 않았습니다. 사용자들은 유년기 기억에 대해 이야기했지만 가치관에 대해서는 결코 이야기하지 않았습니다. 일에 대해서는 이야기했지만 꿈에 대해서는 결코 이야기하지 않았습니다.',
        blog_p3_2: '해결책은 10개의 주제별 블록으로 전환하는 것이었습니다: Ice-Breaker (Geschmack & Vorlieben), Alltag & Lebenswelt, Kommunikationsstil, Erinnerungen & Schlüsselerlebnisse, Emotionen & Beziehungsmuster, Beziehungen & Fremdbild, Werte & Überzeugungen, Macken & Widersprüche, Vermächtnis & Zukunft 그리고 Abschluss. 각 블록은 삶의 특정 영역을 완전히 탐구하도록 설계되었으며, 그런 다음에만 자동으로 다음으로 전환됩니다.',
        blog_h3_4: '프론트엔드: 기능과 품위 사이',
        blog_p4_1: 'Oblivio의 디자인은 명확한 전제를 따랐습니다: 앱처럼 느껴지는 것이 아니라 편지처럼 느껴져야 합니다. 색상 팔레트 (크림, 차콜, 녹슨 빨간색, 이끼 녹색)는 따뜻함과 영속성을 전달하기 위해 의도적으로 선택되었습니다. Crimson Pro와 DM Serif Display 폰트는 인터페이스에 문학을 가져옵니다.',
        blog_p4_2: '블록 1 이후에 나타나 사용자를 블록 1에서 10까지 안내하는 진행 표시줄은 작지만 중요한 UX 결정이었습니다: 눈에 보이는 진행은 대화를 방해하지 않고 방향을 제공합니다. 그 상태는 <code>localStorage</code>에 저장되어 새로 고침 후에도 보존됩니다.',
        blog_h3_5: '블록 0 설문지',
        blog_p5_1: '실제 전기 작가가 시작하기 전에 사용자는 짧은 설문지를 작성합니다: 이름, 연령대, 성별, 결혼 여부, 성격 특성 및 의사소통 스타일. 이 정보는 컨텍스트로 전기 작가에게 전달됩니다. 그러면 누구를 상대하고 있는지 알고 그에 따라 어조, 질문 및 반응을 조정할 수 있습니다.',
        blog_p5_2: '이 "블록 0"은 7개 언어(독일어, 영어, 프랑스어, 이탈리아어, 한국어, 일본어, 중국어)로 제공되며 빠르고 방해가 되지 않으며 정직하게 느껴지도록 설계되었습니다. 이전의 동의 양식은 무엇이 저장되고 왜인지 명확하게 전달합니다.',
        blog_h3_6: 'Supabase, Railway & 스위스 호스팅',
        blog_p6_1: 'Oblivio의 인프라는 간단한 원칙에 따라 선택되었습니다: 각 구성 요소는 해당 범주에서 최고이며 잘 함께 작동하고 불필요한 복잡성을 추가하지 않아야 합니다. 인증 및 데이터베이스를 위한 Supabase. 모든 git push에서 자동 배포되는 PROMISE 백엔드 서비스를 위한 Railway. 스위스 프론트엔드 호스팅을 위한 스위스 제공업체.',
        blog_p6_2: 'Railway는 특히 가치 있는 것으로 증명되었습니다: Java 백엔드의 모든 변경 (새로운 가드, 새로운 프롬프트, 새로운 언어 지원)이 몇 분 내에 실시간으로 반영됩니다. 이것은 반복 속도를 크게 높였습니다.',
        blog_h3_7: '이미 달성한 것',
        blog_p7_1: 'Oblivio는 원래의 비전을 넘어 성장했습니다: 레거시 채팅이 활성화되었습니다 — 가족들이 접근 코드를 통해 저장된 유산과 대화할 수 있습니다. ElevenLabs 음성 합성이 전기 작가에게 들을 수 있는 목소리를 부여하고, Web Speech API 덕분에 사용자는 음성 입력으로도 답변을 받아쓸 수 있습니다.',
        blog_p7_2: 'Oblivio는 완성되었습니다. 하지만 끝나지 않았습니다. 그것은 그 위에서 진행되는 모든 대화와 함께 더 풍부해지는 플랫폼입니다.',
        blog_date_v2: '2026년 5월 9일',
        blog_tag_v2_1: '업데이트',
        blog_tag_v2_2: '반복',
        blog_v2_h2: '네 개에서 여덟 개 언어로: 대대적인 개편',
        blog_v2_lead: '지난 몇 주 동안 Oblivio는 성장했습니다. 페르소나의 수뿐만 아니라 기능의 깊이에서도 말입니다. 가장 중요한 변경 사항을 살펴봅니다.',
        blog_v2_h3_1: '네 개가 아닌 여덟 개의 언어',
        blog_v2_p1: 'Oblivio는 이제 독일어, 영어, 프랑스어, 이탈리아어, 터키어, 한국어, 일본어, 중국어의 여덟 개 언어를 지원합니다. 국제적인 도달 범위를 더욱 확장하기 위해 터키어가 여덟 번째 언어로 추가되었습니다. 이를 위해 모든 UI 텍스트, 전기 작가 설문지 및 블록 지침이 보완되었습니다.',
        blog_v2_h3_2: '세 가지 대화 변형',
        blog_v2_p2_1: '레거시 페르소나는 이제 세 가지 다른 모드로 접근할 수 있습니다. 변형 1은 레이더 차트, 커뮤니케이션 DNA 및 삶의 패턴을 포함한 전체 성격 분석을 제공합니다. 변형 2는 페르소나가 능동적으로 대화를 시작하게 합니다. 변형 3은 방문자의 첫 메시지를 조용히 기다립니다.',
        blog_v2_p2_2: '각 변형은 서로 다른 감정적 상황에 적합합니다: 깊은 이해, 낮은 진입 장벽, 또는 대화가 시작되는 방식에 대한 완전한 통제.',
        blog_v2_h3_3: '자동 컨텍스트 압축',
        blog_v2_p3: 'PROMISE 백엔드의 기술적 개선: 사용자 메시지 20개 이후, 오래된 대화 기여는 자동으로 요약되어 압축된 시스템 메시지로 대체됩니다. 이렇게 하면 토큰 비용은 일정하게 유지되면서 가장 중요한 내용은 보존됩니다 — 인간의 기억이 세부 사항은 흐려지게 하면서도 전체적인 그림은 유지하는 것과 비슷합니다.',
        blog_v2_h3_4: '눈에 보이는 진전과 보이지 않는 정리 작업',
        blog_v2_p4_1: '뒤에서는 많은 구성 요소가 정교하게 다듬어졌습니다: 저장소가 재구성되었고(문서와 SQL 스크립트를 위한 별도의 폴더), 모든 Java 클래스에 상세한 주석이 추가되었으며, 웹사이트의 오래된 텍스트가 업데이트되었습니다.',
        blog_v2_p4_2: '인물 페이지도 개편되었습니다: 개별 페르소나 이름에 대한 이전 참조는 일반적인 표현으로 대체되어 플랫폼이 향후 페르소나에 대해서도 일관성을 유지할 수 있도록 했습니다.',
        blog_v2_h3_5: '15명의 참가자, 새로운 페르소나, 새로운 목소리',
        blog_v2_p5: '총 15명이 연구에 참여하여 자신의 인생 이야기를 전기 작가와 공유했습니다. 이러한 각 이야기는 자체 페르소나가 되었습니다 — 자체 프로필 사진, ElevenLabs를 통한 자체 목소리, 그리고 세 가지 대화 변형을 위한 세 부분으로 나뉜 시스템 프롬프트와 함께. 이를 통해 플랫폼은 다양성을 얻었습니다 — 다양한 언어, 연령대, 삶의 여정이 이곳에서 만납니다.',
        blog_v2_p_final: 'Oblivio는 계속 진화하고 있습니다 — 한 번의 큰 도약이 아니라, 각각 대화를 조금 더 진실되고 조금 더 인간답게 만드는 수많은 작은 개선을 통해서.',

        // Terms page
        terms_label: '법적 사항',
        terms_h1: '이용약관',
        terms_updated: '기준: 2026년 1월',
        terms_highlight: 'Oblivio는 ZHAW – 취리히 응용과학대학교에서의 학사 논문 내 학술 연구 프로젝트입니다. 이 플랫폼을 사용함으로써 귀하는 이 이용약관에 동의합니다.',
        terms_s1_title: '1. 서비스의 성격',
        terms_s1_p1: 'Oblivio는 ZHAW에서 학사 논문의 일환으로 개발된 비상업적 학술 플랫폼입니다. 이 서비스는 무료로 그리고 영리 목적 없이 일반 대중에게 제공됩니다.',
        terms_s1_p2: '플랫폼은 활발히 개발 중입니다. 기능, 가용성 및 내용은 언제든지 변경될 수 있습니다. 영구적인 운영은 보장되지 않습니다.',
        terms_s2_title: '2. 허용된 사용',
        terms_s2_p1: 'Oblivio를 다음 용도로 사용할 수 있습니다:',
        terms_s2_list1: '<li>개인 디지털 유산 문서화</li><li>AI 전기 작가와 대화 진행</li><li>저장된 콘텐츠 검색 및 관리</li>',
        terms_s2_p2: '다음 용도로의 사용은 허용되지 않습니다:',
        terms_s2_list2: '<li>자동화된 대량 요청 또는 API 남용</li><li>불법적, 모욕적 또는 유해한 콘텐츠 입력</li><li>타인의 데이터에 접근하거나 보안 조치를 우회하려는 시도</li><li>서면 허가 없는 모든 종류의 상업적 목적</li>',
        terms_s3_title: '3. 귀하의 콘텐츠',
        terms_s3_p1: 'Oblivio에 입력하는 모든 콘텐츠 (대화, 답변, 프로필 정보)는 지적 재산으로 남습니다. 귀하는 Oblivio에 서비스의 기술적 운영을 위해 이 콘텐츠를 처리하고 저장할 권리를 부여합니다.',
        terms_s3_p2: '학술 연구를 위해 대화 패턴 및 사용 행동이 <strong>완전히 익명화된 형태</strong>로 평가될 수 있습니다. 개인에 대한 추론은 의도되지 않으며 가능하지도 않습니다.',
        terms_s4_title: '4. 책임 부인',
        terms_s4_p1: 'Oblivio는 "있는 그대로" 제공됩니다. 중단 없는 가용성, 오류 없음 또는 데이터의 영구적 저장에 대한 보증은 없습니다. 학술 프로젝트의 일환으로 서비스는 언제든지 중단, 변경 또는 제한될 수 있습니다.',
        terms_s4_p2: '전기 작가의 AI가 생성한 응답은 개인적인 반성과 문서화만을 위한 것입니다. 심리적, 의학적 또는 법적 조언을 구성하지 않습니다.',
        terms_s5_title: '5. 지적 재산',
        terms_s5_p1: 'Oblivio 플랫폼의 디자인, 코드, 텍스트 및 기타 모든 콘텐츠(사용자 콘텐츠 제외)는 저작권으로 보호되며 Dennis Riccardo의 소유입니다. 서면 허가 없는 사용 또는 복제, 부분적인 경우에도, 는 허용되지 않습니다.',
        terms_s6_title: '6. 제3자 제공업체',
        terms_s6_p1: 'Oblivio는 외부 서비스(OpenAI, Supabase, Railway 및 스위스 호스팅 제공업체 포함)를 사용하며 각 제공업체가 해당 개인정보 및 이용약관에 대한 책임이 있습니다. Oblivio를 사용함으로써 귀하는 운영에 필요한 범위 내에서 이러한 서비스의 사용에 암묵적으로 동의합니다.',
        terms_s7_title: '7. 변경',
        terms_s7_p1: '이 이용약관은 언제든지 변경될 수 있습니다. 중요한 변경 사항은 플랫폼에 표시됩니다. 변경 후 지속적인 사용은 동의로 간주됩니다.',
        terms_s8_title: '8. 연락처',
        terms_s8_p1: '이 이용약관에 대한 질문: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',

        // Privacy page
        priv_label: '법적 사항',
        priv_h1: '개인정보 처리방침',
        priv_updated: '기준: 2026년 1월',
        priv_s1_title: '1. 책임자',
        priv_s1_p1: '이 플랫폼에서의 데이터 처리 책임자:',
        priv_s1_p2: '<strong>Dennis Riccardo</strong><br>학생, ZHAW – 취리히 응용과학대학교<br>이메일: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s1_p3: 'Oblivio는 학사 논문 내 학술 연구 프로젝트입니다. 상업 기업이 아닙니다.',
        priv_s2_title: '2. 수집하는 데이터',
        priv_s2_p1: 'Oblivio는 서비스 운영에 필요한 데이터만 수집합니다:',
        priv_s2_list: '<li><strong>등록 데이터:</strong> 이메일 주소, 전체 이름, 비밀번호(bcrypt 해시로 저장)</li><li><strong>프로필 데이터:</strong> 닉네임, 연령대, 성별, 결혼 여부, 성격 특성, 의사소통 스타일 – 대화 전 설문지에서 자발적으로 제공</li><li><strong>대화 내용:</strong> 전기 작가와의 대화에서 작성한 모든 메시지</li><li><strong>언어 설정:</strong> 선택한 언어(DE, EN, IT, KO), 브라우저 localStorage에 저장</li>',
        priv_s2_p2: '위치 데이터, 기기 지문, IP 주소(개인 식별용), 광고 목적 쿠키 또는 행동 데이터는 <strong>수집되지 않습니다</strong>.',
        priv_s3_title: '3. 데이터 처리 목적',
        priv_s3_p1: '수집된 데이터는 다음 목적으로만 사용됩니다:',
        priv_s3_list: '<li>플랫폼 운영 및 전기 작가 대화 제공</li><li>프로필 정보를 기반으로 한 AI 전기 작가 개인화</li><li>나중에 검색할 수 있도록 디지털 유산 저장</li><li>계정 인증 및 보안</li><li>학사 논문 내 학술 연구 및 평가(익명화)</li>',
        priv_s4_title: '4. 제3자 공개',
        priv_s4_p1: '귀하의 데이터는 광고 목적으로 판매, 임대 또는 공개되지 <strong>않습니다</strong>. 플랫폼 운영을 위해 다음 제3자 제공업체가 사용됩니다:',
        priv_s4_list: '<li><strong>Supabase</strong>(데이터베이스 및 인증) – 데이터는 Supabase 개인정보 보호정책에 따라 처리됩니다</li><li><strong>OpenAI</strong>(GPT API) – 대화 메시지가 처리를 위해 전송됩니다; OpenAI는 계약에 따라 모델 훈련에 이를 사용하지 않습니다</li><li><strong>Railway</strong>(백엔드 인프라) – 영구적인 데이터 저장 없이 API 요청 처리</li><li><strong>스위스 호스팅 제공업체</strong>(웹 호스팅, 스위스) – 정적 파일 제공</li>',
        priv_s5_title: '5. 데이터 보안',
        priv_s5_p1: '브라우저와 서버 간의 모든 전송은 TLS로 암호화됩니다. 비밀번호는 bcrypt 해시로 저장됩니다. Supabase 행 수준 보안(RLS)은 어떤 사용자도 다른 사람의 데이터에 접근할 수 없도록 보장합니다. 데이터베이스 접근은 서명된 JWT 토큰을 통해서만 이루어집니다.',
        priv_s6_title: '6. 귀하의 권리',
        priv_s6_p1: '귀하는 다음에 대한 권리가 있습니다:',
        priv_s6_list: '<li><strong>정보:</strong> 귀하에 대해 저장된 데이터 요청</li><li><strong>수정:</strong> 잘못된 데이터 수정</li><li><strong>삭제:</strong> 모든 데이터의 완전하고 돌이킬 수 없는 삭제</li><li><strong>데이터 이동성:</strong> 기계 가독 형식으로 데이터 제공</li><li><strong>이의:</strong> 특정 처리 목적에 대한 이의</li>',
        priv_s6_p2: '이러한 권리를 행사하려면 연락하세요: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s7_title: '7. 보존 기간',
        priv_s7_p1: '귀하의 데이터는 계정이 활성 상태인 동안 저장됩니다. 삭제 요청 후 모든 데이터는 7 영업일 이내에 완전히 제거됩니다. 학술 프로젝트 완료 후 모든 개인 데이터가 삭제됩니다; 익명화된 평가 결과는 학사 논문에 남을 수 있습니다.',
        priv_s8_title: '8. 적용 법률',
        priv_s8_p1: '이 개인정보 처리방침은 스위스 데이터 보호법(revDSG)에 따릅니다. Oblivio가 EU 사용자도 유치할 수 있으므로 GDPR의 원칙이 가능한 한 고려됩니다.',

        // 베타 페이지
        hero_beta_cta: '베타 테스터 되기',
        beta_cta_title: '내일의 미래를 만드세요.',
        beta_cta_desc: 'Oblivio는 테스트 단계에 있습니다. 지금 자리를 확보하고 이야기를 영원히 만드는 플랫폼을 함께 만들어 주세요.',
        beta_label: '테스터 되기',
        beta_title: '이야기의<br>일부가 되세요.',
        beta_subtitle: 'Oblivio는 테스트 단계에 있습니다. 유산을 보존하고 플랫폼의 미래를 함께 만들어갈 첫 번째 사용자가 되세요.',
        beta_benefit1_title: '조기 접근',
        beta_benefit1_desc: '공개 전에 Oblivio를 체험하고 AI가 어떻게 유산을 보존하는지 직접 경험하세요.',
        beta_benefit2_title: '함께 만들기',
        beta_benefit2_desc: '여러분의 피드백이 플랫폼의 미래를 만듭니다. 모든 의견이 Oblivio를 더 좋게 만드는 데 도움이 됩니다.',
        beta_benefit3_title: '무료',
        beta_benefit3_desc: '비용 없이 전체 접근. 유산 보존은 모든 사람에게 접근 가능해야 한다고 믿습니다.',
        beta_form_title: '지금 등록하고 참여하세요.',
        beta_form_desc: '등록하시면 접근 권한이 준비되는 즉시 연락드리겠습니다. 스팸 없음을 약속합니다.',
        beta_name_label: '이름',
        beta_email_label: '이메일',
        beta_name_placeholder: '이름을 입력하세요',
        beta_email_placeholder: 'your@email.com',
        beta_submit: '지금 등록',
        beta_submitting: '전송 중...',
        beta_success: '감사합니다! 곧 연락드리겠습니다.',
        beta_error: '오류가 발생했습니다. 다시 시도해주세요.',
        beta_duplicate: '이 이메일은 이미 등록되어 있습니다.',
        beta_privacy_note: '등록하면 <a href="terms.html">이용약관</a> 및 <a href="privacy.html">개인정보 처리방침</a>에 동의하게 됩니다.',

        // Page titles
        page_title_index: 'Oblivio – 기억을 넘어서',
        page_title_about: 'Oblivio 소개 – Oblivio',
        page_title_features: '기술 – Oblivio',
        page_title_blog: '블로그 – Oblivio',
        page_title_faq: 'FAQ – Oblivio',
        page_title_pricing: '요금제 – Oblivio',
        page_title_security: '보안 – Oblivio',
        page_title_contact: '문의 – Oblivio',
        page_title_journey: '여정 – Oblivio',
        page_title_biographer: '전기 작가 – Oblivio',
        page_title_login: '로그인 – Oblivio',
        page_title_signup: '회원가입 – Oblivio',
        page_title_privacy: '개인정보 처리방침 – Oblivio',
        page_title_terms: '이용약관 – Oblivio',
        page_title_404: '페이지를 찾을 수 없습니다 – Oblivio',
        page_title_legacy: '유산 – Oblivio',

        // Legacy Chat
        legacy_title: '유산 체험하기',
        legacy_subtitle: '유산과 대화하려면 접근 코드를 입력하세요.',
        legacy_code_placeholder: '접근 코드',
        legacy_connect_btn: '연결',
        legacy_invalid_code: '유효하지 않은 코드입니다. 다시 시도해 주세요.',
        legacy_no_data: '유산 데이터를 찾을 수 없습니다.',
        legacy_error: '오류가 발생했습니다. 다시 시도해 주세요.',
        legacy_loading: '연결 중...',
        legacy_chat_title: '대화 상대:',
        legacy_chat_subtitle: '{name}의 유산과의 대화',
        legacy_input_placeholder: '메시지를 입력하세요...',
        legacy_ended: '대화가 종료되었습니다.',
        legacy_send_error: '메시지를 보낼 수 없습니다. 다시 시도해 주세요.',
        // Legacy Visitor Info
        legacy_visitor_title: '시작하기 전에',
        legacy_visitor_subtitle: '대화를 더 개인적으로 만들기 위해.',
        legacy_visitor_name_label: '{name} 가 당신을 어떻게 부르면 좋을까요?',
        legacy_visitor_name_placeholder: '당신의 이름',
        legacy_visitor_relation_label: '{name} 와 어떤 관계입니까?',
        legacy_visitor_relation_placeholder: '선택해 주세요...',
        legacy_visitor_rel_spouse: '배우자',
        legacy_visitor_rel_child: '자녀',
        legacy_visitor_rel_parent: '부모',
        legacy_visitor_rel_sibling: '형제자매',
        legacy_visitor_rel_grandchild: '손주',
        legacy_visitor_rel_friend: '친구',
        legacy_visitor_rel_relative: '친척',
        legacy_visitor_rel_other: '기타',
        legacy_visitor_gender_label: '성별',
        legacy_visitor_gender_placeholder: '선택해 주세요...',
        legacy_visitor_gender_male: '남성',
        legacy_visitor_gender_female: '여성',
        legacy_visitor_gender_other: '기타',
        legacy_visitor_start: '대화 시작',
        legacy_visitor_required: '모든 항목을 입력해 주세요.',
        // Legacy Conversation Mode
        legacy_mode_active: '변형 2',
        legacy_mode_passive: '변형 3',
        legacy_mode_analysis: '변형 1',
        legacy_passive_hint: '{name} 에게 메시지를 보내 대화를 시작하세요…',
        legacy_mode_switch_confirm: '모드를 변경하시겠습니까? 현재 대화가 다시 시작됩니다.',

        // Biographer Completion — Access Code
        bio_complete_code_desc: '이 코드를 가족에게 공유하세요:',
        bio_complete_code_copy: '코드 복사',
        bio_complete_code_copied: '복사됨!',
        bio_complete_code_email: '이메일로 공유',
        bio_complete_email_subject: 'Oblivio 접근 코드 -',
        bio_complete_email_greeting: '안녕하세요',
        bio_complete_email_line1: '전기가 성공적으로 완성되었습니다!',
        bio_complete_email_line2: '접근 코드:',
        bio_complete_email_line3: '이 페이지를 방문하여 유산과 대화하세요:',

        // Journey — Access Code
        journey_your_code: '내 접근 코드',
        journey_code_desc: '가족이 당신의 유산과 대화할 수 있도록 이 코드를 공유하세요.',
        journey_email_code: '이메일로 공유'
};
