// Oblivio translations — it
window._oblivioLang = {
// Navigation
        nav_home: 'Home',
        nav_features: 'Caratteristiche',
        nav_philosophy: 'Filosofia',
        nav_journey: 'Viaggio',
        nav_login: 'Accedi',
        nav_signup: 'Registrati',
        nav_logout: 'Esci',
        nav_back: '← Indietro',
        nav_back_home: '← Torna alla Home',

        // Hero Section
        hero_subtitle: 'Un\'eredità digitale che vive attraverso le generazioni. Preserva la tua essenza, condividi la tua saggezza, lascia più di semplici ricordi.',
        hero_cta: 'Inizia Ora',

        // Features Section
        features_title: 'Preserva l\'Essenza',
        features_subtitle: 'Il tuo lascito, in tre passi.',
        feature1_title: 'Registrati',
        feature1_desc: 'Configura il tuo account in pochi istanti. I tuoi dati sono protetti da crittografia, accessibili soltanto a te.',
        feature2_title: 'Racconta la tua storia',
        feature2_desc: 'Lasciati guidare dal Biografo attraverso i capitoli della tua vita, dai ricordi più significativi e la quotidianità, fino ai tuoi sogni e ai valori che ti appartengono davvero.',
        feature3_title: 'Condividi il tuo Oblivio',
        feature3_desc: 'Offri alle persone più care qualcosa che duri nel tempo: un lascito vivente che custodisce la tua voce, i tuoi valori e il tuo amore ben oltre la tua presenza.',

        // Philosophy Section
        philosophy_title: 'Più che un Ricordo',
        philosophy_p1: 'Oblivio non è solo un archivio di fatti e dati. È un\'eredità vivente, un luogo dove la tua personalità, i tuoi valori e il tuo amore rimangono per sempre presenti.',
        philosophy_p2: 'Crediamo che ogni persona possieda una saggezza unica che vale la pena preservare. Per i figli, i nipoti e tutti coloro che verranno dopo di noi.',
        philosophy_p3: 'Il tempo passa, ma l\'essenziale rimane.',

        // Journey Page
        journey_welcome: 'Benvenuto su Oblivio',
        journey_subtitle: 'Cosa vorresti fare oggi?',
        journey_card1_label: 'Per Te',
        journey_card1_title: 'Racconta la tua storia',
        journey_card1_desc: 'Condividi i tuoi ricordi, le tue esperienze e la tua saggezza di vita. Il nostro Biografo ti accompagnerà con delicatezza nel raccogliere la tua storia personale, come eredità per le persone che ami.',
        journey_card1_cta: 'Inizia la conversazione',
        journey_card2_label: 'Per i Cari',
        journey_card2_title: 'Vivi un\'eredità',
        journey_card2_desc: 'Entra in dialogo con l\'eredità di una persona speciale. Ascolta le sue storie, scopri la sua saggezza e senti la sua vicinanza, ogni volta che ne hai bisogno.',
        journey_card2_cta: 'Inizia la Conversazione',
        journey_coming_soon: 'Prossimamente',

        // Login Page
        login_title: 'Bentornato',
        login_subtitle: 'Accedi per continuare il tuo viaggio',
        login_email: 'Email',
        login_password: 'Password',
        login_button: 'Accedi',
        login_signing_in: 'Accesso in corso...',
        login_no_account: 'Non hai un account?',
        login_create_here: 'Creane uno qui',
        login_success: 'Accesso riuscito! Reindirizzamento...',

        // Signup Page
        signup_title: 'Crea Account',
        signup_subtitle: 'Inizia il tuo viaggio nell\'eredità oggi',
        signup_name: 'Nome Completo',
        signup_name_placeholder: 'Il tuo nome completo',
        signup_email: 'Email',
        signup_email_placeholder: 'tua@email.it',
        signup_password: 'Password',
        signup_password_placeholder: 'Crea una password sicura',
        signup_password_req: 'Almeno 6 caratteri',
        signup_confirm: 'Conferma Password',
        signup_confirm_placeholder: 'Conferma la tua password',
        signup_button: 'Crea Account',
        signup_creating: 'Creazione Account...',
        signup_have_account: 'Hai già un account?',
        signup_signin_here: 'Accedi qui',
        signup_success: 'Account creato con successo! Reindirizzamento al login...',
        signup_error_match: 'Le password non corrispondono',
        signup_error_length: 'La password deve essere lunga almeno 6 caratteri',

        // Biographer Page
        bio_title: 'Il Biografo',
        bio_subtitle: 'Preserviamo insieme la tua storia',
        bio_input_placeholder: 'Scrivi qui la tua risposta...',
        bio_send: 'Invia',
        bio_complete_title: 'Biografia completata',
        bio_complete: 'Grazie per aver condiviso la tua storia con me. La tua eredità viene preparata con cura — Dennis ti contatterà non appena tutto sarà pronto per farti vivere l\'esperienza.',

        // Language Selection Modal
        lang_modal_title: 'Scegli la tua lingua',
        lang_modal_subtitle: 'Seleziona la lingua per la tua conversazione con il Biografo',
        lang_modal_continue: 'Continua',

        // Footer
        footer_tagline: 'Preserva ciò che è indimenticabile.<br>Un\'eredità per l\'eternità.',
        footer_product: 'Prodotto',
        footer_features: 'Caratteristiche',
        footer_pricing: 'Prezzi',
        footer_security: 'Sicurezza',
        footer_faq: 'FAQ',
        footer_company: 'Azienda',
        footer_about: 'Su Oblivio',
        footer_blog: 'Blog',
        footer_careers: 'Carriere',
        footer_press: 'Stampa',
        footer_legal: 'Legale',
        footer_privacy: 'Privacy',
        footer_terms: 'Termini di Servizio',
        footer_imprint: 'Impronta',
        footer_contact: 'Contatto',
        footer_rights: '© 2026 Oblivio. Tutti i diritti riservati.',
        footer_tech: 'Tecnologia',
        nav_tech_link: 'Tecnologia',
        nav_about_link: 'Su Oblivio',
        nav_start_link: 'Inizia',
        sec_label: 'Sicurezza',
        sec_h1: 'La tua storia<br>appartiene solo a te.',
        sec_sub: 'Ciò che condividi con Oblivio è la cosa più intima che possiedi. La trattiamo di conseguenza.',
        sec_c1_title: 'Crittografia',
        sec_c1_desc: 'Tutte le connessioni sono crittografate con TLS. I dati sono memorizzati in Supabase con crittografia a riposo. Nessuno può leggerli in testo normale.',
        sec_c2_title: 'Row Level Security',
        sec_c2_desc: 'Supabase RLS garantisce che ogni query del database restituisca solo i tuoi dati, rendendo tecnicamente impossibile accedere ai dati altrui.',
        sec_c3_title: 'Autenticazione JWT',
        sec_c3_desc: 'L\'accesso al tuo account è protetto da JSON Web Token firmati. I token scaduti o non validi vengono automaticamente rifiutati.',
        sec_c4_title: 'Infrastruttura Svizzera',
        sec_c4_desc: 'Il frontend è gestito tramite un fornitore di hosting svizzero certificato. La legge svizzera sulla protezione dei dati (revLPD) si applica come standard minimo.',
        sec_c5_title: 'Nessun Tracking, nessuna pubblicità',
        sec_c5_desc: 'Oblivio non utilizza tracker pubblicitari, nessun servizio di analisi di terze parti e non vende dati degli utenti. A nessuno.',
        sec_c6_title: 'Diritto alla Cancellazione',
        sec_c6_desc: 'Puoi richiedere la cancellazione dei tuoi dati in qualsiasi momento. Il tuo account, le conversazioni e il lascito verranno rimossi completamente e irreversibilmente.',
        sec_auth_title: 'Autenticazione e Accesso',
        sec_auth_p1: 'L\'accesso a Oblivio avviene esclusivamente tramite un indirizzo email verificato combinato con una password scelta dall\'utente. Le password non vengono mai memorizzate in testo normale. Supabase Auth utilizza l\'hashing <strong>bcrypt</strong>, uno degli standard più sicuri per la memorizzazione delle password.',
        sec_auth_p2: 'Le sessioni sono gestite da token JWT di breve durata. Dopo un certo periodo, questi vengono automaticamente rinnovati o invalidati, in modo che le sessioni scadute non garantiscano l\'accesso.',
        sec_auth_box: '<strong>Row Level Security (RLS)</strong> è abilitata su tutte le tabelle. Ciò significa: anche se si verificasse un errore tecnico nella logica dell\'applicazione, il database a livello di server garantirebbe che nessun utente possa accedere ai dati altrui.',
        sec_dm_title: 'Minimizzazione dei Dati',
        sec_dm_p1: 'Oblivio raccoglie solo ciò che è necessario per il servizio: nome, indirizzo email, preferenza linguistica e il contenuto delle tue conversazioni con il Biografo. Non vengono raccolti dati di localizzazione, impronte digitali del dispositivo o schemi comportamentali oltre la necessità tecnica.',
        sec_dm_p2: 'I contenuti delle conversazioni vengono utilizzati esclusivamente per generare il tuo lascito e non sono soggetti ad altre analisi, addestramento di modelli AI di terze parti o condivisione.',
        sec_ai_title: 'Richieste AI',
        sec_ai_p: 'I contenuti delle conversazioni vengono trasmessi all\'API OpenAI GPT per l\'elaborazione. OpenAI si è impegnata contrattualmente a non utilizzare le richieste API dei clienti business per addestrare i propri modelli. La trasmissione avviene esclusivamente con crittografia (TLS 1.3) e solo per la durata dell\'elaborazione, senza archiviazione permanente presso OpenAI.',
        price_label: 'Prezzi',
        price_h1: 'I sogni non dovrebbero<br>mandare fatture.',
        price_sub: 'Oblivio è e rimane gratuito per ogni utente. Ecco la storia onesta dietro tutto questo.',
        price_s1_title: 'La verità sulle API',
        price_s1_p1: 'Dietro ogni conversazione con il Biografo ci sono costi reali. Ogni messaggio che scrivi viaggia verso i data center di OpenAI e ritorna come risposta ponderata ed empatica. Ogni ricordo salvato occupa spazio sui server Supabase. Ogni chiamata all\'AI PROMISE consuma capacità di calcolo su Railway.',
        price_s1_p2: 'Non sono costi ipotetici. Sono tariffe API reali che si generano ad ogni conversazione:',
        price_cost1_title: 'OpenAI (GPT API)',
        price_cost1_desc: 'I costi token si generano per blocco di conversazione, a seconda della profondità della conversazione e della lunghezza del contesto di sistema.',
        price_cost2_title: 'Supabase',
        price_cost2_desc: 'Query del database, autenticazione e archiviazione delle storie di conversazione e dei lasciti.',
        price_cost3_title: 'Railway',
        price_cost3_desc: 'Operazione continua del servizio backend PROMISE, intensivo in calcolo con utenti simultanei.',
        price_cost4_title: 'Web Hosting (CH)',
        price_cost4_desc: 'Hosting e consegna del frontend tramite il dominio oblivio.ch.',
        price_s2_title: 'Perché comunque gratuito?',
        price_s2_p1: 'Oblivio è un progetto del cuore, nato non da un piano aziendale, ma da una semplice convinzione: <em>ogni persona merita di essere ascoltata e ricordata.</em> Non solo chi può permettersi software costosi.',
        price_s2_p2: 'L\'idea di documentare la propria vita, preservare la propria voce per le generazioni future, tramandare la propria saggezza: non è un lusso. È un bisogno profondamente umano. Oblivio vuole essere il luogo dove questo bisogno viene soddisfatto, indipendentemente dal conto in banca.',
        price_s2_p3: 'Nella fase attuale come progetto di ricerca accademica alla ZHAW, i costi sono sostenuti dagli sviluppatori. Ciò che conta è l\'esperienza, e dev\'essere completa, illimitata e dignitosa.',
        price_plan_label: 'Piano Attuale',
        price_plan_name: 'Oblivio Free',
        price_plan_price: 'CHF 0',
        price_plan_per: '/ mese',
        price_plan_desc: 'Accesso completo al Biografo, a tutti i 10 blocchi di conversazione, all\'archiviazione automatica del lascito e al legacy digitale, senza restrizioni.',
        price_inc1: '10 blocchi di conversazione',
        price_inc2: 'Archiviazione automatica della conoscenza',
        price_inc3: 'Legacy digitale',
        price_inc4: 'Tutte le 8 lingue',
        price_inc5: 'Crittografia sicura',
        price_inc6: 'Nessuna pubblicità',
        price_footnote: 'Oblivio è in sviluppo attivo. Le funzionalità future, come la clonazione vocale con ElevenLabs o la continuazione della conversazione da parte dei familiari, saranno introdotte nello spirito di questa promessa: con dignità, cura e il più accessibile possibile.',
        faq_label: 'FAQ',
        faq_h1: 'Domande<br>frequenti',
        faq_sub: 'Tutto quello che vuoi sapere su Oblivio, risposto chiaramente e onestamente.',
        faq_cat1: 'Generale',
        faq_q1: 'Cos\'è Oblivio?',
        faq_a1: 'Oblivio è una piattaforma digitale dove puoi documentare l\'opera della tua vita, guidato da un Biografo AI. Le conversazioni, intuizioni e ricordi risultanti vengono archiviati come legacy digitale che i tuoi cari potranno vivere in futuro.',
        faq_q2: 'Per chi è Oblivio?',
        faq_a2: 'Per chiunque abbia una storia da raccontare, cioè per ogni persona. Oblivio si rivolge in particolare a persone che desiderano preservare la loro saggezza, i loro ricordi e la loro personalità per figli, nipoti e generazioni future.',
        faq_q3: 'Come funziona il Biografo?',
        faq_a3: 'Il Biografo ti guida attraverso dieci blocchi di conversazione tematici, dalla tua vita quotidiana attraverso ricordi, relazioni e valori fino al tuo lascito. Ogni blocco è una conversazione profonda, automaticamente riassunta e salvata una volta raccolte informazioni significative sufficienti.',
        faq_q4: 'In quali lingue è disponibile Oblivio?',
        faq_a4: 'Oblivio supporta attualmente otto lingue: tedesco, inglese, francese, italiano, turco, coreano, giapponese e cinese. Scegli la lingua del Biografo all\'inizio della prima conversazione. Il Biografo comunicherà poi sempre in quella lingua.',
        faq_cat2: 'Conversazione &amp; Biografo',
        faq_q5: 'Quanti blocchi di conversazione ci sono?',
        faq_a5: 'Ci sono dieci blocchi: Vita Quotidiana, Emozioni, Ricordi, Relazioni, Crescita Personale, Sogni, Valori, Lascito, Messaggi Personali e Conclusione. Ogni blocco si dedica a una propria area di vita e viene completato solo quando il Biografo ha raccolto risposte profonde sufficienti.',
        faq_q6: 'Posso interrompere e riprendere la conversazione?',
        faq_a6: 'Sì. La cronologia della tua conversazione viene salvata automaticamente in Supabase. Quando accedi di nuovo, riprendi da dove ti eri fermato, incluso il blocco di conversazione attuale.',
        faq_q7: 'Cosa succede alla fine di tutti i 10 blocchi?',
        faq_a7: 'Dopo aver completato tutti e dieci i blocchi, il tuo legacy digitale completo viene salvato automaticamente. Contiene le intuizioni riassunte da tutte le conversazioni. In una versione futura, i familiari potranno entrare in dialogo con questo lascito.',
        faq_q8: 'Il Biografo ascolta davvero, o è testo standard?',
        faq_a8: 'Il Biografo è alimentato da un modello linguistico GPT di OpenAI. Legge ogni tua frase, ricorda il contesto dell\'intera conversazione e pone domande di follow-up che rispondono genuinamente a ciò che hai detto. Non è un modulo. È una vera conversazione.',
        faq_cat3: 'Privacy &amp; Sicurezza',
        faq_q9: 'Chi può leggere le mie conversazioni?',
        faq_a9: 'Nessuno tranne te. Supabase Row Level Security garantisce che ogni query del database sia tecnicamente limitata ai tuoi dati. Nessun amministratore, sviluppatore o altro utente può visualizzare i contenuti delle tue conversazioni.',
        faq_q10: 'I miei dati vengono usati per l\'addestramento AI?',
        faq_a10: 'No. OpenAI si impegna contrattualmente a non utilizzare le richieste API dei clienti business per addestrare i modelli. I contenuti delle tue conversazioni vengono elaborati esclusivamente per generare risposte e non vengono archiviati successivamente.',
        faq_q11: 'Posso far cancellare i miei dati?',
        faq_a11: 'Sì, in qualsiasi momento. Invia un\'email a <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a> con l\'oggetto "Cancellazione dati", e tutti i tuoi dati verranno rimossi completamente e irreversibilmente.',
        faq_cat4: 'Costi',
        faq_q12: 'Oblivio è davvero gratuito?',
        faq_a12: 'Sì. Oblivio è un progetto di ricerca accademica della ZHAW ed è completamente disponibile per tutti gli utenti gratuitamente, senza costi nascosti, senza restrizioni freemium e senza pubblicità. Maggiori informazioni nella <a href="pricing.html">pagina dei prezzi</a>.',
        faq_q13: 'Oblivio rimarrà permanentemente gratuito?',
        faq_a13: 'È l\'intenzione. Poiché Oblivio è nato come tesi di laurea, i costi operativi sono gestibili. Se il progetto dovesse crescere, qualsiasi cambiamento al modello di business sarà comunicato in modo trasparente.',
        tech_label: 'Tecnologia',
        tech_h1: 'L\'Architettura<br>dell\'Eterno',
        tech_sub: 'Oblivio unisce ricerca all\'avanguardia con un\'infrastruttura ponderata, affinché ogni storia sia preservata in sicurezza, ogni conversazione prenda vita e ogni legacy rimanga accessibile permanentemente.',
        tech_intro: 'Dietro Oblivio non ci sono soluzioni preconfezionate, ma tecnologie scelte consapevolmente che insieme creano un sistema che bilancia dignità, sicurezza e profondità.',
        tech_01_sub: 'Framework AI Conversazionale',
        tech_01_title: 'PROMISE',
        tech_01_p: 'PROMISE è un framework scientifico della <strong>ZHAW – Università di Scienze Applicate di Zurigo</strong>, che consente conversazioni AI a più fasi basate sullo stato. Il Biografo di Oblivio è costruito interamente su PROMISE: ognuno dei dieci blocchi di conversazione tematici è uno stato indipendente con il proprio contesto di sistema, condizioni di transizione ed estrazione automatica della conoscenza. Il servizio backend è fornito tramite <strong>Railway</strong>.',
        tech_01_tag1: 'ZHAW Research',
        tech_01_tag2: 'Stateful AI',
        tech_02_sub: 'Modello Linguistico',
        tech_02_title: 'GPT di OpenAI',
        tech_02_p: 'Le conversazioni del Biografo sono alimentate da un <strong>modello linguistico GPT di OpenAI</strong>. I modelli di OpenAI sono stati addestrati su enormi quantità di linguaggio umano e sono in grado di condurre conversazioni contestualmente sensibili ed empatiche. Questo permette a Oblivio di tenere conversazioni che non sembrano meccaniche, ma come un interlocutore attento: paziente, perspicace e sempre interessato alla persona.',
        tech_02_tag1: 'OpenAI',
        tech_02_tag2: 'GPT',
        tech_03_sub: 'Database &amp; Autenticazione',
        tech_03_title: 'Supabase',
        tech_03_p: 'Tutti i dati utente, le cronologie delle conversazioni e i lasciti archiviati sono memorizzati in <strong>Supabase</strong>, una piattaforma PostgreSQL aperta con Row Level Security (RLS). Ciò significa: nessun utente può accedere ai dati di un altro, né per errori né per vulnerabilità. L\'autenticazione avviene tramite token JWT crittografati.',
        tech_03_tag1: 'PostgreSQL',
        tech_03_tag2: 'Row Level Security',
        tech_04_sub: 'Infrastruttura Backend',
        tech_04_title: 'Railway',
        tech_04_p: 'Il servizio backend PROMISE gira su <strong>Railway</strong>, una moderna piattaforma cloud che combina deployment automatico, scaling e monitoraggio. Ogni modifica al sistema del Biografo è live in pochi minuti, senza configurazione manuale del server. Railway garantisce che Oblivio rimanga accessibile in modo affidabile anche sotto carico.',
        tech_04_tag1: 'Auto-Deploy',
        tech_04_tag2: 'Cloud Infrastructure',
        tech_05_sub: 'Sintesi Vocale · Pianificata',
        tech_05_title: 'ElevenLabs',
        tech_05_p: 'In una versione futura di Oblivio, ogni legacy digitale dovrà essere non solo leggibile, ma <em>ascoltabile</em>. Con <strong>ElevenLabs</strong>, la piattaforma leader per la sintesi vocale realistica, sarà possibile registrare e clonare la propria voce. I familiari potranno poi non solo leggere messaggi di testo, ma risentire la voce familiare dei loro cari.',
        tech_05_tag1: 'Voice Cloning',
        tech_05_tag2: 'Roadmap 2026',
        tech_06_sub: 'Web Hosting',
        tech_06_title: 'Hosting Web Svizzero',
        tech_06_p: 'Il frontend di Oblivio è gestito tramite un rinomato provider di hosting svizzero. Il dominio <em>oblivio.ch</em> e tutte le risorse statiche vengono consegnate direttamente dalla Svizzera. Ciò significa: i dati rimangono in Svizzera, sono soggetti alla legge svizzera sulla protezione dei dati (LPD) e beneficiano di un\'eccellente infrastruttura di rete.',
        tech_06_tag1: 'Hosting Svizzero',
        tech_06_tag2: 'Conforme LPD',
        tech_arch_title: 'Come tutto si integra',
        tech_arch_lead: 'Dal tuo input al ricordo archiviato: ogni passo è ponderato e sicuro.',
        tech_flow1_title: 'Input',
        tech_flow1_p: 'Scrivi un messaggio nel browser, trasmesso crittografato tramite HTTPS.',
        tech_flow2_title: 'PROMISE elabora',
        tech_flow2_p: 'Il servizio backend Railway riceve il messaggio, determina lo stato attuale e lo invia a OpenAI GPT.',
        tech_flow3_title: 'GPT risponde',
        tech_flow3_p: 'Il modello linguistico genera una risposta empatica e contestualmente sensibile basata sullo stato attuale del Biografo.',
        tech_flow4_title: 'Supabase archivia',
        tech_flow4_p: 'La conversazione e le intuizioni estratte vengono archiviate in modo sicuro nella tua istanza Supabase personale, accessibile solo a te.',
        contact_label: 'Contatto',
        contact_h1: 'Rimaniamo<br>in contatto.',
        contact_li_title: 'Dennis Riccardo',
        contact_li_sub: 'Creatore di Oblivio · Studente alla ZHAW',
        contact_li_cta: 'Visita il profilo',
        contact_em_title: 'Email',
        contact_em_addr: 'riccaden@students.zhaw.ch',
        contact_info: '<strong>Contesto accademico:</strong> Oblivio è una tesi di laurea alla <strong>ZHAW</strong> – Università di Scienze Applicate di Zurigo. Domande, feedback o proposte di collaborazione sono benvenuti.',

        // About page
        about_label: 'Su Oblivio',
        about_h1: 'Una persona.<br>Un\'idea.<br>Un\'eredità.',
        about_sub: 'Oblivio è nato dalla convinzione che ogni persona meriti di essere ascoltata e ricordata, ben oltre la propria vita.',
        about_badge: 'Tesi di Laurea',
        about_inst: '<strong>ZHAW – Università di Scienze Applicate di Zurigo</strong> · Dipartimento di Economia · Informatica Gestionale · 2026',
        about_role: 'Sviluppatore · Studente',
        about_bio1: 'Studio Informatica Gestionale alla ZHAW di Winterthur, un corso che mi ha affascinato fin dall\'inizio perché unisce due mondi che amo entrambi: la precisione logica della tecnologia e il pensiero strategico dell\'economia.',
        about_bio2: 'Parallelamente lavoro come Project Manager presso una delle più grandi assicurazioni sanitarie della Svizzera. Lì imparo quotidianamente come organizzare sistemi complessi, come guidare le persone e come implementare cambiamenti in modo sostenibile. È un mondo che ruota molto attorno alla cura, al benessere di persone reali.',
        about_bio3: 'Oblivio è la mia tesi di laurea. Ma più ancora: è il progetto in cui si unisce tutto ciò per cui mi batto. L\'implementazione tecnica con AI e infrastrutture moderne. Il lato umano: conversazioni, ricordi, il bisogno di connessione nel tempo. E la convinzione che la tecnologia debba servire le persone, non viceversa.',
        about_bio4: 'Il mio obiettivo con Oblivio era costruire qualcosa che non solo funzionasse, ma che si sentisse giusto. Una piattaforma che tratta con dignità la cosa più intima che esiste: la vita stessa.',
        about_values_title: 'Cosa guida Oblivio',
        about_v1_title: 'Dignità',
        about_v1_p: 'Ogni storia merita di essere trattata con rispetto, non come punto dati, ma come l\'opera di vita di un essere umano.',
        about_v2_title: 'Accessibilità',
        about_v2_p: 'Preservare la propria vita non dovrebbe essere una questione di denaro. Oblivio è gratuito, e consapevolmente così.',
        about_v3_title: 'Profondità',
        about_v3_p: 'Le risposte superficiali portano a ricordi superficiali. Il biografo continua a chiedere finché non emerge l\'essenziale.',

        // Blog page
        blog_label: 'Blog',
        blog_h1: 'Come è nato<br>Oblivio.',
        blog_sub: 'Un resoconto onesto di decisioni, deviazioni e intuizioni nel percorso dall\'idea alla piattaforma.',
        blog_date: 'Primavera 2026',
        blog_tag1: 'Tesi di Laurea',
        blog_tag2: 'Sviluppo',
        blog_art_h2: 'Dall\'idea alla piattaforma viva: la storia dello sviluppo di Oblivio',
        blog_art_lead: 'Cosa inizia quando ci si chiede: cosa rimane di una persona quando non c\'è più? Oblivio è iniziato con questa domanda, e si è concluso con una risposta che contiene più decisioni tecniche di quante me ne aspettassi all\'inizio.',
        blog_h3_1: 'La domanda di partenza',
        blog_p1_1: 'L\'idea di Oblivio non è nata alla scrivania, ma in un momento di quiete personale: cosa vorrei ancora chiedere a una persona che ho perso? E viceversa: cosa vorrei lasciare io stesso quando non sarò più qui?',
        blog_p1_2: 'Queste domande mi hanno portato alla mia tesi di laurea. L\'obiettivo era ambizioso: una piattaforma basata sull\'AI che permette a ogni persona di documentare la propria vita sotto forma di eredità digitale, profonda, personale e duratura.',
        blog_quote: '"Non un modulo. Non un questionario. Una conversazione che ascolta davvero."',
        blog_h3_2: 'PROMISE: Il cuore',
        blog_p2_1: 'La spina dorsale tecnologica di Oblivio è <strong>PROMISE</strong>, un framework di conversazione basato su stati sviluppato alla ZHAW. Invece di semplici sequenze di chatbot, PROMISE abilita veri stati conversazionali: ognuno dei dieci blocchi del biografo è il proprio stato con il proprio contesto di sistema, condizioni di transizione ed estrazione automatica delle conoscenze.',
        blog_p2_2: 'La sfida centrale: quando un blocco passa al successivo? La prima soluzione era una doppia condizione: l\'utente doveva dire esplicitamente "continua", E il guard doveva confermare che abbastanza argomenti fossero stati coperti. Sembra ragionevole, ma ha portato a un bug grave.',
        blog_technote: '<strong>Bug:</strong> <code>Transition(List.of(trigger, guard), ...)</code> — logica AND. Quando l\'utente diceva "no" (Trigger = true) dopo una lunga conversazione (Guard = true), veniva attivata <code>TransferUtterancesAction</code> — e poiché l\'intera storia della conversazione veniva trasferita a tutti gli stati successivi, TUTTI i guard valutavano contemporaneamente come true. Il Blocco 1 saltava direttamente a "Biography Complete".<br><br><strong>Soluzione:</strong> <code>Transition(List.of(guard), ...)</code> — Solo guard. Nessun trigger. Il cambio avviene automaticamente non appena vengono raccolte abbastanza risposte significative.',
        blog_h3_3: 'Dieci blocchi invece di uno',
        blog_p3_1: 'La versione originale del biografo era un unico stato, un flusso di conversazione infinito senza struttura. Il problema: senza guida tematica, molte aree della vita rimanevano intonse. Gli utenti parlavano di ricordi d\'infanzia, ma mai dei loro valori. Del loro lavoro, ma mai dei loro sogni.',
        blog_p3_2: 'La soluzione è stata il passaggio a dieci blocchi tematici: Ice-Breaker (Geschmack & Vorlieben), Alltag & Lebenswelt, Kommunikationsstil, Erinnerungen & Schlüsselerlebnisse, Emotionen & Beziehungsmuster, Beziehungen & Fremdbild, Werte & Überzeugungen, Macken & Widersprüche, Vermächtnis & Zukunft e Abschluss. Ogni blocco è progettato per esplorare completamente un\'area specifica della vita, e solo allora passa automaticamente al successivo.',
        blog_h3_4: 'Frontend: tra funzione e dignità',
        blog_p4_1: 'Il design di Oblivio seguiva una premessa chiara: non dovrebbe sembrare un\'app, ma una lettera. La tavolozza dei colori (crema, antracite, rosso ruggine, verde muschio) è stata scelta deliberatamente per trasmettere calore e permanenza. I font Crimson Pro e DM Serif Display portano la letteratura nell\'interfaccia.',
        blog_p4_2: 'La barra di avanzamento, che appare dopo il Blocco 1 e accompagna l\'utente dal Blocco 1 al 10, è stata una piccola ma significativa decisione UX: il progresso visibile fornisce orientamento senza interrompere la conversazione. Il suo stato viene salvato nel <code>localStorage</code> così viene preservato dopo un aggiornamento.',
        blog_h3_5: 'Il questionario Blocco 0',
        blog_p5_1: 'Prima che inizi il vero biografo, l\'utente completa un breve questionario: nome, fascia d\'età, sesso, stato civile, tratti della personalità e stile di comunicazione. Queste informazioni vengono fornite al biografo come contesto. Sa quindi con chi ha a che fare e può adattare il suo tono, le sue domande e le sue reazioni di conseguenza.',
        blog_p5_2: 'Questo "Blocco 0" è disponibile in sette lingue (tedesco, inglese, francese, italiano, coreano, giapponese e cinese) ed è stato progettato per sembrare rapido, discreto e onesto. Il modulo di consenso precedente comunica chiaramente cosa viene memorizzato e perché.',
        blog_h3_6: 'Supabase, Railway & Hosting Svizzero',
        blog_p6_1: 'L\'infrastruttura di Oblivio è stata scelta secondo un principio semplice: ogni componente dovrebbe essere la migliore nella sua categoria, funzionare bene insieme e non aggiungere complessità inutile. Supabase per autenticazione e database. Railway per il servizio backend PROMISE con auto-deploy ad ogni git push. Un provider svizzero per l\'hosting frontend.',
        blog_p6_2: 'Railway si è rivelato particolarmente prezioso: ogni modifica al backend Java (nuovi guard, nuovi prompt, nuovo supporto linguistico) è live in pochi minuti. Questo ha aumentato significativamente la velocità di iterazione.',
        blog_h3_7: 'Cosa è già stato raggiunto',
        blog_p7_1: 'Oblivio è andato oltre la visione originale: la chat legacy è attiva — i familiari possono utilizzare un codice di accesso per entrare in dialogo con l\'eredità memorizzata. La sintesi vocale di ElevenLabs dona al Biografo una voce udibile, e grazie alla Web Speech API, gli utenti possono anche dettare le loro risposte tramite input vocale.',
        blog_p7_2: 'Oblivio è finito, ma non concluso. È una piattaforma che diventa più ricca con ogni conversazione che si tiene su di essa.',
        blog_date_v2: '9 maggio 2026',
        blog_tag_v2_1: 'Aggiornamento',
        blog_tag_v2_2: 'Iterazione',
        blog_v2_h2: 'Da quattro a otto lingue: la grande revisione',
        blog_v2_lead: 'Nelle ultime settimane Oblivio è cresciuto. Non solo nel numero di persone, ma anche nella profondità delle sue funzionalità. Ecco una panoramica dei cambiamenti più importanti.',
        blog_v2_h3_1: 'Otto lingue invece di quattro',
        blog_v2_p1: 'Oblivio supporta ora otto lingue: tedesco, inglese, francese, italiano, turco, coreano, giapponese e cinese. Il turco è stato aggiunto come ottava lingua per ampliare ulteriormente la portata internazionale. Per farlo, sono stati integrati tutti i testi dell\'interfaccia, il questionario del Biografo e le istruzioni dei blocchi.',
        blog_v2_h3_2: 'Tre varianti di conversazione',
        blog_v2_p2_1: 'Le persone legacy possono ora essere interrogate in tre modalità diverse: la variante 1 contiene un\'analisi completa della personalità con diagramma radar, DNA comunicativo e schemi di vita. La variante 2 lascia che la persona apra attivamente la conversazione. La variante 3 attende in silenzio il primo messaggio del visitatore.',
        blog_v2_p2_2: 'Ogni variante è adatta a una diversa situazione emotiva: comprensione profonda, bassa soglia d\'ingresso o controllo completo su come inizia la conversazione.',
        blog_v2_h3_3: 'Compattazione automatica del contesto',
        blog_v2_p3: 'Un miglioramento tecnico nel backend PROMISE: dopo venti messaggi dell\'utente, i contributi più vecchi della conversazione vengono automaticamente riassunti e sostituiti da un messaggio di sistema compatto. In questo modo i costi dei token rimangono costanti, mentre i contenuti più importanti vengono conservati — in modo simile a come la memoria umana lascia svanire i dettagli, ma preserva il quadro generale.',
        blog_v2_h3_4: 'Progressi visibili e lavoro di pulizia invisibile',
        blog_v2_p4_1: 'Dietro le quinte, molti componenti sono stati perfezionati: il repository è stato ristrutturato (cartelle separate per documentazione e script SQL), tutte le classi Java hanno ricevuto commenti dettagliati e i testi obsoleti sul sito web sono stati aggiornati.',
        blog_v2_p4_2: 'Anche la pagina delle persone è stata rivista: i vecchi riferimenti a singoli nomi di persone sono stati sostituiti con formulazioni generiche, in modo che la piattaforma rimanga coerente anche con le persone future.',
        blog_v2_h3_5: '15 partecipanti, nuove persone, nuove voci',
        blog_v2_p5: 'In totale 15 persone hanno preso parte allo studio e hanno condiviso la loro storia di vita con il Biografo. Ognuna di queste storie è diventata una persona a sé — con una propria immagine del profilo, una propria voce tramite ElevenLabs e un prompt di sistema in tre parti per le tre varianti di conversazione. La piattaforma ha guadagnato in varietà — lingue, fasce d\'età e percorsi di vita diversi si incontrano qui.',
        blog_v2_p_final: 'Oblivio continua a evolversi — non con un grande balzo, ma attraverso molti piccoli miglioramenti, ognuno dei quali rende la conversazione un po\' più autentica e più umana.',

        // Terms page
        terms_label: 'Legale',
        terms_h1: 'Termini di Utilizzo',
        terms_updated: 'Aggiornato: gennaio 2026',
        terms_highlight: 'Oblivio è un progetto di ricerca accademico nell\'ambito di una tesi di laurea alla ZHAW – Università di Scienze Applicate di Zurigo. Utilizzando questa piattaforma accetti questi termini di utilizzo.',
        terms_s1_title: '1. Natura del servizio',
        terms_s1_p1: 'Oblivio è una piattaforma accademica non commerciale sviluppata nell\'ambito di una tesi di laurea alla ZHAW. Il servizio è disponibile al pubblico gratuitamente e senza scopo di lucro.',
        terms_s1_p2: 'La piattaforma è in sviluppo attivo. Funzionalità, disponibilità e contenuti possono cambiare in qualsiasi momento. Non è garantito il funzionamento permanente.',
        terms_s2_title: '2. Utilizzo consentito',
        terms_s2_p1: 'Puoi utilizzare Oblivio per:',
        terms_s2_list1: '<li>Documentare la tua eredità digitale personale</li><li>Condurre conversazioni con il biografo AI</li><li>Recuperare e gestire i tuoi contenuti salvati</li>',
        terms_s2_p2: 'Non è consentito l\'utilizzo per:',
        terms_s2_list2: '<li>Richieste di massa automatizzate o abuso delle API</li><li>Inserimento di contenuti illegali, offensivi o dannosi</li><li>Tentativi di accedere ai dati di altri o aggirare le misure di sicurezza</li><li>Scopi commerciali di qualsiasi tipo senza autorizzazione scritta</li>',
        terms_s3_title: '3. I tuoi contenuti',
        terms_s3_p1: 'Tutti i contenuti che inserisci in Oblivio (conversazioni, risposte, informazioni del profilo) rimangono proprietà intellettuale. Concedi a Oblivio il diritto di elaborare e archiviare questi contenuti per il funzionamento tecnico del servizio.',
        terms_s3_p2: 'Per la ricerca accademica, i modelli di conversazione e il comportamento d\'uso possono essere valutati in <strong>forma completamente anonimizzata</strong>. Le deduzioni su singole persone non sono né intenzionali né possibili.',
        terms_s4_title: '4. Esclusione di responsabilità',
        terms_s4_p1: 'Oblivio è fornito "così com\'è". Non viene fornita alcuna garanzia per la disponibilità ininterrotta, l\'assenza di errori o l\'archiviazione permanente dei dati. Come parte di un progetto accademico, il servizio può essere interrotto, modificato o limitato in qualsiasi momento.',
        terms_s4_p2: 'Le risposte generate dall\'AI del biografo servono esclusivamente per la riflessione e la documentazione personale. Non costituiscono consulenza psicologica, medica o legale.',
        terms_s5_title: '5. Proprietà intellettuale',
        terms_s5_p1: 'Design, codice, testi e tutti gli altri contenuti della piattaforma Oblivio (ad eccezione dei contenuti degli utenti) sono protetti da copyright e sono di proprietà di Dennis Riccardo. L\'utilizzo o la riproduzione, anche parziale, senza autorizzazione scritta non è consentita.',
        terms_s6_title: '6. Fornitori terzi',
        terms_s6_p1: 'Oblivio utilizza servizi esterni (tra cui OpenAI, Supabase, Railway e un provider di hosting svizzero) per la cui privacy e termini di utilizzo i rispettivi fornitori sono responsabili. Utilizzando Oblivio accetti implicitamente l\'utilizzo di questi servizi nella misura in cui sono necessari per il funzionamento.',
        terms_s7_title: '7. Modifiche',
        terms_s7_p1: 'Questi termini di utilizzo possono essere modificati in qualsiasi momento. Le modifiche sostanziali saranno indicate sulla piattaforma. L\'uso continuato dopo una modifica costituisce accettazione.',
        terms_s8_title: '8. Contatto',
        terms_s8_p1: 'Per domande su questi termini di utilizzo: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',

        // Privacy page
        priv_label: 'Legale',
        priv_h1: 'Informativa sulla Privacy',
        priv_updated: 'Aggiornata: gennaio 2026',
        priv_s1_title: '1. Responsabile del trattamento',
        priv_s1_p1: 'Responsabile del trattamento dei dati su questa piattaforma è:',
        priv_s1_p2: '<strong>Dennis Riccardo</strong><br>Studente, ZHAW – Università di Scienze Applicate di Zurigo<br>Email: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s1_p3: 'Oblivio è un progetto di ricerca accademico nell\'ambito di una tesi di laurea. Non è un\'azienda commerciale.',
        priv_s2_title: '2. Quali dati raccogliamo',
        priv_s2_p1: 'Oblivio raccoglie esclusivamente i dati necessari per il funzionamento del servizio:',
        priv_s2_list: '<li><strong>Dati di registrazione:</strong> Indirizzo email, nome completo, password (memorizzata come hash bcrypt)</li><li><strong>Dati del profilo:</strong> Soprannome, fascia d\'età, sesso, stato civile, tratti della personalità, stile di comunicazione – forniti volontariamente nel questionario prima della conversazione</li><li><strong>Contenuto delle conversazioni:</strong> Tutti i messaggi che scrivi nella conversazione con il biografo</li><li><strong>Preferenza linguistica:</strong> La lingua scelta (DE, EN, IT, KO), memorizzata nel localStorage del browser</li>',
        priv_s2_p2: '<strong>Non</strong> vengono raccolti dati di localizzazione, impronte digitali dei dispositivi, indirizzi IP (per l\'identificazione delle persone), cookie per scopi pubblicitari o dati comportamentali.',
        priv_s3_title: '3. Finalità del trattamento',
        priv_s3_p1: 'I dati raccolti vengono utilizzati esclusivamente per le seguenti finalità:',
        priv_s3_list: '<li>Funzionamento della piattaforma e fornitura della conversazione del biografo</li><li>Personalizzazione del biografo AI in base alle tue informazioni del profilo</li><li>Archiviazione della tua eredità digitale per il recupero successivo</li><li>Autenticazione e protezione del tuo account</li><li>Ricerca accademica e valutazione nell\'ambito della tesi di laurea (anonimizzata)</li>',
        priv_s4_title: '4. Trasferimento a terzi',
        priv_s4_p1: 'I tuoi dati <strong>non</strong> vengono venduti, affittati o trasmessi a scopo pubblicitario. Per il funzionamento della piattaforma vengono utilizzati i seguenti fornitori terzi:',
        priv_s4_list: '<li><strong>Supabase</strong> (database e autenticazione) – i dati vengono elaborati in conformità con le politiche sulla privacy di Supabase</li><li><strong>OpenAI</strong> (API GPT) – i messaggi della conversazione vengono trasmessi per l\'elaborazione; OpenAI non li utilizza per il training dei modelli in conformità con il contratto</li><li><strong>Railway</strong> (infrastruttura backend) – elaborazione di richieste API senza archiviazione permanente dei dati</li><li><strong>Provider di hosting svizzero</strong> (hosting web, Svizzera) – distribuzione di file statici</li>',
        priv_s5_title: '5. Sicurezza dei dati',
        priv_s5_p1: 'Tutte le trasmissioni tra browser e server sono crittografate con TLS. Le password vengono memorizzate come hash bcrypt. Supabase Row Level Security (RLS) garantisce che nessun utente possa accedere ai dati di un altro. L\'accesso al database avviene esclusivamente tramite token JWT firmati.',
        priv_s6_title: '6. I tuoi diritti',
        priv_s6_p1: 'Hai il diritto a:',
        priv_s6_list: '<li><strong>Informazione:</strong> Richiedere quali dati sono memorizzati su di te</li><li><strong>Rettifica:</strong> Correzione di dati errati</li><li><strong>Cancellazione:</strong> Eliminazione completa e irreversibile di tutti i tuoi dati</li><li><strong>Portabilità dei dati:</strong> Fornitura dei tuoi dati in un formato leggibile da macchina</li><li><strong>Opposizione:</strong> Opposizione a determinati scopi di trattamento</li>',
        priv_s6_p2: 'Per esercitare questi diritti contatta: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s7_title: '7. Periodo di conservazione',
        priv_s7_p1: 'I tuoi dati verranno conservati finché il tuo account è attivo. Dopo una richiesta di cancellazione, tutti i dati verranno completamente rimossi entro 7 giorni lavorativi. Dopo la conclusione del progetto accademico, tutti i dati personali verranno eliminati; i risultati della valutazione anonimizzata possono rimanere nella tesi di laurea.',
        priv_s8_title: '8. Legge applicabile',
        priv_s8_p1: 'Questa informativa sulla privacy è disciplinata dalla legge svizzera sulla protezione dei dati (revLPD). Poiché Oblivio può anche attrarre utenti dall\'UE, i principi del GDPR vengono rispettati per quanto possibile.',

        // Pagina Beta
        hero_beta_cta: 'Diventa Beta Tester',
        beta_cta_title: 'Plasma il futuro di domani.',
        beta_cta_desc: 'Oblivio è in fase di test. Assicurati il tuo posto e aiutaci a creare una piattaforma che rende le storie immortali.',
        beta_label: 'Diventa tester',
        beta_title: 'Fai parte<br>della storia.',
        beta_subtitle: 'Oblivio è in fase di test. Sii tra i primi a preservare il tuo patrimonio e a plasmare il futuro della piattaforma.',
        beta_benefit1_title: 'Accesso anticipato',
        beta_benefit1_desc: 'Prova Oblivio prima che diventi pubblico e scopri per primo come l\'IA preserva il tuo patrimonio.',
        beta_benefit2_title: 'Partecipa',
        beta_benefit2_desc: 'Il tuo feedback plasma il futuro della piattaforma. Ogni risposta ci aiuta a migliorare Oblivio.',
        beta_benefit3_title: 'Gratuito',
        beta_benefit3_desc: 'Accesso completo senza costi. Crediamo che la preservazione del patrimonio debba essere accessibile a tutti.',
        beta_form_title: 'Iscriviti e partecipa.',
        beta_form_desc: 'Registrati e ti contatteremo non appena il tuo accesso sarà pronto. Niente spam, promesso.',
        beta_name_label: 'Nome',
        beta_email_label: 'Email',
        beta_name_placeholder: 'Il tuo nome',
        beta_email_placeholder: 'tua@email.com',
        beta_submit: 'Iscriviti ora',
        beta_submitting: 'Invio in corso...',
        beta_success: 'Grazie! Ti contatteremo presto.',
        beta_error: 'Si è verificato un errore. Riprova.',
        beta_duplicate: 'Questa email è già registrata.',
        beta_privacy_note: 'Iscrivendoti accetti i nostri <a href="terms.html">Termini di servizio</a> e la <a href="privacy.html">Informativa sulla privacy</a>.',

        // Page titles
        page_title_index: 'Oblivio – Oltre la Memoria',
        page_title_about: 'Chi siamo – Oblivio',
        page_title_features: 'Tecnologia – Oblivio',
        page_title_blog: 'Blog – Oblivio',
        page_title_faq: 'FAQ – Oblivio',
        page_title_pricing: 'Prezzi – Oblivio',
        page_title_security: 'Sicurezza – Oblivio',
        page_title_contact: 'Contatti – Oblivio',
        page_title_journey: 'Il tuo viaggio – Oblivio',
        page_title_biographer: 'Biografo – Oblivio',
        page_title_login: 'Accedi – Oblivio',
        page_title_signup: 'Registrati – Oblivio',
        page_title_privacy: 'Privacy – Oblivio',
        page_title_terms: 'Termini di servizio – Oblivio',
        page_title_404: 'Pagina non trovata – Oblivio',
        page_title_legacy: 'Eredità – Oblivio',

        // Legacy Chat
        legacy_title: 'Vivere un\'eredità',
        legacy_subtitle: 'Inserisci il codice di accesso per parlare con un\'eredità.',
        legacy_code_placeholder: 'Codice di accesso',
        legacy_connect_btn: 'Connetti',
        legacy_invalid_code: 'Codice non valido. Riprova.',
        legacy_no_data: 'Nessun dato di eredità trovato.',
        legacy_error: 'Si è verificato un errore. Riprova.',
        legacy_loading: 'Connessione in corso...',
        legacy_chat_title: 'Conversazione con',
        legacy_chat_subtitle: 'Una conversazione con l\'eredità di {name}',
        legacy_input_placeholder: 'Scrivi un messaggio...',
        legacy_ended: 'La conversazione è terminata.',
        legacy_send_error: 'Impossibile inviare il messaggio. Riprova.',
        // Legacy Visitor Info
        legacy_visitor_title: 'Prima di iniziare',
        legacy_visitor_subtitle: 'Per rendere la conversazione più personale.',
        legacy_visitor_name_label: 'Come ti deve chiamare {name}?',
        legacy_visitor_name_placeholder: 'Il tuo nome',
        legacy_visitor_relation_label: 'Che rapporto hai con {name}?',
        legacy_visitor_relation_placeholder: 'Seleziona...',
        legacy_visitor_rel_spouse: 'Coniuge',
        legacy_visitor_rel_child: 'Figlio/Figlia',
        legacy_visitor_rel_parent: 'Genitore',
        legacy_visitor_rel_sibling: 'Fratello/Sorella',
        legacy_visitor_rel_grandchild: 'Nipote',
        legacy_visitor_rel_friend: 'Amico/Amica',
        legacy_visitor_rel_relative: 'Parente',
        legacy_visitor_rel_other: 'Altro',
        legacy_visitor_gender_label: 'Genere',
        legacy_visitor_gender_placeholder: 'Seleziona...',
        legacy_visitor_gender_male: 'Uomo',
        legacy_visitor_gender_female: 'Donna',
        legacy_visitor_gender_other: 'Altro',
        legacy_visitor_start: 'Inizia conversazione',
        legacy_visitor_required: 'Per favore compila tutti i campi.',
        // Legacy Conversation Mode
        legacy_mode_active: 'Variante 2',
        legacy_mode_passive: 'Variante 3',
        legacy_mode_analysis: 'Variante 1',
        legacy_passive_hint: 'Scrivi un messaggio a {name} per iniziare la conversazione…',
        legacy_mode_switch_confirm: 'Cambiare modalità? La conversazione attuale verrà riavviata.',

        // Biographer Completion — Access Code
        bio_complete_code_desc: 'Condividi questo codice con i tuoi cari:',
        bio_complete_code_copy: 'Copia codice',
        bio_complete_code_copied: 'Copiato!',
        bio_complete_code_email: 'Condividi via e-mail',
        bio_complete_email_subject: 'Il tuo codice di accesso Oblivio per',
        bio_complete_email_greeting: 'Ciao',
        bio_complete_email_line1: 'La biografia è stata completata con successo!',
        bio_complete_email_line2: 'Codice di accesso:',
        bio_complete_email_line3: 'Visita questa pagina per parlare con l\'eredità:',

        // Journey — Access Code
        journey_your_code: 'Il tuo codice di accesso',
        journey_code_desc: 'Condividi questo codice con i tuoi cari per permettere loro di parlare con la tua eredità.',
        journey_email_code: 'Condividi via e-mail'
};
