// Oblivio translations — de
window._oblivioLang = {
// Navigation
        nav_home: 'Home',
        nav_features: 'Funktionen',
        nav_philosophy: 'Philosophie',
        nav_journey: 'Reise',
        nav_login: 'Anmelden',
        nav_signup: 'Registrieren',
        nav_logout: 'Abmelden',
        nav_back: '← Zurück',
        nav_back_home: '← Zurück zur Startseite',

        // Hero Section
        hero_subtitle: 'Ein digitales Erbe, das über Generationen hinweg lebt. Bewahre deine Essenz, teile deine Weisheit, hinterlasse mehr als nur Erinnerungen.',
        hero_cta: 'Jetzt starten',

        // Features Section
        features_title: 'Die Essenz bewahren',
        features_subtitle: 'Dein Vermächtnis, in drei Schritten.',
        feature1_title: 'Registriere dich',
        feature1_desc: 'Richte dein Konto in wenigen Augenblicken ein. Deine Daten werden verschlüsselt gespeichert, zugänglich nur für dich.',
        feature2_title: 'Erzähl deine Geschichte',
        feature2_desc: 'Lass dich von unserem Biografen durch die Kapitel deines Lebens führen, von prägenden Erinnerungen und deinem Alltag bis hin zu deinen Träumen und dem, was dir wirklich am Herzen liegt.',
        feature3_title: 'Teile dein Oblivio',
        feature3_desc: 'Schenke deinen Liebsten etwas Bleibendes: ein lebendiges Vermächtnis, das deine Stimme, deine Werte und deine Liebe weit über das eigene Leben hinaus trägt.',

        // Philosophy Section
        philosophy_title: 'Mehr als Erinnerung',
        philosophy_p1: 'Oblivio ist nicht nur ein Speicher für Fakten und Daten. Es ist ein lebendiges Erbe, ein Ort, an dem deine Persönlichkeit, deine Werte und deine Liebe für immer präsent bleiben.',
        philosophy_p2: 'Wir glauben, dass jeder Mensch einzigartige Weisheiten besitzt, die es wert sind, bewahrt zu werden. Für Kinder, Enkelkinder und all jene, die nach uns kommen.',
        philosophy_p3: 'Die Zeit vergeht, aber das Wesentliche bleibt.',

        // Journey Page
        journey_welcome: 'Willkommen bei Oblivio',
        journey_subtitle: 'Was möchtest du heute tun?',
        journey_card1_label: 'Für Dich',
        journey_card1_title: 'Erzähl deine Geschichte',
        journey_card1_desc: 'Teile deine Erinnerungen, Erlebnisse und Lebensweisheiten. Unser Biograf begleitet dich behutsam dabei, deine persönliche Geschichte festzuhalten, als Vermächtnis für die Menschen, die dir wichtig sind.',
        journey_card1_cta: 'Gespräch beginnen',
        journey_card2_label: 'Für Angehörige',
        journey_card2_title: 'Ein Vermächtnis erleben',
        journey_card2_desc: 'Tritt in Dialog mit dem Vermächtnis eines besonderen Menschen. Höre seine Geschichten, entdecke seine Weisheit und fühle seine Nähe, wann immer du es brauchst.',
        journey_card2_cta: 'Gespräch beginnen',
        journey_coming_soon: 'Bald verfügbar',

        // Login Page
        login_title: 'Willkommen zurück',
        login_subtitle: 'Melde dich an, um deine Reise fortzusetzen',
        login_email: 'E-Mail',
        login_password: 'Passwort',
        login_button: 'Anmelden',
        login_signing_in: 'Anmeldung läuft...',
        login_no_account: 'Noch kein Konto?',
        login_create_here: 'Hier erstellen',
        login_success: 'Anmeldung erfolgreich! Weiterleitung...',

        // Signup Page
        signup_title: 'Konto erstellen',
        signup_subtitle: 'Beginne heute deine Vermächtnis-Reise',
        signup_name: 'Vollständiger Name',
        signup_name_placeholder: 'Dein vollständiger Name',
        signup_email: 'E-Mail',
        signup_email_placeholder: 'deine@email.de',
        signup_password: 'Passwort',
        signup_password_placeholder: 'Erstelle ein sicheres Passwort',
        signup_password_req: 'Mindestens 6 Zeichen lang',
        signup_confirm: 'Passwort bestätigen',
        signup_confirm_placeholder: 'Passwort bestätigen',
        signup_button: 'Konto erstellen',
        signup_creating: 'Konto wird erstellt...',
        signup_have_account: 'Bereits ein Konto?',
        signup_signin_here: 'Hier anmelden',
        signup_success: 'Konto erfolgreich erstellt! Weiterleitung zur Anmeldung...',
        signup_error_match: 'Passwörter stimmen nicht überein',
        signup_error_length: 'Passwort muss mindestens 6 Zeichen lang sein',

        // Biographer Page
        bio_title: 'Der Biograf',
        bio_subtitle: 'Lass uns deine Geschichte gemeinsam bewahren',
        bio_input_placeholder: 'Gib hier deine Antwort ein...',
        bio_send: 'Senden',
        bio_complete_title: 'Biografie abgeschlossen',
        bio_complete: 'Vielen Dank, dass du deine Geschichte mit mir geteilt hast. Dein Vermächtnis wird nun sorgfältig aufbereitet — Dennis wird sich bei dir melden, sobald alles bereit ist und du es erleben kannst.',

        // Biographer Questions
        bio_q1: 'Hallo! Ich bin der Biograf und ich bin hier, um dir zu helfen, dein Erbe zu bewahren. Wie ist dein vollständiger Name?',
        bio_q2: 'Erzähle mir von deiner Kindheit. Wo bist du aufgewachsen und was sind deine liebsten Erinnerungen?',
        bio_q3: 'Was sind die wichtigsten Werte in deinem Leben? Welche Prinzipien leiten deine Entscheidungen?',
        bio_q4: 'Wer hatte den größten Einfluss auf dein Leben? Wie haben sie dich zu dem gemacht, der du heute bist?',
        bio_q5: 'Auf welche Leistungen in deinem Leben bist du am stolzesten?',
        bio_q6: 'Welche Lektionen hast du gelernt, die du an zukünftige Generationen weitergeben möchtest?',
        bio_q7: 'Wenn du deinen Lieben einen Ratschlag geben könntest, welcher wäre es?',
        bio_q8: 'Was bringt dir im Leben die größte Freude?',
        bio_q9: 'Gibt es noch etwas, das du über deine Lebensgeschichte teilen möchtest?',

        // Language Selection Modal
        lang_modal_title: 'Wähle deine Sprache',
        lang_modal_subtitle: 'Wähle die Sprache für dein Gespräch mit dem Biografen',
        lang_modal_continue: 'Weiter',

        // Footer
        footer_tagline: 'Bewahre das Unvergessliche.<br>Ein Erbe für die Ewigkeit.',
        footer_product: 'Produkt',
        footer_features: 'Funktionen',
        footer_pricing: 'Preise',
        footer_security: 'Sicherheit',
        footer_faq: 'FAQ',
        footer_company: 'Unternehmen',
        footer_about: 'Über Oblivio',
        footer_blog: 'Blog',
        footer_careers: 'Karriere',
        footer_press: 'Presse',
        footer_legal: 'Rechtliches',
        footer_privacy: 'Datenschutz',
        footer_terms: 'Nutzungsbedingungen',
        footer_imprint: 'Impressum',
        footer_contact: 'Kontakt',
        footer_rights: '© 2026 Oblivio. Alle Rechte vorbehalten.',
        footer_tech: 'Technologie',

        // Nav sub-page links
        nav_tech_link: 'Technologie',
        nav_about_link: 'Über Oblivio',
        nav_start_link: 'Starten',

        // Security page
        sec_label: 'Sicherheit',
        sec_h1: 'Deine Geschichte<br>gehört nur dir.',
        sec_sub: 'Was du mit Oblivio teilst, ist das Intimste, das du besitzt. Wir behandeln es entsprechend.',
        sec_c1_title: 'Verschlüsselung',
        sec_c1_desc: 'Alle Verbindungen sind TLS-verschlüsselt. Daten werden in Supabase mit Encryption at Rest gespeichert. Niemand kann sie im Klartext lesen.',
        sec_c2_title: 'Row Level Security',
        sec_c2_desc: 'Supabase RLS stellt sicher, dass jede Datenbankabfrage nur deine eigenen Daten zurückgibt, technisch unmöglich, fremde Daten abzurufen.',
        sec_c3_title: 'JWT-Authentifizierung',
        sec_c3_desc: 'Der Zugang zu deinem Konto ist durch signierte JSON Web Tokens gesichert. Abgelaufene oder ungültige Token werden automatisch abgelehnt.',
        sec_c4_title: 'Schweizer Infrastruktur',
        sec_c4_desc: 'Das Frontend wird über einen zertifizierten Schweizer Hosting-Anbieter betrieben. Das Schweizer Datenschutzgesetz (revDSG) gilt als Mindeststandard für alle Datenverarbeitungen.',
        sec_c5_title: 'Kein Tracking, keine Werbung',
        sec_c5_desc: 'Oblivio verwendet keine Werbe-Tracker, keine Analytics-Dienste von Drittanbietern und verkauft keine Nutzerdaten. An niemanden.',
        sec_c6_title: 'Recht auf Löschung',
        sec_c6_desc: 'Du kannst jederzeit die Löschung deiner Daten verlangen. Dein Konto, deine Gespräche und dein Vermächtnis werden vollständig und unwiderruflich entfernt.',
        sec_auth_title: 'Authentifizierung &amp; Zugang',
        sec_auth_p1: 'Der Zugang zu Oblivio erfolgt ausschliesslich über eine verifizierte E-Mail-Adresse in Kombination mit einem selbst gewählten Passwort. Die Passwörter werden niemals im Klartext gespeichert. Supabase Auth verwendet <strong>bcrypt</strong>-basiertes Hashing, einen der sichersten Standards für Passwortspeicherung.',
        sec_auth_p2: 'Sitzungen werden durch kurzlebige JWT-Tokens verwaltet. Nach einem bestimmten Zeitraum werden diese automatisch erneuert oder invalidiert, sodass abgelaufene Sitzungen keinen Zugang gewähren.',
        sec_auth_box: '<strong>Row Level Security (RLS)</strong> ist auf allen Tabellen aktiviert. Das bedeutet: Selbst wenn ein technischer Fehler in der Applikationslogik auftreten sollte, würde die Datenbank auf Ebene des Datenbankservers sicherstellen, dass kein Nutzer auf fremde Daten zugreift.',
        sec_dm_title: 'Datenminimierung',
        sec_dm_p1: 'Oblivio erhebt nur, was für den Dienst notwendig ist: Name, E-Mail-Adresse, Sprachpräferenz und der Inhalt deiner Gespräche mit dem Biografen. Es werden keine Standortdaten, Gerätefingerprints, Verhaltensmuster oder sonstige Metadaten erhoben, die über die technische Notwendigkeit hinausgehen.',
        sec_dm_p2: 'Gesprächsinhalte werden ausschliesslich für die Generierung deines Vermächtnisses verwendet und keiner anderen Analyse, keinem Training von KI-Modellen durch Dritte und keiner Weitergabe unterzogen.',
        sec_ai_title: 'Umgang mit KI-Anfragen',
        sec_ai_p: 'Gesprächsinhalte werden zur Verarbeitung an die OpenAI GPT API übertragen. OpenAI hat sich vertraglich verpflichtet, API-Anfragen von Business-Kunden nicht für das Training ihrer Modelle zu verwenden. Die Übertragung erfolgt ausschliesslich verschlüsselt (TLS 1.3) und nur für den Zeitraum der Verarbeitung. Es findet keine dauerhafte Speicherung bei OpenAI statt.',

        // Pricing page
        price_label: 'Preise',
        price_h1: 'Träume sollten<br>keine Rechnungen stellen.',
        price_sub: 'Oblivio ist und bleibt kostenlos für jeden Nutzer. Hier ist die ehrliche Geschichte dahinter.',
        price_s1_title: 'Die Wahrheit über APIs',
        price_s1_p1: 'Hinter jedem Gespräch mit dem Biografen stehen reale Kosten. Jede Nachricht, die du schreibst, reist zu OpenAIs Rechenzentren und kehrt als durchdachte, einfühlsame Antwort zurück. Jede gespeicherte Erinnerung belegt Speicherplatz auf Supabase-Servern. Jeder Aufruf der PROMISE-KI verbraucht Rechenkapazität auf Railway.',
        price_s1_p2: 'Das sind keine hypothetischen Kosten. Das sind reale API-Gebühren, die mit jeder Unterhaltung entstehen:',
        price_cost1_title: 'OpenAI (GPT API)',
        price_cost1_desc: 'Pro Konversationsblock fallen Token-Kosten an, je nach Tiefe des Gesprächs und Länge des Systemkontexts.',
        price_cost2_title: 'Supabase',
        price_cost2_desc: 'Datenbankabfragen, Authentifizierung und Speicherung der Gesprächsverläufe und Vermächtnisse.',
        price_cost3_title: 'Railway',
        price_cost3_desc: 'Laufender Betrieb des PROMISE-Backend-Dienstes, compute-intensiv bei gleichzeitigen Nutzern.',
        price_cost4_title: 'Webhosting (CH)',
        price_cost4_desc: 'Hosting und Auslieferung des Frontends über die Domain oblivio.ch.',
        price_s2_title: 'Warum dennoch kostenlos?',
        price_s2_p1: 'Oblivio ist ein Herzensprojekt, entstanden nicht aus einem Businessplan, sondern aus einer einfachen Überzeugung: <em>Jeder Mensch verdient es, gehört und erinnert zu werden.</em> Nicht nur jene, die sich teure Software leisten können.',
        price_s2_p2: 'Die Idee, das eigene Leben zu dokumentieren, die eigene Stimme für kommende Generationen zu bewahren, die eigene Weisheit weiterzugeben: das ist kein Luxus. Das ist ein zutiefst menschliches Bedürfnis. Oblivio will der Ort sein, an dem dieses Bedürfnis erfüllt wird, unabhängig vom Kontostand.',
        price_s2_p3: 'In der aktuellen Phase als akademisches Forschungsprojekt der ZHAW tragen die anfallenden Kosten die Entwickler. Was zählt, ist das Erlebnis, und das soll vollständig, uneingeschränkt und würdevoll sein.',
        price_plan_label: 'Aktueller Plan',
        price_plan_name: 'Oblivio Free',
        price_plan_price: 'CHF 0',
        price_plan_per: '/ Monat',
        price_plan_desc: 'Vollständiger Zugang zum Biografen, zu allen 10 Gesprächsblöcken, zur automatischen Vermächtnis-Speicherung und zur digitalen Legacy, ohne Einschränkungen.',
        price_inc1: '10 Gesprächsblöcke',
        price_inc2: 'Automatische Wissensspeicherung',
        price_inc3: 'Digitale Legacy',
        price_inc4: 'Alle 8 Sprachen',
        price_inc5: 'Sichere Verschlüsselung',
        price_inc6: 'Keine Werbung',
        price_footnote: 'Oblivio befindet sich in aktiver Entwicklung. Zukünftige Funktionen, wie die Stimmklonung mit ElevenLabs oder die Weiterführung des Gesprächs durch Angehörige, werden ebenfalls im Geiste dieses Versprechens eingeführt: mit Würde, Bedacht und so zugänglich wie möglich.',

        // FAQ page
        faq_label: 'FAQ',
        faq_h1: 'Häufig gestellte<br>Fragen',
        faq_sub: 'Alles, was du über Oblivio wissen möchtest, klar und ehrlich beantwortet.',
        faq_cat1: 'Allgemein',
        faq_q1: 'Was ist Oblivio?',
        faq_a1: 'Oblivio ist eine digitale Plattform, auf der du dein Lebenswerk dokumentieren kannst, geführt von einem KI-Biografen. Die entstehenden Gespräche, Erkenntnisse und Erinnerungen werden als digitales Vermächtnis gespeichert, das deine Liebsten künftig erleben können.',
        faq_q2: 'Für wen ist Oblivio gedacht?',
        faq_a2: 'Für jeden, der eine Geschichte zu erzählen hat, also für jeden Menschen. Oblivio richtet sich besonders an Menschen, die ihre Weisheit, ihre Erinnerungen und ihre Persönlichkeit für Kinder, Enkelkinder und künftige Generationen festhalten möchten.',
        faq_q3: 'Wie funktioniert der Biograf?',
        faq_a3: 'Der Biograf führt dich durch zehn thematische Gesprächsblöcke, von deinem Alltag über deine Erinnerungen, Beziehungen und Werte bis hin zu deinem Vermächtnis. Jeder Block ist eine tiefe Konversation, die automatisch zusammengefasst und gespeichert wird, sobald genug bedeutungsvolle Informationen gesammelt wurden.',
        faq_q4: 'In welchen Sprachen ist Oblivio verfügbar?',
        faq_a4: 'Oblivio unterstützt derzeit acht Sprachen: Deutsch, Englisch, Französisch, Italienisch, Türkisch, Koreanisch, Japanisch und Chinesisch. Die Sprache des Biografen wählst du zu Beginn des ersten Gesprächs. Der Biograf kommuniziert dann konsequent in dieser Sprache mit dir.',
        faq_cat2: 'Gespräch &amp; Biograf',
        faq_q5: 'Wie viele Gesprächsblöcke gibt es?',
        faq_a5: 'Es gibt zehn Blöcke: Alltag, Emotionen, Erinnerungen, Beziehungen, persönliches Wachstum, Träume, Werte, Vermächtnis, persönliche Botschaften und Abschluss. Jeder Block widmet sich einem eigenen Lebensbereich und wird erst abgeschlossen, wenn der Biograf genug tiefgründige Antworten gesammelt hat.',
        faq_q6: 'Kann ich das Gespräch unterbrechen und später fortsetzen?',
        faq_a6: 'Ja. Dein Gesprächsverlauf wird automatisch in Supabase gesichert. Wenn du dich erneut einloggst, setzt du dort fort, wo du aufgehört hast, einschliesslich des aktuellen Gesprächsblocks.',
        faq_q7: 'Was passiert am Ende aller 10 Blöcke?',
        faq_a7: 'Nach Abschluss aller zehn Blöcke wird dein vollständiges digitales Vermächtnis automatisch gespeichert. Es enthält die zusammengefassten Erkenntnisse aus allen Gesprächen. In einer zukünftigen Version können Angehörige dann mit diesem Vermächtnis in Dialog treten.',
        faq_q8: 'Liest der Biograf wirklich aufmerksam zu, oder ist es Standardtext?',
        faq_a8: 'Der Biograf wird von einem GPT-Sprachmodell von OpenAI angetrieben. Er liest jeden deiner Sätze, merkt sich den Kontext des gesamten Gesprächs und stellt Folgefragen, die wirklich auf das eingehen, was du gesagt hast. Es ist kein Formular. Es ist ein echtes Gespräch.',
        faq_cat3: 'Datenschutz &amp; Sicherheit',
        faq_q9: 'Wer kann meine Gespräche lesen?',
        faq_a9: 'Niemand ausser dir. Supabase Row Level Security stellt sicher, dass jede Datenbankabfrage technisch auf deine eigenen Daten beschränkt ist. Kein Administrator, kein Entwickler und kein anderer Nutzer kann deine Gesprächsinhalte einsehen.',
        faq_q10: 'Werden meine Daten für KI-Training verwendet?',
        faq_a10: 'Nein. OpenAI verpflichtet sich vertraglich, API-Anfragen von Business-Kunden nicht für das Training von Modellen zu verwenden. Deine Gesprächsinhalte werden ausschliesslich für die Generierung von Antworten verarbeitet und danach nicht gespeichert.',
        faq_q11: 'Kann ich meine Daten löschen lassen?',
        faq_a11: 'Ja, jederzeit. Schreib eine E-Mail an <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a> mit dem Betreff „Datenlöschung", und alle deine Daten werden vollständig und unwiderruflich entfernt.',
        faq_cat4: 'Kosten',
        faq_q12: 'Ist Oblivio wirklich kostenlos?',
        faq_a12: 'Ja. Oblivio ist ein akademisches Forschungsprojekt der ZHAW und steht allen Nutzern vollständig kostenlos zur Verfügung, ohne versteckte Gebühren, ohne Freemium-Einschränkungen und ohne Werbung. Mehr dazu auf der <a href="pricing.html">Preisseite</a>.',
        faq_q13: 'Bleibt Oblivio dauerhaft kostenlos?',
        faq_a13: 'Das ist die Absicht. Da Oblivio als Bachelorarbeit entstanden ist, sind die laufenden Kosten überschaubar. Sollte das Projekt wachsen, wird jede Änderung am Geschäftsmodell transparent kommuniziert.',

        // Features / Technology page
        tech_label: 'Technologie',
        tech_h1: 'Die Architektur<br>des Unvergänglichen',
        tech_sub: 'Oblivio vereint modernste Forschung mit durchdachter Infrastruktur, damit jede Geschichte sicher bewahrt, jedes Gespräch lebendig und jedes Erbe dauerhaft zugänglich bleibt.',
        tech_intro: 'Hinter Oblivio stehen keine fertigen Baukasten-Lösungen, sondern bewusst gewählte Technologien, die zusammen ein System ergeben, das Würde, Sicherheit und Tiefe in Einklang bringt.',
        tech_01_sub: 'Konversations-KI-Framework',
        tech_01_title: 'PROMISE',
        tech_01_p: 'PROMISE ist ein wissenschaftliches Framework der <strong>ZHAW – Zürcher Hochschule für Angewandte Wissenschaften</strong>, das zustandsbasierte, mehrstufige KI-Konversationen ermöglicht. Der Biograf von Oblivio basiert vollständig auf PROMISE: Jeder der zehn thematischen Gesprächsblöcke ist ein eigenständiger Zustand mit individuellem Systemkontext, Übergangsbedingungen und automatischer Wissensextraktion. Der Backend-Dienst wird über <strong>Railway</strong> bereitgestellt und ist jederzeit skalierbar erreichbar.',
        tech_01_tag1: 'ZHAW Research',
        tech_01_tag2: 'Stateful AI',
        tech_02_sub: 'Sprachmodell',
        tech_02_title: 'GPT von OpenAI',
        tech_02_p: 'Die Gespräche des Biografen werden von einem <strong>GPT-Sprachmodell von OpenAI</strong> angetrieben. OpenAIs Modelle wurden auf riesigen Mengen menschlicher Sprache trainiert und sind in der Lage, kontextsensitive, einfühlsame Konversationen zu führen. Das ermöglicht Oblivio, Gespräche zu führen, die sich nicht maschinell anfühlen, sondern wie ein aufmerksames Gegenüber: geduldig, feinfühlig und stets an der Person interessiert.',
        tech_02_tag1: 'OpenAI',
        tech_02_tag2: 'GPT',
        tech_03_sub: 'Datenbank &amp; Authentifizierung',
        tech_03_title: 'Supabase',
        tech_03_p: 'Alle Nutzerdaten, Gesprächsverläufe und gespeicherten Vermächtnisse werden in <strong>Supabase</strong> abgelegt, einer offenen PostgreSQL-Plattform mit Row Level Security (RLS). Das bedeutet: Kein Nutzer kann auf die Daten eines anderen zugreifen, nicht durch Fehler, nicht durch Schwachstellen. Die Authentifizierung erfolgt über verschlüsselte JWT-Token, und alle Verbindungen sind TLS-gesichert.',
        tech_03_tag1: 'PostgreSQL',
        tech_03_tag2: 'Row Level Security',
        tech_04_sub: 'Backend-Infrastruktur',
        tech_04_title: 'Railway',
        tech_04_p: 'Der PROMISE-Backend-Dienst läuft auf <strong>Railway</strong>, einer modernen Cloud-Plattform, die automatisches Deployment, Skalierung und Monitoring vereint. Jede Änderung am Biografen-System ist innerhalb von Minuten live, ohne manuelle Server-Konfiguration. Railway sorgt dafür, dass Oblivio auch unter Last zuverlässig erreichbar bleibt.',
        tech_04_tag1: 'Auto-Deploy',
        tech_04_tag2: 'Cloud Infrastructure',
        tech_05_sub: 'Stimmsynthese · Geplant',
        tech_05_title: 'ElevenLabs',
        tech_05_p: 'In einer zukünftigen Version von Oblivio soll jedes digitale Vermächtnis nicht nur lesbar, sondern <em>hörbar</em> sein. Mit <strong>ElevenLabs</strong>, der führenden Plattform für realistische Stimmsynthese, wird es möglich sein, die eigene Stimme aufzunehmen und zu klonen. Angehörige können dann nicht nur Textnachrichten lesen, sondern die vertraute Stimme ihrer Liebsten wieder hören.',
        tech_05_tag1: 'Voice Cloning',
        tech_05_tag2: 'Roadmap 2026',
        tech_06_sub: 'Web-Hosting',
        tech_06_title: 'Schweizer Webhosting',
        tech_06_p: 'Das Frontend von Oblivio wird über einen renommierten Schweizer Hosting-Anbieter betrieben. Die Domain <em>oblivio.ch</em> und alle statischen Ressourcen werden direkt aus der Schweiz ausgeliefert. Das bedeutet: Daten bleiben in der Schweiz, unterliegen dem Schweizer Datenschutzgesetz (DSG) und profitieren von einer exzellenten Netzinfrastruktur.',
        tech_06_tag1: 'Schweizer Hosting',
        tech_06_tag2: 'DSG-konform',
        tech_arch_title: 'Wie alles zusammenspielt',
        tech_arch_lead: 'Von deiner Eingabe bis zur gespeicherten Erinnerung: jeder Schritt ist durchdacht und gesichert.',
        tech_flow1_title: 'Eingabe',
        tech_flow1_p: 'Du schreibst eine Nachricht im Browser, verschlüsselt über HTTPS übertragen.',
        tech_flow2_title: 'PROMISE verarbeitet',
        tech_flow2_p: 'Der Railway-Backend-Dienst empfängt die Nachricht, bestimmt den aktuellen Zustand und sendet sie an OpenAI GPT.',
        tech_flow3_title: 'GPT antwortet',
        tech_flow3_p: 'Das Sprachmodell generiert eine einfühlsame, kontextsensitive Antwort basierend auf dem Zustand des Biografen.',
        tech_flow4_title: 'Supabase speichert',
        tech_flow4_p: 'Gespräch und extrahierte Erkenntnisse werden sicher in deiner persönlichen Supabase-Instanz gespeichert, zugänglich nur für dich.',

        // Contact page
        contact_label: 'Kontakt',
        contact_h1: 'Lass uns<br>in Verbindung bleiben.',
        contact_li_title: 'Dennis Riccardo',
        contact_li_sub: 'Schöpfer von Oblivio · Student an der ZHAW',
        contact_li_cta: 'Profil besuchen',
        contact_em_title: 'E-Mail',
        contact_em_addr: 'riccaden@students.zhaw.ch',
        contact_info: '<strong>Akademischer Kontext:</strong> Oblivio ist eine Bachelorarbeit an der <strong>ZHAW</strong> – Zürcher Hochschule für Angewandte Wissenschaften. Fragen, Feedback oder Zusammenarbeitsvorschläge sind herzlich willkommen.',

        // About page
        about_label: 'Über Oblivio',
        about_h1: 'Eine Person.<br>Eine Idee.<br>Ein Erbe.',
        about_sub: 'Oblivio entstand aus der Überzeugung, dass jeder Mensch es verdient, gehört und erinnert zu werden, weit über das eigene Leben hinaus.',
        about_badge: 'Bachelorarbeit',
        about_inst: '<strong>ZHAW – Zürcher Hochschule für Angewandte Wissenschaften</strong> · Departement Wirtschaft · Wirtschaftsinformatik · 2026',
        about_role: 'Entwickler · Student',
        about_bio1: 'Ich studiere Wirtschaftsinformatik an der ZHAW in Winterthur, einem Studiengang, der mich von Anfang an fasziniert hat, weil er zwei Welten verbindet, die ich beide liebe: die logische Präzision der Technologie und das strategische Denken der Wirtschaft.',
        about_bio2: 'Parallel dazu arbeite ich als Project Manager bei einer der grössten Krankenversicherungen der Schweiz. Dort lerne ich täglich, wie komplexe Systeme organisiert, wie Menschen geführt und wie Veränderungen nachhaltig umgesetzt werden. Es ist eine Welt, in der es viel um Sorgfalt geht, um das Wohlergehen echter Menschen.',
        about_bio3: 'Oblivio ist meine Bachelorarbeit. Aber mehr noch: Es ist das Projekt, in dem all das zusammenkommt, wofür ich stehe. Die technische Umsetzung mit KI und modernen Infrastrukturen. Die menschliche Seite: Gespräche, Erinnerungen, das Bedürfnis nach Verbindung über Zeit hinweg. Und die Überzeugung, dass Technologie dem Menschen dienen soll, nicht umgekehrt.',
        about_bio4: 'Mein Ziel mit Oblivio war es, etwas zu bauen, das nicht nur funktioniert, sondern das sich richtig anfühlt. Eine Plattform, die mit Würde mit dem Intimsten umgeht, was es gibt: dem eigenen Leben.',
        about_values_title: 'Was Oblivio antreibt',
        about_v1_title: 'Würde',
        about_v1_p: 'Jede Geschichte verdient es, mit Respekt behandelt zu werden, nicht als Datenpunkt, sondern als das Lebenswerk eines Menschen.',
        about_v2_title: 'Zugänglichkeit',
        about_v2_p: 'Das Bewahren des eigenen Lebens sollte keine Frage des Geldes sein. Oblivio ist kostenlos, und das bewusst.',
        about_v3_title: 'Tiefe',
        about_v3_p: 'Oberflächliche Antworten führen zu oberflächlichen Erinnerungen. Der Biograf fragt nach, bis das Wesentliche zutage tritt.',

        // Blog page
        blog_label: 'Blog',
        blog_h1: 'Wie Oblivio<br>entstand.',
        blog_sub: 'Ein ehrlicher Bericht über Entscheidungen, Umwege und Erkenntnisse auf dem Weg von der Idee zur Plattform.',
        blog_date: 'Frühjahr 2026',
        blog_tag1: 'Bachelorarbeit',
        blog_tag2: 'Entwicklung',
        blog_art_h2: 'Von der Idee zur lebendigen Plattform: die Entwicklungsgeschichte von Oblivio',
        blog_art_lead: 'Was beginnt, wenn man sich fragt: Was bleibt von einem Menschen, wenn er nicht mehr da ist? Oblivio begann mit dieser Frage, und endete mit einer Antwort, die mehr technische Entscheidungen enthält, als ich anfangs erwartet hatte.',
        blog_h3_1: 'Die Ausgangsfrage',
        blog_p1_1: 'Die Idee zu Oblivio entstand nicht am Schreibtisch, sondern in einem Moment persönlicher Stille: Was würde ich einer Person, die ich verloren habe, noch fragen wollen? Und umgekehrt: Was würde ich selbst gerne hinterlassen, wenn ich nicht mehr hier bin?',
        blog_p1_2: 'Diese Fragen haben mich zu meiner Bachelorarbeit geführt. Das Ziel war ambitioniert: eine KI-gestützte Plattform, die es jedem Menschen ermöglicht, sein Leben in Form eines digitalen Vermächtnisses zu dokumentieren, tief, persönlich und dauerhaft.',
        blog_quote: '"Nicht ein Formular. Kein Fragebogen. Ein Gespräch, das tatsächlich zuhört."',
        blog_h3_2: 'PROMISE: Das Herzstück',
        blog_p2_1: 'Das technologische Rückgrat von Oblivio ist <strong>PROMISE</strong>, ein zustandsbasiertes Konversationsframework, das an der ZHAW entwickelt wurde. Statt einfacher Chatbot-Sequenzen ermöglicht PROMISE echte Gesprächszustände: Jeder der zehn Biografen-Blöcke ist ein eigener Zustand mit eigenem Systemkontext, eigenen Übergangsbedingungen und automatischer Wissensextraktion.',
        blog_p2_2: 'Die zentrale Herausforderung: Wann wechselt ein Block zum nächsten? Die erste Lösung war eine doppelte Bedingung: der Nutzer musste explizit „weiter" sagen, UND der Guard musste bestätigen, dass genug Themen abgedeckt wurden. Das klingt vernünftig, führte aber zu einem gravierenden Bug.',
        blog_technote: '<strong>Bug:</strong> <code>Transition(List.of(trigger, guard), ...)</code> — AND-Logik. Wenn der Nutzer „nein" sagte (Trigger = true) nach einem langen Gespräch (Guard = true), wurde <code>TransferUtterancesAction</code> ausgelöst — und da die gesamte Gesprächshistorie auf alle Folge-States übertragen wurde, evaluierten ALLE Guards gleichzeitig als true. Block 1 sprang direkt zu „Biography Complete".<br><br><strong>Lösung:</strong> <code>Transition(List.of(guard), ...)</code> — Guard allein. Kein Trigger. Der Wechsel erfolgt automatisch, sobald genug bedeutungsvolle Antworten gesammelt wurden.',
        blog_h3_3: 'Zehn Blöcke statt einem',
        blog_p3_1: 'Die ursprüngliche Version des Biografen war ein einziger State, ein endloser Konversationsfluss ohne Struktur. Das Problem: Ohne thematische Führung blieben viele Bereiche des Lebens unberührt. Nutzer sprachen über Kindheitserinnerungen, aber nie über ihre Werte. Über ihre Arbeit, aber nie über ihre Träume.',
        blog_p3_2: 'Die Lösung war der Wechsel zu zehn thematischen Blöcken: Ice-Breaker (Geschmack & Vorlieben), Alltag & Lebenswelt, Kommunikationsstil, Erinnerungen & Schlüsselerlebnisse, Emotionen & Beziehungsmuster, Beziehungen & Fremdbild, Werte & Überzeugungen, Macken & Widersprüche, Vermächtnis & Zukunft und Abschluss. Jeder Block ist so konzipiert, dass er einen spezifischen Lebensbereich vollständig erschliesst, und erst dann automatisch weiterschaltet.',
        blog_h3_4: 'Frontend: Zwischen Funktion und Würde',
        blog_p4_1: 'Das Design von Oblivio folgte einer klaren Prämisse: Es soll sich nicht anfühlen wie eine App, sondern wie ein Brief. Die Farbpalette (Creme, Anthrazit, rostrot, moosgrün) wurde bewusst gewählt, um Wärme und Dauerhaftigkeit zu vermitteln. Die Schriften Crimson Pro und DM Serif Display bringen Literatur ins Interface.',
        blog_p4_2: 'Der Fortschrittsbalken, der nach Block 1 erscheint und den Nutzer von Block 1 bis 10 begleitet, war eine kleine aber bedeutsame UX-Entscheidung: Sichtbarer Fortschritt gibt Orientierung, ohne das Gespräch zu unterbrechen. Sein Stand wird im <code>localStorage</code> gespeichert, damit er nach einem Refresh erhalten bleibt.',
        blog_h3_5: 'Der Block-0-Fragebogen',
        blog_p5_1: 'Bevor der eigentliche Biograf beginnt, durchläuft der Nutzer einen kurzen Fragebogen: Name, Altersgruppe, Geschlecht, Familienstand, Persönlichkeitsmerkmale und Kommunikationsstil. Diese Informationen werden dem Biografen als Kontext mitgegeben. Er weiss dann, wen er vor sich hat, und kann seinen Ton, seine Fragen und seine Reaktionen entsprechend anpassen.',
        blog_p5_2: 'Dieser „Block 0" ist in sieben Sprachen (Deutsch, Englisch, Französisch, Italienisch, Koreanisch, Japanisch und Chinesisch) verfügbar und wurde so gestaltet, dass er schnell, nicht aufdringlich und ehrlich wirkt. Das Einwilligungsformular davor kommuniziert klar, was gespeichert wird und warum.',
        blog_h3_6: 'Supabase, Railway & Schweizer Hosting',
        blog_p6_1: 'Die Infrastruktur von Oblivio wurde nach einem einfachen Prinzip ausgewählt: Jede Komponente sollte das Beste in ihrer Kategorie sein, gut zusammenarbeiten und keine unnötige Komplexität hinzufügen. Supabase für Authentifizierung und Datenbank. Railway für den PROMISE-Backend-Dienst mit Auto-Deploy bei jedem Git-Push. Ein Schweizer Anbieter für das Frontend-Hosting.',
        blog_p6_2: 'Railway hat sich dabei als besonders wertvoll erwiesen: Jede Änderung am Java-Backend (neue Guards, neue Prompts, neue Sprachunterstützung) ist innerhalb weniger Minuten live. Das hat die Iterationsgeschwindigkeit erheblich erhöht.',
        blog_h3_7: 'Was bereits erreicht wurde',
        blog_p7_1: 'Oblivio ist über die ursprüngliche Vision hinausgewachsen: Der Legacy-Chat ist aktiv — Angehörige können per Zugangscode mit dem gespeicherten Vermächtnis in Dialog treten. ElevenLabs-Sprachsynthese verleiht dem Biografen eine hörbare Stimme, und dank Web Speech API können Nutzer ihre Antworten auch per Spracheingabe diktieren.',
        blog_p7_2: 'Oblivio ist fertig, aber nicht abgeschlossen. Es ist eine Plattform, die mit jedem Gespräch, das auf ihr geführt wird, reicher wird.',
        blog_date_v2: '9. Mai 2026',
        blog_tag_v2_1: 'Update',
        blog_tag_v2_2: 'Iteration',
        blog_v2_h2: 'Von vier zu acht Sprachen: Die grosse Überarbeitung',
        blog_v2_lead: 'In den letzten Wochen ist Oblivio gewachsen. Nicht nur in der Anzahl der Personas, sondern auch in der Tiefe seiner Funktionen. Hier ein Überblick über die wichtigsten Änderungen.',
        blog_v2_h3_1: 'Acht Sprachen statt vier',
        blog_v2_p1: 'Oblivio unterstützt jetzt acht Sprachen: Deutsch, Englisch, Französisch, Italienisch, Türkisch, Koreanisch, Japanisch und Chinesisch. Türkisch wurde als achte Sprache hinzugefügt, um die internationale Reichweite weiter zu vergrössern. Dafür wurden alle UI-Texte, der Biograph-Fragebogen und die Block-Anweisungen ergänzt.',
        blog_v2_h3_2: 'Drei Konversationsvarianten',
        blog_v2_p2_1: 'Die Legacy-Personas können jetzt in drei verschiedenen Modi befragt werden: Variante 1 enthält eine vollständige Persönlichkeitsanalyse mit Radar-Diagramm, Kommunikations-DNA und Lebensmuster. Variante 2 lässt die Persona das Gespräch aktiv eröffnen. Variante 3 wartet schweigend auf die erste Nachricht des Besuchers.',
        blog_v2_p2_2: 'Jede Variante eignet sich für eine andere emotionale Situation: tiefes Verständnis, niedrige Einstiegshürde oder vollständige Kontrolle über den Gesprächsbeginn.',
        blog_v2_h3_3: 'Automatische Kontextkompaktion',
        blog_v2_p3: 'Eine technische Verbesserung im PROMISE-Backend: Nach zwanzig Benutzernachrichten werden ältere Gesprächsbeiträge automatisch zusammengefasst und durch eine kompakte System-Nachricht ersetzt. So bleiben die Token-Kosten konstant, während die wichtigsten Inhalte erhalten bleiben — ähnlich wie das menschliche Gedächtnis Details verblassen lässt, aber das Gesamtbild bewahrt.',
        blog_v2_h3_4: 'Sichtbare Fortschritte und unsichtbare Aufräumarbeiten',
        blog_v2_p4_1: 'Im Hintergrund wurden viele Komponenten verfeinert: Das Repository wurde neu strukturiert (separate Ordner für Dokumentation und SQL-Skripte), alle Java-Klassen erhielten ausführliche Kommentare, und veraltete Texte auf der Website wurden aktualisiert.',
        blog_v2_p4_2: 'Auch die Personenseite wurde überarbeitet: Ältere Verweise auf einzelne Persona-Namen wurden durch generische Formulierungen ersetzt, damit die Plattform auch mit zukünftigen Personas konsistent bleibt.',
        blog_v2_h3_5: '15 Teilnehmende, neue Personas, neue Stimmen',
        blog_v2_p5: 'Insgesamt haben 15 Personen an der Studie teilgenommen und ihre Lebensgeschichte mit dem Biografen geteilt. Jede dieser Geschichten wurde zu einer eigenen Persona — mit eigenem Profilbild, eigener Stimme via ElevenLabs und einem dreigeteilten System-Prompt für die drei Konversationsvarianten. Die Plattform hat dadurch an Vielfalt gewonnen — verschiedene Sprachen, Altersgruppen und Lebenswege treffen aufeinander.',
        blog_v2_p_final: 'Oblivio entwickelt sich weiter — nicht im grossen Wurf, sondern in vielen kleinen Verbesserungen, die jede für sich das Gespräch echter und menschlicher machen.',

        // Terms page
        terms_label: 'Rechtliches',
        terms_h1: 'Nutzungsbedingungen',
        terms_updated: 'Stand: Januar 2026',
        terms_highlight: 'Oblivio ist ein akademisches Forschungsprojekt im Rahmen einer Bachelorarbeit an der ZHAW – Zürcher Hochschule für Angewandte Wissenschaften. Durch die Nutzung dieser Plattform erklärst du dich mit diesen Nutzungsbedingungen einverstanden.',
        terms_s1_title: '1. Art des Dienstes',
        terms_s1_p1: 'Oblivio ist eine nicht-kommerzielle, akademische Plattform, die im Rahmen einer Bachelorarbeit an der ZHAW entwickelt wurde. Der Dienst steht der Öffentlichkeit kostenlos und ohne Gewinnerzielungsabsicht zur Verfügung.',
        terms_s1_p2: 'Die Plattform befindet sich in aktiver Entwicklung. Funktionen, Verfügbarkeit und Inhalte können sich jederzeit ändern. Es besteht keine Garantie auf dauerhaften Betrieb.',
        terms_s2_title: '2. Zulässige Nutzung',
        terms_s2_p1: 'Du darfst Oblivio verwenden, um:',
        terms_s2_list1: '<li>Dein persönliches digitales Vermächtnis zu dokumentieren</li><li>Gespräche mit dem KI-Biografen zu führen</li><li>Deine gespeicherten Inhalte abzurufen und zu verwalten</li>',
        terms_s2_p2: 'Nicht zulässig ist die Nutzung für:',
        terms_s2_list2: '<li>Automatisierte Massenanfragen oder API-Missbrauch</li><li>Die Eingabe illegaler, beleidigender oder schädlicher Inhalte</li><li>Versuche, auf fremde Daten zuzugreifen oder die Sicherheitsmassnahmen zu umgehen</li><li>Kommerzielle Zwecke jeglicher Art ohne schriftliche Genehmigung</li>',
        terms_s3_title: '3. Deine Inhalte',
        terms_s3_p1: 'Alle Inhalte, die du in Oblivio eingibst (Gespräche, Antworten, Profilinformationen) bleiben geistiges Eigentum. Du räumst Oblivio das Recht ein, diese Inhalte für den technischen Betrieb des Dienstes zu verarbeiten und zu speichern.',
        terms_s3_p2: 'Für die akademische Forschung können Gesprächsmuster und Nutzungsverhalten in <strong>vollständig anonymisierter Form</strong> ausgewertet werden. Rückschlüsse auf einzelne Personen sind weder beabsichtigt noch möglich.',
        terms_s4_title: '4. Haftungsausschluss',
        terms_s4_p1: 'Oblivio wird „wie besehen" bereitgestellt. Es wird keine Garantie für ununterbrochene Verfügbarkeit, Fehlerfreiheit oder die dauerhafte Speicherung von Daten übernommen. Im Rahmen eines akademischen Projekts kann der Dienst jederzeit eingestellt, geändert oder eingeschränkt werden.',
        terms_s4_p2: 'Die KI-generierten Antworten des Biografen dienen ausschliesslich der persönlichen Reflexion und Dokumentation. Sie stellen keine psychologische, medizinische oder rechtliche Beratung dar.',
        terms_s5_title: '5. Geistiges Eigentum',
        terms_s5_p1: 'Design, Code, Texte und alle weiteren Inhalte der Plattform Oblivio (mit Ausnahme der Nutzerinhalte) sind urheberrechtlich geschützt und Eigentum von Dennis Riccardo. Eine Nutzung oder Reproduktion, auch in Teilen, ohne schriftliche Genehmigung ist nicht gestattet.',
        terms_s6_title: '6. Drittanbieter',
        terms_s6_p1: 'Oblivio nutzt externe Dienste (u.a. OpenAI, Supabase, Railway sowie einen Schweizer Hosting-Anbieter), für deren Datenschutz- und Nutzungsbedingungen die jeweiligen Anbieter verantwortlich sind. Durch die Nutzung von Oblivio stimmst du implizit der Nutzung dieser Dienste zu, soweit sie für den Betrieb notwendig sind.',
        terms_s7_title: '7. Änderungen',
        terms_s7_p1: 'Diese Nutzungsbedingungen können jederzeit angepasst werden. Bei wesentlichen Änderungen wird auf der Plattform darauf hingewiesen. Die fortgesetzte Nutzung nach einer Änderung gilt als Zustimmung.',
        terms_s8_title: '8. Kontakt',
        terms_s8_p1: 'Bei Fragen zu diesen Nutzungsbedingungen: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',

        // Privacy page
        priv_label: 'Rechtliches',
        priv_h1: 'Datenschutzerklärung',
        priv_updated: 'Stand: Januar 2026',
        priv_s1_title: '1. Verantwortliche Person',
        priv_s1_p1: 'Verantwortlich für die Datenverarbeitung auf dieser Plattform ist:',
        priv_s1_p2: '<strong>Dennis Riccardo</strong><br>Student, ZHAW – Zürcher Hochschule für Angewandte Wissenschaften<br>E-Mail: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s1_p3: 'Oblivio ist ein akademisches Forschungsprojekt im Rahmen einer Bachelorarbeit. Es handelt sich um kein kommerzielles Unternehmen.',
        priv_s2_title: '2. Welche Daten wir erheben',
        priv_s2_p1: 'Oblivio erhebt ausschliesslich die Daten, die für den Betrieb des Dienstes notwendig sind:',
        priv_s2_list: '<li><strong>Registrierungsdaten:</strong> E-Mail-Adresse, vollständiger Name, Passwort (als bcrypt-Hash gespeichert)</li><li><strong>Profildaten:</strong> Spitzname, Altersgruppe, Geschlecht, Familienstand, Persönlichkeitsmerkmale, Kommunikationsstil – freiwillig angegeben im Fragebogen vor dem Gespräch</li><li><strong>Gesprächsinhalte:</strong> Alle Nachrichten, die du im Gespräch mit dem Biografen schreibst</li><li><strong>Sprachpräferenz:</strong> Die von dir gewählte Sprache (DE, EN, IT, KO), gespeichert im Browser-localStorage</li>',
        priv_s2_p2: 'Es werden <strong>keine</strong> Standortdaten, Gerätefingerprints, IP-Adressen (zur Personenidentifikation), Cookies für Werbezwecke oder Verhaltensdaten erhoben.',
        priv_s3_title: '3. Zweck der Datenverarbeitung',
        priv_s3_p1: 'Die erhobenen Daten werden ausschliesslich für folgende Zwecke verwendet:',
        priv_s3_list: '<li>Betrieb der Plattform und Bereitstellung des Biografen-Gesprächs</li><li>Personalisierung des KI-Biografen anhand deiner Profilinformationen</li><li>Speicherung deines digitalen Vermächtnisses für späteren Abruf</li><li>Authentifizierung und Sicherung deines Kontos</li><li>Akademische Forschung und Auswertung im Rahmen der Bachelorarbeit (anonymisiert)</li>',
        priv_s4_title: '4. Weitergabe an Dritte',
        priv_s4_p1: 'Deine Daten werden <strong>nicht</strong> verkauft, vermietet oder zu Werbezwecken weitergegeben. Für den Betrieb der Plattform werden folgende Drittanbieter eingesetzt:',
        priv_s4_list: '<li><strong>Supabase</strong> (Datenbank und Authentifizierung) – Daten werden gemäss Supabase-Datenschutzrichtlinien verarbeitet</li><li><strong>OpenAI</strong> (GPT API) – Gesprächsnachrichten werden zur Verarbeitung übermittelt; OpenAI verwendet diese vertragsgemäss nicht für Modelltraining</li><li><strong>Railway</strong> (Backend-Infrastruktur) – Verarbeitung von API-Anfragen ohne dauerhafte Datenspeicherung</li><li><strong>Schweizer Hosting-Anbieter</strong> (Web-Hosting, Schweiz) – Auslieferung statischer Dateien</li>',
        priv_s5_title: '5. Datensicherheit',
        priv_s5_p1: 'Alle Übertragungen zwischen Browser und Server sind TLS-verschlüsselt. Passwörter werden als bcrypt-Hash gespeichert. Supabase Row Level Security (RLS) stellt sicher, dass kein Nutzer auf die Daten eines anderen zugreifen kann. Datenbankzugriffe erfolgen ausschliesslich über signierte JWT-Token.',
        priv_s6_title: '6. Deine Rechte',
        priv_s6_p1: 'Du hast das Recht auf:',
        priv_s6_list: '<li><strong>Auskunft:</strong> Anfrage, welche Daten über dich gespeichert sind</li><li><strong>Berichtigung:</strong> Korrektur unrichtiger Daten</li><li><strong>Löschung:</strong> Vollständige und unwiderrufliche Löschung aller deiner Daten</li><li><strong>Datenübertragbarkeit:</strong> Herausgabe deiner Daten in einem maschinenlesbaren Format</li><li><strong>Widerspruch:</strong> Widerspruch gegen bestimmte Verarbeitungszwecke</li>',
        priv_s6_p2: 'Zur Ausübung dieser Rechte wende dich an: <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s7_title: '7. Speicherdauer',
        priv_s7_p1: 'Deine Daten werden so lange gespeichert, wie dein Konto aktiv ist. Nach einer Löschungsanfrage werden alle Daten innerhalb von 7 Werktagen vollständig entfernt. Nach Abschluss des akademischen Projekts werden alle personenbezogenen Daten gelöscht; anonymisierte Auswertungsergebnisse können in der Bachelorarbeit verbleiben.',
        priv_s8_title: '8. Anwendbares Recht',
        priv_s8_p1: 'Diese Datenschutzerklärung richtet sich nach dem Schweizer Datenschutzgesetz (revDSG). Da Oblivio auch Nutzer aus der EU ansprechen kann, werden die Grundsätze der DSGVO soweit möglich berücksichtigt.',

        // Beta-Seite
        hero_beta_cta: 'Beta-Tester werden',
        beta_cta_title: 'Gestalte die Zukunft von morgen.',
        beta_cta_desc: 'Oblivio befindet sich in der Testphase. Sichere dir jetzt deinen Platz und hilf uns, eine Plattform zu schaffen, die Geschichten unsterblich macht.',
        beta_label: 'Werde Tester',
        beta_title: 'Werde Teil<br>der Geschichte.',
        beta_subtitle: 'Oblivio befindet sich in der Testphase. Sei unter den Ersten, die ihr Vermächtnis bewahren und die Zukunft der Plattform mitgestalten.',
        beta_benefit1_title: 'Früher Zugang',
        beta_benefit1_desc: 'Teste Oblivio bevor es öffentlich wird und erlebe als Erste:r, wie KI dein Vermächtnis bewahrt.',
        beta_benefit2_title: 'Mitgestalten',
        beta_benefit2_desc: 'Dein Feedback formt die Zukunft der Plattform. Jede Rückmeldung hilft uns, Oblivio besser zu machen.',
        beta_benefit3_title: 'Kostenlos',
        beta_benefit3_desc: 'Voller Zugang ohne Kosten. Wir glauben, dass Vermächtnisbewahrung für alle zugänglich sein sollte.',
        beta_form_title: 'Jetzt anmelden und dabei sein.',
        beta_form_desc: 'Trag dich ein und wir melden uns bei dir, sobald dein Zugang bereit ist. Kein Spam, versprochen.',
        beta_name_label: 'Name',
        beta_email_label: 'E-Mail',
        beta_name_placeholder: 'Dein Name',
        beta_email_placeholder: 'deine@email.ch',
        beta_submit: 'Jetzt anmelden',
        beta_submitting: 'Wird gesendet...',
        beta_success: 'Vielen Dank! Wir melden uns bei dir.',
        beta_error: 'Ein Fehler ist aufgetreten. Bitte versuche es erneut.',
        beta_duplicate: 'Diese E-Mail ist bereits angemeldet.',
        beta_privacy_note: 'Mit der Anmeldung stimmst du unseren <a href="terms.html">Nutzungsbedingungen</a> und der <a href="privacy.html">Datenschutzerklärung</a> zu.',

        // Page titles
        page_title_index: 'Oblivio – Beyond Memory',
        page_title_about: 'Über Oblivio – Oblivio',
        page_title_features: 'Technologie – Oblivio',
        page_title_blog: 'Blog – Oblivio',
        page_title_faq: 'FAQ – Oblivio',
        page_title_pricing: 'Preise – Oblivio',
        page_title_security: 'Sicherheit – Oblivio',
        page_title_contact: 'Kontakt – Oblivio',
        page_title_journey: 'Deine Reise – Oblivio',
        page_title_biographer: 'Biograf – Oblivio',
        page_title_login: 'Anmelden – Oblivio',
        page_title_signup: 'Registrieren – Oblivio',
        page_title_privacy: 'Datenschutz – Oblivio',
        page_title_terms: 'Nutzungsbedingungen – Oblivio',
        page_title_404: 'Seite nicht gefunden – Oblivio',
        page_title_legacy: 'Vermächtnis – Oblivio',

        // Legacy Chat
        legacy_title: 'Ein Vermächtnis erleben',
        legacy_subtitle: 'Gib den Zugangscode ein, um mit dem Vermächtnis zu sprechen.',
        legacy_code_placeholder: 'Zugangscode',
        legacy_connect_btn: 'Verbinden',
        legacy_invalid_code: 'Ungültiger Code. Bitte versuche es erneut.',
        legacy_no_data: 'Keine Vermächtnisdaten gefunden.',
        legacy_error: 'Ein Fehler ist aufgetreten. Bitte versuche es erneut.',
        legacy_loading: 'Verbindung wird hergestellt...',
        legacy_chat_title: 'Gespräch mit',
        legacy_chat_subtitle: 'Ein Gespräch mit dem Vermächtnis von {name}',
        legacy_input_placeholder: 'Schreibe eine Nachricht...',
        legacy_ended: 'Das Gespräch wurde beendet.',
        legacy_send_error: 'Nachricht konnte nicht gesendet werden. Bitte versuche es erneut.',
        // Legacy Visitor Info
        legacy_visitor_title: 'Bevor wir beginnen',
        legacy_visitor_subtitle: 'Damit das Gespräch persönlicher wird.',
        legacy_visitor_name_label: 'Wie soll dich {name} nennen?',
        legacy_visitor_name_placeholder: 'Dein Name',
        legacy_visitor_relation_label: 'In welcher Beziehung stehst du zu {name}?',
        legacy_visitor_relation_placeholder: 'Bitte wählen...',
        legacy_visitor_rel_spouse: 'Ehepartner/in',
        legacy_visitor_rel_child: 'Kind',
        legacy_visitor_rel_parent: 'Elternteil',
        legacy_visitor_rel_sibling: 'Geschwister',
        legacy_visitor_rel_grandchild: 'Enkelkind',
        legacy_visitor_rel_friend: 'Freund/in',
        legacy_visitor_rel_relative: 'Verwandte/r',
        legacy_visitor_rel_other: 'Andere',
        legacy_visitor_gender_label: 'Geschlecht',
        legacy_visitor_gender_placeholder: 'Bitte wählen...',
        legacy_visitor_gender_male: 'Männlich',
        legacy_visitor_gender_female: 'Weiblich',
        legacy_visitor_gender_other: 'Divers',
        legacy_visitor_start: 'Gespräch beginnen',
        legacy_visitor_required: 'Bitte fülle alle Felder aus.',
        // Legacy Conversation Mode
        legacy_mode_active: 'Variante 2',
        legacy_mode_passive: 'Variante 3',
        legacy_mode_analysis: 'Variante 1',
        legacy_passive_hint: 'Schreibe {name} eine Nachricht, um das Gespräch zu beginnen…',
        legacy_mode_switch_confirm: 'Modus wechseln? Das aktuelle Gespräch wird neu gestartet.',

        // Biographer Completion — Access Code
        bio_complete_code_desc: 'Teile diesen Code mit Angehörigen:',
        bio_complete_code_copy: 'Code kopieren',
        bio_complete_code_copied: 'Kopiert!',
        bio_complete_code_email: 'Per E-Mail teilen',
        bio_complete_email_subject: 'Dein Oblivio Zugangscode für',
        bio_complete_email_greeting: 'Hallo',
        bio_complete_email_line1: 'Die Biografie wurde erfolgreich abgeschlossen!',
        bio_complete_email_line2: 'Zugangscode:',
        bio_complete_email_line3: 'Besuche diese Seite, um mit dem Vermächtnis zu sprechen:',

        // Journey — Access Code
        journey_your_code: 'Dein Zugangscode',
        journey_code_desc: 'Teile diesen Code mit deinen Angehörigen, damit sie mit deinem Vermächtnis sprechen können.',
        journey_email_code: 'Per E-Mail teilen'
};
