// Oblivio translations — fr
window._oblivioLang = {
// Navigation
        nav_home: 'Accueil',
        nav_features: 'Fonctionnalités',
        nav_philosophy: 'Philosophie',
        nav_journey: 'Parcours',
        nav_login: 'Connexion',
        nav_signup: 'Inscription',
        nav_logout: 'Déconnexion',
        nav_back: '← Retour',
        nav_back_home: '← Retour à l\'accueil',

        // Hero Section
        hero_subtitle: 'Un héritage numérique qui traverse les générations. Préserve ton essence, partage ta sagesse, laisse bien plus que des souvenirs.',
        hero_cta: 'Commencer',

        // Features Section
        features_title: 'Préserver l\'essentiel',
        features_subtitle: 'Ton héritage, façonné en trois étapes.',
        feature1_title: 'Inscris-toi',
        feature1_desc: 'Configure ton compte en quelques instants. Tes données sont stockées avec un chiffrement de bout en bout — accessibles à toi seul.',
        feature2_title: 'Raconte ton histoire',
        feature2_desc: 'Laisse notre Biographe te guider à travers les chapitres de ta vie — des moments du quotidien et des souvenirs précieux à tes valeurs profondes et la sagesse que tu portes en toi.',
        feature3_title: 'Partage ton Oblivio',
        feature3_desc: 'Offre à tes proches quelque chose qui perdure — un héritage vivant qui préserve ta voix, tes valeurs et ton amour bien au-delà d\'une vie.',

        // Philosophy Section
        philosophy_title: 'Plus qu\'un souvenir',
        philosophy_p1: 'Oblivio n\'est pas un simple répertoire de faits et de données. C\'est un héritage vivant, un lieu où ta personnalité, tes valeurs et ton amour restent à jamais présents.',
        philosophy_p2: 'Nous croyons que chaque personne possède une sagesse unique qui mérite d\'être préservée. Pour les enfants, les petits-enfants et tous ceux qui viendront après nous.',
        philosophy_p3: 'Le temps passe, mais l\'essentiel demeure.',

        // Journey Page
        journey_welcome: 'Bienvenue sur Oblivio',
        journey_subtitle: 'Que souhaites-tu faire aujourd\'hui ?',
        journey_card1_label: 'Pour toi',
        journey_card1_title: 'Raconte ton histoire',
        journey_card1_desc: 'Partage tes souvenirs, tes expériences et la sagesse de ta vie. Notre Biographe te guidera avec douceur pour capturer ton histoire personnelle, un héritage pour les personnes qui comptent le plus à tes yeux.',
        journey_card1_cta: 'Commencer la conversation',
        journey_card2_label: 'Pour tes proches',
        journey_card2_title: 'Découvrir un héritage',
        journey_card2_desc: 'Entre en dialogue avec l\'héritage d\'une personne spéciale. Écoute ses histoires, découvre sa sagesse et ressens sa présence, chaque fois que tu en as besoin.',
        journey_card2_cta: 'Commencer la conversation',
        journey_coming_soon: 'Bientôt disponible',

        // Login Page
        login_title: 'Bon retour',
        login_subtitle: 'Connecte-toi pour continuer ton parcours',
        login_email: 'Email',
        login_password: 'Mot de passe',
        login_button: 'Se connecter',
        login_signing_in: 'Connexion en cours...',
        login_no_account: 'Tu n\'as pas encore de compte ?',
        login_create_here: 'Crée-en un ici',
        login_success: 'Connexion réussie ! Redirection...',

        // Signup Page
        signup_title: 'Créer un compte',
        signup_subtitle: 'Commence ton parcours d\'héritage dès aujourd\'hui',
        signup_name: 'Nom complet',
        signup_name_placeholder: 'Ton nom complet',
        signup_email: 'Email',
        signup_email_placeholder: 'ton@email.com',
        signup_password: 'Mot de passe',
        signup_password_placeholder: 'Crée un mot de passe solide',
        signup_password_req: 'Au moins 6 caractères',
        signup_confirm: 'Confirmer le mot de passe',
        signup_confirm_placeholder: 'Confirme ton mot de passe',
        signup_button: 'Créer un compte',
        signup_creating: 'Création du compte...',
        signup_have_account: 'Tu as déjà un compte ?',
        signup_signin_here: 'Connecte-toi ici',
        signup_success: 'Compte créé avec succès ! Redirection vers la connexion...',
        signup_error_match: 'Les mots de passe ne correspondent pas',
        signup_error_length: 'Le mot de passe doit contenir au moins 6 caractères',

        // Biographer Page
        bio_title: 'Le Biographe',
        bio_subtitle: 'Préservons ton histoire ensemble',
        bio_input_placeholder: 'Écris ta réponse ici...',
        bio_send: 'Envoyer',
        bio_complete_title: 'Biographie terminée',
        bio_complete: 'Merci d\'avoir partagé ton histoire avec moi. Ton héritage est en cours de préparation — Dennis te contactera dès que tout sera prêt pour que tu puisses en faire l\'expérience.',

        // Biographer Questions
        bio_q1: 'Bonjour ! Je suis le Biographe et je suis là pour t\'aider à préserver ton héritage. Quel est ton nom complet ?',
        bio_q2: 'Parle-moi de ton enfance. Où as-tu grandi et quels sont tes plus beaux souvenirs ?',
        bio_q3: 'Quelles sont les valeurs les plus importantes dans ta vie ? Quels principes guident tes décisions ?',
        bio_q4: 'Qui a eu la plus grande influence sur ta vie ? Comment cette personne a-t-elle façonné qui tu es aujourd\'hui ?',
        bio_q5: 'De quelles réalisations es-tu le plus fier dans ta vie ?',
        bio_q6: 'Quelles leçons as-tu apprises que tu aimerais transmettre aux générations futures ?',
        bio_q7: 'Si tu pouvais donner un seul conseil à tes proches, quel serait-il ?',
        bio_q8: 'Qu\'est-ce qui t\'apporte le plus de joie dans la vie ?',
        bio_q9: 'Y a-t-il autre chose que tu aimerais partager sur l\'histoire de ta vie ?',

        // Language Selection Modal
        lang_modal_title: 'Choisis ta langue',
        lang_modal_subtitle: 'Sélectionne la langue pour ta conversation avec le Biographe',
        lang_modal_continue: 'Continuer',

        // Footer
        footer_tagline: 'Préserve ce qui est inoubliable.<br>Un héritage pour l\'éternité.',
        footer_product: 'Produit',
        footer_features: 'Fonctionnalités',
        footer_pricing: 'Tarifs',
        footer_security: 'Sécurité',
        footer_faq: 'FAQ',
        footer_company: 'Entreprise',
        footer_about: 'À propos d\'Oblivio',
        footer_blog: 'Blog',
        footer_careers: 'Carrières',
        footer_press: 'Presse',
        footer_legal: 'Mentions légales',
        footer_privacy: 'Confidentialité',
        footer_terms: 'Conditions d\'utilisation',
        footer_imprint: 'Mentions légales',
        footer_contact: 'Contact',
        footer_rights: '© 2026 Oblivio. Tous droits réservés.',
        footer_tech: 'Technologie',

        // Nav sub-page links
        nav_tech_link: 'Technologie',
        nav_about_link: 'À propos d\'Oblivio',
        nav_start_link: 'Commencer',

        // Security page
        sec_label: 'Sécurité',
        sec_h1: 'Ton histoire<br>n\'appartient qu\'à toi.',
        sec_sub: 'Ce que tu partages avec Oblivio est ce que tu as de plus personnel. Nous le traitons en conséquence.',
        sec_c1_title: 'Chiffrement',
        sec_c1_desc: 'Toutes les connexions sont chiffrées par TLS. Les données sont stockées dans Supabase avec un chiffrement au repos. Personne ne peut les lire en texte clair.',
        sec_c2_title: 'Row Level Security',
        sec_c2_desc: 'Le RLS de Supabase garantit que chaque requête de base de données ne renvoie que tes propres données, rendant techniquement impossible l\'accès aux données d\'une autre personne.',
        sec_c3_title: 'Authentification JWT',
        sec_c3_desc: 'L\'accès à ton compte est sécurisé par des JSON Web Tokens signés. Les tokens expirés ou invalides sont automatiquement rejetés.',
        sec_c4_title: 'Infrastructure suisse',
        sec_c4_desc: 'Le frontend est opéré par un hébergeur suisse certifié. La loi suisse sur la protection des données (nLPD) s\'applique comme standard minimal pour tout traitement de données.',
        sec_c5_title: 'Pas de tracking, pas de publicité',
        sec_c5_desc: 'Oblivio n\'utilise aucun traceur publicitaire, aucun service d\'analyse tiers et ne vend aucune donnée utilisateur. À personne.',
        sec_c6_title: 'Droit à la suppression',
        sec_c6_desc: 'Tu peux demander la suppression de tes données à tout moment. Ton compte, tes conversations et ton héritage seront entièrement et irréversiblement supprimés.',
        sec_auth_title: 'Authentification &amp; accès',
        sec_auth_p1: 'L\'accès à Oblivio se fait exclusivement via une adresse email vérifiée combinée à un mot de passe choisi par toi. Les mots de passe ne sont jamais stockés en texte clair. Supabase Auth utilise un hachage basé sur <strong>bcrypt</strong>, l\'un des standards les plus sûrs pour le stockage de mots de passe.',
        sec_auth_p2: 'Les sessions sont gérées par des tokens JWT à durée de vie limitée. Après un certain temps, ceux-ci sont automatiquement renouvelés ou invalidés, de sorte que les sessions expirées ne donnent aucun accès.',
        sec_auth_box: '<strong>Row Level Security (RLS)</strong> est activé sur toutes les tables. Cela signifie : même si une erreur technique survient dans la logique applicative, la base de données au niveau du serveur garantit qu\'aucun utilisateur ne peut accéder aux données d\'un autre utilisateur.',
        sec_dm_title: 'Minimisation des données',
        sec_dm_p1: 'Oblivio ne collecte que ce qui est nécessaire au service : nom, adresse email, préférence linguistique et le contenu de tes conversations avec le Biographe. Aucune donnée de localisation, empreinte d\'appareil, schéma comportemental ou autre métadonnée au-delà de la nécessité technique n\'est collectée.',
        sec_dm_p2: 'Le contenu des conversations est utilisé exclusivement pour la génération de ton héritage et ne fait l\'objet d\'aucune autre analyse, d\'aucun entraînement de modèle d\'IA tiers, ni d\'aucun partage.',
        sec_ai_title: 'Requêtes IA',
        sec_ai_p: 'Le contenu des conversations est transmis à l\'API GPT d\'OpenAI pour traitement. OpenAI s\'est contractuellement engagé à ne pas utiliser les requêtes API des clients professionnels pour entraîner ses modèles. La transmission est exclusivement chiffrée (TLS 1.3) et uniquement pour la durée du traitement, sans stockage permanent chez OpenAI.',

        // Pricing page
        price_label: 'Tarifs',
        price_h1: 'Les rêves ne devraient<br>pas envoyer de factures.',
        price_sub: 'Oblivio est et reste gratuit pour chaque utilisateur. Voici l\'histoire honnête qui se cache derrière.',
        price_s1_title: 'La vérité sur les API',
        price_s1_p1: 'Derrière chaque conversation avec le Biographe se cachent de vrais coûts. Chaque message que tu écris voyage vers les centres de données d\'OpenAI et revient sous forme de réponse réfléchie et empathique. Chaque souvenir stocké occupe de l\'espace sur les serveurs Supabase. Chaque appel à l\'IA PROMISE consomme de la capacité de calcul sur Railway.',
        price_s1_p2: 'Ce ne sont pas des coûts hypothétiques. Ce sont de véritables frais d\'API engagés à chaque conversation :',
        price_cost1_title: 'OpenAI (GPT API)',
        price_cost1_desc: 'Des coûts de tokens surviennent par bloc de conversation, en fonction de la profondeur de la conversation et de la longueur du contexte système.',
        price_cost2_title: 'Supabase',
        price_cost2_desc: 'Requêtes de base de données, authentification et stockage des historiques de conversation et des héritages.',
        price_cost3_title: 'Railway',
        price_cost3_desc: 'Fonctionnement continu du service backend PROMISE, gourmand en calcul lors d\'utilisations simultanées.',
        price_cost4_title: 'Hébergement web (CH)',
        price_cost4_desc: 'Hébergement et diffusion du frontend via le domaine oblivio.ch.',
        price_s2_title: 'Pourquoi gratuit malgré tout ?',
        price_s2_p1: 'Oblivio est un projet de passion, né non pas d\'un business plan, mais d\'une conviction simple : <em>chaque personne mérite d\'être entendue et rappelée.</em> Pas seulement celles qui peuvent se permettre un logiciel coûteux.',
        price_s2_p2: 'L\'idée de documenter sa propre vie, de préserver sa voix pour les générations futures, de transmettre sa sagesse : ce n\'est pas un luxe. C\'est un besoin profondément humain. Oblivio veut être le lieu où ce besoin est comblé, indépendamment du solde bancaire.',
        price_s2_p3: 'Dans la phase actuelle en tant que projet de recherche académique à la ZHAW, les développeurs assument les coûts de fonctionnement. Ce qui compte, c\'est l\'expérience, et elle doit être complète, sans restriction et digne.',
        price_plan_label: 'Offre actuelle',
        price_plan_name: 'Oblivio Free',
        price_plan_price: 'CHF 0',
        price_plan_per: '/ mois',
        price_plan_desc: 'Accès complet au Biographe, aux 10 blocs de conversation, au stockage automatique de l\'héritage et à l\'héritage numérique, sans aucune restriction.',
        price_inc1: '10 blocs de conversation',
        price_inc2: 'Stockage automatique des connaissances',
        price_inc3: 'Héritage numérique',
        price_inc4: 'Toutes les 8 langues',
        price_inc5: 'Chiffrement sécurisé',
        price_inc6: 'Aucune publicité',
        price_footnote: 'Oblivio est en développement actif. Les futures fonctionnalités, comme le clonage vocal avec ElevenLabs ou la poursuite de la conversation avec les proches, seront également introduites dans l\'esprit de cette promesse : avec dignité, soin et aussi accessibles que possible.',

        // FAQ page
        faq_label: 'FAQ',
        faq_h1: 'Questions<br>fréquentes',
        faq_sub: 'Tout ce que tu veux savoir sur Oblivio, avec des réponses claires et honnêtes.',
        faq_cat1: 'Général',
        faq_q1: 'Qu\'est-ce qu\'Oblivio ?',
        faq_a1: 'Oblivio est une plateforme numérique où tu peux documenter l\'œuvre de ta vie, guidé par un Biographe IA. Les conversations, les réflexions et les souvenirs qui en résultent sont conservés sous forme d\'héritage numérique que tes proches pourront découvrir à l\'avenir.',
        faq_q2: 'À qui s\'adresse Oblivio ?',
        faq_a2: 'À toute personne qui a une histoire à raconter, c\'est-à-dire tout le monde. Oblivio s\'adresse particulièrement aux personnes qui souhaitent préserver leur sagesse, leurs souvenirs et leur personnalité pour leurs enfants, petits-enfants et les générations futures.',
        faq_q3: 'Comment fonctionne le Biographe ?',
        faq_a3: 'Le Biographe te guide à travers dix blocs thématiques de conversation, de ta vie quotidienne en passant par les souvenirs, les relations et les valeurs jusqu\'à ton héritage. Chaque bloc est une conversation approfondie, automatiquement résumée et enregistrée une fois que suffisamment d\'informations significatives ont été recueillies.',
        faq_q4: 'Quelles langues Oblivio prend-il en charge ?',
        faq_a4: 'Oblivio prend actuellement en charge huit langues : allemand, anglais, français, italien, turc, coréen, japonais et chinois. Vous choisissez la langue du Biographe au début de votre première conversation. Le Biographe communique ensuite systématiquement dans cette langue.',
        faq_cat2: 'Conversation &amp; Biographe',
        faq_q5: 'Combien de blocs de conversation y a-t-il ?',
        faq_a5: 'Il y a dix blocs : Vie quotidienne, Émotions, Souvenirs, Relations, Développement personnel, Rêves, Valeurs, Héritage, Messages personnels et Clôture. Chaque bloc est consacré à son propre domaine de vie et n\'est complété que lorsque le Biographe a recueilli suffisamment de réponses profondes.',
        faq_q6: 'Puis-je mettre la conversation en pause et la reprendre ?',
        faq_a6: 'Oui. Ton historique de conversation est automatiquement sauvegardé dans Supabase. Lorsque tu te reconnectes, tu reprends là où tu t\'es arrêté, y compris le bloc de conversation en cours.',
        faq_q7: 'Que se passe-t-il à la fin des 10 blocs ?',
        faq_a7: 'Après avoir terminé les dix blocs, ton héritage numérique complet est automatiquement sauvegardé. Il contient les réflexions résumées de toutes les conversations. Dans une version future, les proches pourront entrer en dialogue avec cet héritage.',
        faq_q8: 'Le Biographe écoute-t-il vraiment, ou est-ce du texte standard ?',
        faq_a8: 'Le Biographe est alimenté par un modèle de langage GPT d\'OpenAI. Il lit chaque phrase que tu écris, se souvient du contexte de toute la conversation et pose des questions de suivi qui répondent véritablement à ce que tu as dit. Ce n\'est pas un formulaire. C\'est une vraie conversation.',
        faq_cat3: 'Confidentialité &amp; sécurité',
        faq_q9: 'Qui peut lire mes conversations ?',
        faq_a9: 'Personne d\'autre que toi. Le Row Level Security de Supabase garantit que chaque requête de base de données est techniquement limitée à tes propres données. Aucun administrateur, développeur ou autre utilisateur ne peut consulter le contenu de tes conversations.',
        faq_q10: 'Mes données sont-elles utilisées pour l\'entraînement de l\'IA ?',
        faq_a10: 'Non. OpenAI s\'engage contractuellement à ne pas utiliser les requêtes API des clients professionnels pour entraîner ses modèles. Le contenu de tes conversations est traité exclusivement pour la génération de réponses et n\'est pas conservé par la suite.',
        faq_q11: 'Puis-je faire supprimer mes données ?',
        faq_a11: 'Oui, à tout moment. Envoie un email à <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a> avec l\'objet « Suppression des données », et toutes tes données seront entièrement et irréversiblement supprimées.',
        faq_cat4: 'Coûts',
        faq_q12: 'Oblivio est-il vraiment gratuit ?',
        faq_a12: 'Oui. Oblivio est un projet de recherche académique à la ZHAW et est entièrement disponible pour tous les utilisateurs gratuitement, sans frais cachés, sans restrictions freemium et sans publicité. Plus de détails sur la <a href="pricing.html">page des tarifs</a>.',
        faq_q13: 'Oblivio restera-t-il gratuit de façon permanente ?',
        faq_a13: 'C\'est l\'intention. Puisqu\'Oblivio a été créé dans le cadre d\'un travail de bachelor, les coûts de fonctionnement sont maîtrisables. Si le projet grandit, tout changement du modèle économique sera communiqué de manière transparente.',

        // Features / Technology page
        tech_label: 'Technologie',
        tech_h1: 'L\'architecture<br>de l\'éternel',
        tech_sub: 'Oblivio combine recherche de pointe et infrastructure réfléchie, pour que chaque histoire soit préservée en toute sécurité, chaque conversation prenne vie et chaque héritage reste accessible de manière permanente.',
        tech_intro: 'Derrière Oblivio, pas de solutions prêtes à l\'emploi, mais des technologies consciemment choisies qui ensemble créent un système équilibrant dignité, sécurité et profondeur.',
        tech_01_sub: 'Framework d\'IA conversationnelle',
        tech_01_title: 'PROMISE',
        tech_01_p: 'PROMISE est un framework scientifique de la <strong>ZHAW – Haute école zurichoise de sciences appliquées</strong>, permettant des conversations IA multi-étapes basées sur des états. Le Biographe d\'Oblivio est entièrement construit sur PROMISE : chacun des dix blocs thématiques de conversation est un état indépendant avec son propre contexte système, ses conditions de transition et son extraction automatique de connaissances. Le service backend est fourni via <strong>Railway</strong> et est accessible de manière évolutive à tout moment.',
        tech_01_tag1: 'Recherche ZHAW',
        tech_01_tag2: 'IA à états',
        tech_02_sub: 'Modèle de langage',
        tech_02_title: 'GPT par OpenAI',
        tech_02_p: 'Les conversations du Biographe sont alimentées par un <strong>modèle de langage GPT d\'OpenAI</strong>. Les modèles d\'OpenAI ont été entraînés sur d\'immenses quantités de langage humain et sont capables de mener des conversations sensibles au contexte et empathiques. Cela permet à Oblivio de tenir des conversations qui ne semblent pas mécaniques, mais comme un interlocuteur attentif : patient, perspicace et toujours intéressé par la personne.',
        tech_02_tag1: 'OpenAI',
        tech_02_tag2: 'GPT',
        tech_03_sub: 'Base de données &amp; authentification',
        tech_03_title: 'Supabase',
        tech_03_p: 'Toutes les données utilisateur, les historiques de conversation et les héritages stockés sont conservés dans <strong>Supabase</strong>, une plateforme PostgreSQL ouverte avec Row Level Security (RLS). Cela signifie : aucun utilisateur ne peut accéder aux données d\'un autre, ni par erreur, ni par faille. L\'authentification se fait via des tokens JWT chiffrés, et toutes les connexions sont sécurisées par TLS.',
        tech_03_tag1: 'PostgreSQL',
        tech_03_tag2: 'Row Level Security',
        tech_04_sub: 'Infrastructure backend',
        tech_04_title: 'Railway',
        tech_04_p: 'Le service backend PROMISE fonctionne sur <strong>Railway</strong>, une plateforme cloud moderne combinant déploiement automatique, mise à l\'échelle et surveillance. Chaque modification du système Biographe est en ligne en quelques minutes, sans configuration manuelle de serveur. Railway garantit qu\'Oblivio reste accessible de manière fiable même en cas de charge.',
        tech_04_tag1: 'Auto-Deploy',
        tech_04_tag2: 'Infrastructure cloud',
        tech_05_sub: 'Synthèse vocale · Planifié',
        tech_05_title: 'ElevenLabs',
        tech_05_p: 'Dans une future version d\'Oblivio, chaque héritage numérique sera non seulement lisible, mais <em>audible</em>. Avec <strong>ElevenLabs</strong>, la plateforme de référence pour la synthèse vocale réaliste, il sera possible d\'enregistrer et de cloner sa propre voix. Les proches pourront alors non seulement lire des messages texte, mais aussi réentendre la voix familière de leurs êtres chers.',
        tech_05_tag1: 'Clonage vocal',
        tech_05_tag2: 'Roadmap 2026',
        tech_06_sub: 'Hébergement web',
        tech_06_title: 'Hébergement web suisse',
        tech_06_p: 'Le frontend d\'Oblivio est opéré par un hébergeur suisse renommé. Le domaine <em>oblivio.ch</em> et toutes les ressources statiques sont livrés directement depuis la Suisse. Cela signifie : les données restent en Suisse, sont soumises à la loi suisse sur la protection des données (LPD) et bénéficient d\'une excellente infrastructure réseau.',
        tech_06_tag1: 'Hébergement suisse',
        tech_06_tag2: 'Conforme LPD',
        tech_arch_title: 'Comment tout s\'articule',
        tech_arch_lead: 'De ta saisie au souvenir stocké : chaque étape est réfléchie et sécurisée.',
        tech_flow1_title: 'Saisie',
        tech_flow1_p: 'Tu écris un message dans le navigateur, transmis de manière chiffrée via HTTPS.',
        tech_flow2_title: 'PROMISE traite',
        tech_flow2_p: 'Le service backend Railway reçoit le message, détermine l\'état actuel et l\'envoie à OpenAI GPT.',
        tech_flow3_title: 'GPT répond',
        tech_flow3_p: 'Le modèle de langage génère une réponse empathique et sensible au contexte, basée sur l\'état actuel du Biographe.',
        tech_flow4_title: 'Supabase stocke',
        tech_flow4_p: 'La conversation et les réflexions extraites sont stockées de manière sécurisée dans ton instance personnelle Supabase, accessible uniquement par toi.',

        // Contact page
        contact_label: 'Contact',
        contact_h1: 'Restons<br>en contact.',
        contact_li_title: 'Dennis Riccardo',
        contact_li_sub: 'Créateur d\'Oblivio · Étudiant à la ZHAW',
        contact_li_cta: 'Voir le profil',
        contact_em_title: 'Email',
        contact_em_addr: 'riccaden@students.zhaw.ch',
        contact_info: '<strong>Contexte académique :</strong> Oblivio est un travail de bachelor à la <strong>ZHAW</strong> – Haute école zurichoise de sciences appliquées. Questions, retours ou propositions de collaboration sont les bienvenus.',

        // About page
        about_label: 'À propos d\'Oblivio',
        about_h1: 'Une personne.<br>Une idée.<br>Un héritage.',
        about_sub: 'Oblivio est né de la conviction que chaque personne mérite d\'être entendue et rappelée, bien au-delà de sa propre vie.',
        about_badge: 'Travail de bachelor',
        about_inst: '<strong>ZHAW – Haute école zurichoise de sciences appliquées</strong> · School of Management and Law · Informatique de gestion · 2026',
        about_role: 'Développeur · Étudiant',
        about_bio1: 'J\'étudie l\'informatique de gestion à la ZHAW à Winterthour, un programme qui me fascine depuis le début parce qu\'il relie deux mondes que j\'aime : la précision logique de la technologie et la réflexion stratégique du monde des affaires.',
        about_bio2: 'Parallèlement, je travaille comme chef de projet chez l\'un des plus grands assureurs maladie de Suisse. J\'y apprends chaque jour comment des systèmes complexes sont organisés, comment les gens sont dirigés et comment le changement est mis en œuvre durablement. C\'est un monde qui tourne beaucoup autour du soin, du bien-être de vraies personnes.',
        about_bio3: 'Oblivio est mon travail de bachelor. Mais plus que cela : c\'est le projet où tout ce que je défends se rejoint. L\'implémentation technique avec l\'IA et une infrastructure moderne. Le côté humain : les conversations, les souvenirs, le besoin de connexion à travers le temps. Et la conviction que la technologie doit servir les gens, et non l\'inverse.',
        about_bio4: 'Mon objectif avec Oblivio était de construire quelque chose qui non seulement fonctionne, mais qui sonne juste. Une plateforme qui traite avec dignité ce qu\'il y a de plus intime : la propre vie d\'une personne.',
        about_values_title: 'Ce qui anime Oblivio',
        about_v1_title: 'Dignité',
        about_v1_p: 'Chaque histoire mérite d\'être traitée avec respect, non pas comme un point de données, mais comme l\'œuvre d\'une vie humaine.',
        about_v2_title: 'Accessibilité',
        about_v2_p: 'Préserver sa propre vie ne devrait pas être une question d\'argent. Oblivio est gratuit, et c\'est un choix délibéré.',
        about_v3_title: 'Profondeur',
        about_v3_p: 'Des réponses superficielles mènent à des souvenirs superficiels. Le Biographe continue de poser des questions jusqu\'à ce que l\'essentiel remonte à la surface.',

        // Blog page
        blog_label: 'Blog',
        blog_h1: 'Comment Oblivio<br>est né.',
        blog_sub: 'Un récit honnête des décisions, des détours et des réflexions sur le chemin de l\'idée à la plateforme.',
        blog_date: 'Printemps 2026',
        blog_tag1: 'Travail de bachelor',
        blog_tag2: 'Développement',
        blog_art_h2: 'De l\'idée à la plateforme vivante : l\'histoire du développement d\'Oblivio',
        blog_art_lead: 'Que se passe-t-il quand on se demande : que reste-t-il d\'une personne quand elle n\'est plus là ? Oblivio a commencé avec cette question, et s\'est terminé par une réponse qui contient plus de décisions techniques que je ne l\'avais initialement prévu.',
        blog_h3_1: 'La question de départ',
        blog_p1_1: 'L\'idée d\'Oblivio n\'est pas née à un bureau, mais dans un moment de silence personnel : qu\'est-ce que je voudrais encore demander à une personne que j\'ai perdue ? Et inversement : qu\'est-ce que moi-même j\'aimerais laisser derrière moi quand je ne serai plus là ?',
        blog_p1_2: 'Ces questions m\'ont conduit à mon travail de bachelor. L\'objectif était ambitieux : une plateforme alimentée par l\'IA qui permet à chaque personne de documenter sa vie sous la forme d\'un héritage numérique, profond, personnel et durable.',
        blog_quote: '« Pas un formulaire. Pas un questionnaire. Une conversation qui écoute vraiment. »',
        blog_h3_2: 'PROMISE : Le cœur',
        blog_p2_1: 'L\'épine dorsale technologique d\'Oblivio est <strong>PROMISE</strong>, un framework de conversation basé sur des états développé à la ZHAW. Au lieu de simples séquences de chatbot, PROMISE permet de véritables états de conversation : chacun des dix blocs du Biographe est son propre état avec son propre contexte système, ses conditions de transition et son extraction automatique de connaissances.',
        blog_p2_2: 'Le défi central : quand un bloc passe-t-il au suivant ? La première solution était une double condition : l\'utilisateur devait explicitement dire « continuer », ET le guard devait confirmer que suffisamment de sujets avaient été couverts. Cela semble raisonnable, mais a conduit à un bug sérieux.',
        blog_technote: '<strong>Bug :</strong> <code>Transition(List.of(trigger, guard), ...)</code> — logique AND. Quand l\'utilisateur disait « non » (Trigger = true) après une longue conversation (Guard = true), <code>TransferUtterancesAction</code> était déclenché — et comme l\'historique complet de la conversation était transféré à tous les états suivants, TOUS les guards s\'évaluaient simultanément comme vrais. Le bloc 1 sautait directement à « Biographie terminée ».<br><br><strong>Solution :</strong> <code>Transition(List.of(guard), ...)</code> — Guard seul. Pas de trigger. Le passage se fait automatiquement une fois que suffisamment de réponses significatives ont été collectées.',
        blog_h3_3: 'Dix blocs au lieu d\'un seul',
        blog_p3_1: 'La version originale du Biographe était un seul état, un flux de conversation sans fin et sans structure. Le problème : sans guidage thématique, de nombreux domaines de la vie restaient inexplorés. Les utilisateurs parlaient de souvenirs d\'enfance, mais jamais de leurs valeurs. De leur travail, mais jamais de leurs rêves.',
        blog_p3_2: 'La solution a été de passer à dix blocs thématiques : Ice-Breaker (Geschmack & Vorlieben), Alltag & Lebenswelt, Kommunikationsstil, Erinnerungen & Schlüsselerlebnisse, Emotionen & Beziehungsmuster, Beziehungen & Fremdbild, Werte & Überzeugungen, Macken & Widersprüche, Vermächtnis & Zukunft et Abschluss. Chaque bloc est conçu pour explorer pleinement un domaine de vie spécifique, et ne passe automatiquement au suivant qu\'une fois terminé.',
        blog_h3_4: 'Frontend : entre fonction et dignité',
        blog_p4_1: 'Le design d\'Oblivio a suivi une prémisse claire : il ne devait pas ressembler à une application, mais à une lettre. La palette de couleurs (crème, charbon, rouge rouille, vert mousse) a été délibérément choisie pour transmettre chaleur et permanence. Les polices Crimson Pro et DM Serif Display apportent de la littérature dans l\'interface.',
        blog_p4_2: 'La barre de progression, qui apparaît après le bloc 1 et accompagne l\'utilisateur du bloc 1 au bloc 10, a été une petite mais significative décision UX : un progrès visible offre une orientation sans interrompre la conversation. Son état est sauvegardé dans le <code>localStorage</code> pour être préservé après un rafraîchissement.',
        blog_h3_5: 'Le questionnaire du bloc 0',
        blog_p5_1: 'Avant le début du Biographe proprement dit, l\'utilisateur passe par un court questionnaire : nom, tranche d\'âge, genre, situation matrimoniale, traits de personnalité et style de communication. Ces informations sont transmises au Biographe comme contexte. Il sait alors à qui il a affaire et peut adapter son ton, ses questions et ses réactions en conséquence.',
        blog_p5_2: 'Ce « bloc 0 » est disponible en sept langues (allemand, anglais, français, italien, coréen, japonais et chinois) et a été conçu pour être rapide, discret et honnête. Le formulaire de consentement qui le précède communique clairement ce qui est stocké et pourquoi.',
        blog_h3_6: 'Supabase, Railway & hébergement suisse',
        blog_p6_1: 'L\'infrastructure d\'Oblivio a été choisie selon un principe simple : chaque composant doit être le meilleur dans sa catégorie, bien fonctionner avec les autres et n\'ajouter aucune complexité inutile. Supabase pour l\'authentification et la base de données. Railway pour le service backend PROMISE avec auto-deploy à chaque git push. Un hébergeur suisse pour le frontend.',
        blog_p6_2: 'Railway s\'est avéré particulièrement précieux : chaque modification du backend Java (nouveaux guards, nouveaux prompts, nouveau support linguistique) est en ligne en quelques minutes. Cela a considérablement accéléré la vitesse d\'itération.',
        blog_h3_7: 'Ce qui a déjà été accompli',
        blog_p7_1: 'Oblivio a dépassé la vision initiale : le chat d\'héritage est actif — les proches peuvent utiliser un code d\'accès pour entrer en dialogue avec l\'héritage stocké. La synthèse vocale ElevenLabs donne au Biographe une voix audible, et grâce à la Web Speech API, les utilisateurs peuvent également dicter leurs réponses par saisie vocale.',
        blog_p7_2: 'Oblivio est terminé, mais pas fini. C\'est une plateforme qui s\'enrichit à chaque conversation qui y est menée.',
        blog_date_v2: '9 mai 2026',
        blog_tag_v2_1: 'Mise à jour',
        blog_tag_v2_2: 'Itération',
        blog_v2_h2: 'De quatre à huit langues : la grande refonte',
        blog_v2_lead: 'Ces dernières semaines, Oblivio a grandi. Pas seulement dans le nombre de personas, mais aussi dans la profondeur de ses fonctionnalités. Voici un aperçu des changements les plus importants.',
        blog_v2_h3_1: 'Huit langues au lieu de quatre',
        blog_v2_p1: 'Oblivio prend désormais en charge huit langues : allemand, anglais, français, italien, turc, coréen, japonais et chinois. Le turc a été ajouté comme huitième langue afin d\'élargir encore la portée internationale. Pour cela, tous les textes de l\'interface, le questionnaire du Biographe et les instructions de blocs ont été complétés.',
        blog_v2_h3_2: 'Trois variantes de conversation',
        blog_v2_p2_1: 'Les personas legacy peuvent désormais être interrogées selon trois modes différents : la variante 1 propose une analyse complète de la personnalité avec diagramme radar, ADN de communication et schémas de vie. La variante 2 laisse la persona ouvrir activement la conversation. La variante 3 attend silencieusement le premier message du visiteur.',
        blog_v2_p2_2: 'Chaque variante convient à une situation émotionnelle différente : compréhension profonde, faible barrière d\'entrée ou contrôle total sur le début de la conversation.',
        blog_v2_h3_3: 'Compaction automatique du contexte',
        blog_v2_p3: 'Une amélioration technique dans le backend PROMISE : après vingt messages de l\'utilisateur, les anciens échanges sont automatiquement résumés et remplacés par un message système compact. Les coûts en tokens restent ainsi constants, tandis que les contenus les plus importants sont préservés — un peu comme la mémoire humaine qui laisse les détails s\'estomper mais conserve la vue d\'ensemble.',
        blog_v2_h3_4: 'Progrès visibles et travail de fond invisible',
        blog_v2_p4_1: 'En coulisses, de nombreux composants ont été affinés : le dépôt a été restructuré (dossiers distincts pour la documentation et les scripts SQL), toutes les classes Java ont reçu des commentaires détaillés et les textes obsolètes du site web ont été mis à jour.',
        blog_v2_p4_2: 'La page des personnes a également été retravaillée : les anciennes références à des noms de personas spécifiques ont été remplacées par des formulations génériques afin que la plateforme reste cohérente avec les futures personas.',
        blog_v2_h3_5: '15 participants, nouvelles personas, nouvelles voix',
        blog_v2_p5: 'Au total, 15 personnes ont participé à l\'étude et ont partagé leur histoire de vie avec le Biographe. Chacune de ces histoires est devenue sa propre persona — avec sa propre photo de profil, sa propre voix via ElevenLabs et un prompt système en trois parties pour les trois variantes de conversation. La plateforme a gagné en diversité — différentes langues, tranches d\'âge et parcours de vie s\'y rencontrent.',
        blog_v2_p_final: 'Oblivio continue d\'évoluer — non pas d\'un grand bond, mais à travers de nombreuses petites améliorations, qui rendent chacune à leur manière la conversation plus authentique et plus humaine.',

        // Terms page
        terms_label: 'Mentions légales',
        terms_h1: 'Conditions d\'utilisation',
        terms_updated: 'En vigueur depuis : janvier 2026',
        terms_highlight: 'Oblivio est un projet de recherche académique dans le cadre d\'un travail de bachelor à la ZHAW – Haute école zurichoise de sciences appliquées. En utilisant cette plateforme, tu acceptes les présentes conditions d\'utilisation.',
        terms_s1_title: '1. Nature du service',
        terms_s1_p1: 'Oblivio est une plateforme académique non commerciale développée dans le cadre d\'un travail de bachelor à la ZHAW. Le service est mis à la disposition du public gratuitement et sans but lucratif.',
        terms_s1_p2: 'La plateforme est en développement actif. Les fonctionnalités, la disponibilité et le contenu peuvent changer à tout moment. Il n\'y a aucune garantie de fonctionnement permanent.',
        terms_s2_title: '2. Utilisation autorisée',
        terms_s2_p1: 'Tu peux utiliser Oblivio pour :',
        terms_s2_list1: '<li>Documenter ton héritage numérique personnel</li><li>Mener des conversations avec le Biographe IA</li><li>Récupérer et gérer ton contenu stocké</li>',
        terms_s2_p2: 'L\'utilisation suivante n\'est pas autorisée :',
        terms_s2_list2: '<li>Requêtes de masse automatisées ou abus d\'API</li><li>Saisie de contenu illégal, offensant ou nuisible</li><li>Tentatives d\'accès aux données d\'autrui ou de contournement des mesures de sécurité</li><li>Fins commerciales de quelque nature que ce soit sans autorisation écrite</li>',
        terms_s3_title: '3. Ton contenu',
        terms_s3_p1: 'Tout le contenu que tu saisis dans Oblivio (conversations, réponses, informations de profil) reste ta propriété intellectuelle. Tu accordes à Oblivio le droit de traiter et de stocker ce contenu pour le fonctionnement technique du service.',
        terms_s3_p2: 'À des fins de recherche académique, les schémas de conversation et le comportement d\'utilisation peuvent être évalués sous <strong>forme entièrement anonymisée</strong>. Des déductions sur des personnes individuelles ne sont ni prévues ni possibles.',
        terms_s4_title: '4. Clause de non-responsabilité',
        terms_s4_p1: 'Oblivio est fourni « en l\'état ». Aucune garantie n\'est donnée quant à la disponibilité ininterrompue, l\'absence d\'erreurs ou le stockage permanent des données. En tant que projet académique, le service peut être interrompu, modifié ou restreint à tout moment.',
        terms_s4_p2: 'Les réponses générées par l\'IA du Biographe servent exclusivement à la réflexion personnelle et à la documentation. Elles ne constituent pas des conseils psychologiques, médicaux ou juridiques.',
        terms_s5_title: '5. Propriété intellectuelle',
        terms_s5_p1: 'Le design, le code, les textes et tout autre contenu de la plateforme Oblivio (à l\'exception du contenu utilisateur) sont protégés par le droit d\'auteur et sont la propriété de Dennis Riccardo. Toute utilisation ou reproduction, même partielle, sans autorisation écrite est interdite.',
        terms_s6_title: '6. Prestataires tiers',
        terms_s6_p1: 'Oblivio utilise des services externes (notamment OpenAI, Supabase, Railway et un hébergeur suisse) dont les prestataires respectifs sont responsables de la confidentialité et des conditions d\'utilisation. En utilisant Oblivio, tu acceptes implicitement l\'utilisation de ces services dans la mesure où ils sont nécessaires au fonctionnement.',
        terms_s7_title: '7. Modifications',
        terms_s7_p1: 'Les présentes conditions d\'utilisation peuvent être modifiées à tout moment. Les changements significatifs seront indiqués sur la plateforme. L\'utilisation continue après une modification vaut acceptation.',
        terms_s8_title: '8. Contact',
        terms_s8_p1: 'Pour toute question concernant les présentes conditions d\'utilisation : <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',

        // Privacy page
        priv_label: 'Mentions légales',
        priv_h1: 'Politique de confidentialité',
        priv_updated: 'En vigueur depuis : janvier 2026',
        priv_s1_title: '1. Responsable',
        priv_s1_p1: 'Le responsable du traitement des données sur cette plateforme est :',
        priv_s1_p2: '<strong>Dennis Riccardo</strong><br>Étudiant, ZHAW – Haute école zurichoise de sciences appliquées<br>Email : <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s1_p3: 'Oblivio est un projet de recherche académique dans le cadre d\'un travail de bachelor. Ce n\'est pas une entreprise commerciale.',
        priv_s2_title: '2. Quelles données nous collectons',
        priv_s2_p1: 'Oblivio collecte exclusivement les données nécessaires au fonctionnement du service :',
        priv_s2_list: '<li><strong>Données d\'inscription :</strong> Adresse email, nom complet, mot de passe (stocké sous forme de hachage bcrypt)</li><li><strong>Données de profil :</strong> Surnom, tranche d\'âge, genre, situation matrimoniale, traits de personnalité, style de communication — fournis volontairement dans le questionnaire avant la conversation</li><li><strong>Contenu des conversations :</strong> Tous les messages que tu écris dans la conversation avec le Biographe</li><li><strong>Préférence linguistique :</strong> Ta langue choisie (DE, EN, IT, KO), stockée dans le localStorage du navigateur</li>',
        priv_s2_p2: '<strong>Aucune</strong> donnée de localisation, empreinte d\'appareil, adresse IP (à des fins d\'identification personnelle), cookie à des fins publicitaires ou donnée comportementale n\'est collectée.',
        priv_s3_title: '3. Finalité du traitement des données',
        priv_s3_p1: 'Les données collectées sont utilisées exclusivement aux fins suivantes :',
        priv_s3_list: '<li>Fonctionnement de la plateforme et mise à disposition de la conversation avec le Biographe</li><li>Personnalisation du Biographe IA en fonction de tes informations de profil</li><li>Stockage de ton héritage numérique pour une consultation ultérieure</li><li>Authentification et sécurisation de ton compte</li><li>Recherche académique et évaluation dans le cadre du travail de bachelor (anonymisé)</li>',
        priv_s4_title: '4. Communication à des tiers',
        priv_s4_p1: 'Tes données ne sont <strong>pas</strong> vendues, louées ou transmises à des fins publicitaires. Les prestataires tiers suivants sont utilisés pour le fonctionnement de la plateforme :',
        priv_s4_list: '<li><strong>Supabase</strong> (base de données et authentification) — les données sont traitées conformément aux politiques de confidentialité de Supabase</li><li><strong>OpenAI</strong> (GPT API) — les messages de conversation sont transmis pour traitement ; OpenAI ne les utilise pas pour l\'entraînement de modèles conformément au contrat</li><li><strong>Railway</strong> (infrastructure backend) — traitement des requêtes API sans stockage permanent de données</li><li><strong>Hébergeur suisse</strong> (hébergement web, Suisse) — diffusion de fichiers statiques</li>',
        priv_s5_title: '5. Sécurité des données',
        priv_s5_p1: 'Toutes les transmissions entre le navigateur et le serveur sont chiffrées par TLS. Les mots de passe sont stockés sous forme de hachage bcrypt. Le Row Level Security (RLS) de Supabase garantit qu\'aucun utilisateur ne peut accéder aux données d\'un autre. L\'accès à la base de données se fait exclusivement via des tokens JWT signés.',
        priv_s6_title: '6. Tes droits',
        priv_s6_p1: 'Tu as le droit de :',
        priv_s6_list: '<li><strong>Information :</strong> Demander quelles données sont stockées te concernant</li><li><strong>Rectification :</strong> Correction de données incorrectes</li><li><strong>Suppression :</strong> Suppression complète et irréversible de toutes tes données</li><li><strong>Portabilité des données :</strong> Mise à disposition de tes données dans un format lisible par machine</li><li><strong>Opposition :</strong> Opposition à certaines finalités de traitement</li>',
        priv_s6_p2: 'Pour exercer ces droits, contacte : <a href="mailto:riccaden@students.zhaw.ch">riccaden@students.zhaw.ch</a>',
        priv_s7_title: '7. Durée de conservation',
        priv_s7_p1: 'Tes données seront conservées aussi longtemps que ton compte est actif. Après une demande de suppression, toutes les données seront entièrement supprimées dans un délai de 7 jours ouvrables. Après la conclusion du projet académique, toutes les données personnelles seront supprimées ; les résultats d\'évaluation anonymisés peuvent rester dans le travail de bachelor.',
        priv_s8_title: '8. Droit applicable',
        priv_s8_p1: 'La présente politique de confidentialité est régie par la loi suisse sur la protection des données (nLPD). Étant donné qu\'Oblivio peut également attirer des utilisateurs de l\'UE, les principes du RGPD sont respectés dans la mesure du possible.',

        // Beta Page
        hero_beta_cta: 'Deviens bêta-testeur',
        beta_cta_title: 'Façonne le futur de demain.',
        beta_cta_desc: 'Oblivio est en phase de test. Réserve ta place maintenant et aide-nous à construire une plateforme qui rend les histoires immortelles.',
        beta_label: 'Deviens testeur',
        beta_title: 'Fais partie<br>de l\'histoire.',
        beta_subtitle: 'Oblivio est en phase de test. Sois parmi les premiers à préserver ton héritage et contribue à façonner l\'avenir de la plateforme.',
        beta_benefit1_title: 'Accès anticipé',
        beta_benefit1_desc: 'Essaie Oblivio avant son lancement public et sois le premier à découvrir comment l\'IA préserve ton héritage.',
        beta_benefit2_title: 'Façonne l\'avenir',
        beta_benefit2_desc: 'Tes retours façonnent l\'avenir de la plateforme. Chaque réponse nous aide à améliorer Oblivio.',
        beta_benefit3_title: 'Gratuit',
        beta_benefit3_desc: 'Accès complet sans aucun coût. Nous croyons que la préservation de l\'héritage devrait être accessible à tous.',
        beta_form_title: 'Inscris-toi et rejoins-nous.',
        beta_form_desc: 'Inscris-toi et nous te contacterons dès que ton accès sera prêt. Pas de spam, promis.',
        beta_name_label: 'Nom',
        beta_email_label: 'Email',
        beta_name_placeholder: 'Ton nom',
        beta_email_placeholder: 'ton@email.com',
        beta_submit: 'S\'inscrire maintenant',
        beta_submitting: 'Envoi en cours...',
        beta_success: 'Merci ! Nous te recontacterons.',
        beta_error: 'Une erreur est survenue. Réessaie s\'il te plaît.',
        beta_duplicate: 'Cet email est déjà enregistré.',
        beta_privacy_note: 'En t\'inscrivant, tu acceptes nos <a href="terms.html">conditions d\'utilisation</a> et notre <a href="privacy.html">politique de confidentialité</a>.',

        // Page titles
        page_title_index: 'Oblivio – Au-delà de la mémoire',
        page_title_about: 'À propos – Oblivio',
        page_title_features: 'Technologie – Oblivio',
        page_title_blog: 'Blog – Oblivio',
        page_title_faq: 'FAQ – Oblivio',
        page_title_pricing: 'Tarifs – Oblivio',
        page_title_security: 'Sécurité – Oblivio',
        page_title_contact: 'Contact – Oblivio',
        page_title_journey: 'Ton parcours – Oblivio',
        page_title_biographer: 'Biographe – Oblivio',
        page_title_login: 'Connexion – Oblivio',
        page_title_signup: 'Inscription – Oblivio',
        page_title_privacy: 'Confidentialité – Oblivio',
        page_title_terms: 'Conditions d\'utilisation – Oblivio',
        page_title_404: 'Page non trouvée – Oblivio',
        page_title_legacy: 'Héritage – Oblivio',

        // Legacy Chat
        legacy_title: 'Vivre un héritage',
        legacy_subtitle: 'Entre le code d\'accès pour parler avec un héritage.',
        legacy_code_placeholder: 'Code d\'accès',
        legacy_connect_btn: 'Se connecter',
        legacy_invalid_code: 'Code invalide. Veuillez réessayer.',
        legacy_no_data: 'Aucune donnée d\'héritage trouvée.',
        legacy_error: 'Une erreur est survenue. Veuillez réessayer.',
        legacy_loading: 'Connexion en cours...',
        legacy_chat_title: 'Conversation avec',
        legacy_chat_subtitle: 'Une conversation avec l\'héritage de {name}',
        legacy_input_placeholder: 'Écris un message...',
        legacy_ended: 'La conversation est terminée.',
        legacy_send_error: 'Le message n\'a pas pu être envoyé. Veuillez réessayer.',
        // Legacy Visitor Info
        legacy_visitor_title: 'Avant de commencer',
        legacy_visitor_subtitle: 'Pour que la conversation soit plus personnelle.',
        legacy_visitor_name_label: 'Comment {name} doit-il/elle t\'appeler ?',
        legacy_visitor_name_placeholder: 'Ton prénom',
        legacy_visitor_relation_label: 'Quelle est ta relation avec {name} ?',
        legacy_visitor_relation_placeholder: 'Choisir...',
        legacy_visitor_rel_spouse: 'Conjoint(e)',
        legacy_visitor_rel_child: 'Enfant',
        legacy_visitor_rel_parent: 'Parent',
        legacy_visitor_rel_sibling: 'Frère/Sœur',
        legacy_visitor_rel_grandchild: 'Petit-enfant',
        legacy_visitor_rel_friend: 'Ami(e)',
        legacy_visitor_rel_relative: 'Parent(e)',
        legacy_visitor_rel_other: 'Autre',
        legacy_visitor_gender_label: 'Genre',
        legacy_visitor_gender_placeholder: 'Choisir...',
        legacy_visitor_gender_male: 'Homme',
        legacy_visitor_gender_female: 'Femme',
        legacy_visitor_gender_other: 'Autre',
        legacy_visitor_start: 'Commencer la conversation',
        legacy_visitor_required: 'Veuillez remplir tous les champs.',
        // Legacy Conversation Mode
        legacy_mode_active: 'Variante 2',
        legacy_mode_passive: 'Variante 3',
        legacy_mode_analysis: 'Variante 1',
        legacy_passive_hint: 'Écris un message à {name} pour commencer la conversation…',
        legacy_mode_switch_confirm: 'Changer de mode ? La conversation actuelle sera redémarrée.',

        // Biographer Completion — Access Code
        bio_complete_code_desc: 'Partage ce code avec tes proches :',
        bio_complete_code_copy: 'Copier le code',
        bio_complete_code_copied: 'Copié !',
        bio_complete_code_email: 'Partager par e-mail',
        bio_complete_email_subject: 'Ton code d\'accès Oblivio pour',
        bio_complete_email_greeting: 'Bonjour',
        bio_complete_email_line1: 'La biographie a été complétée avec succès !',
        bio_complete_email_line2: 'Code d\'accès :',
        bio_complete_email_line3: 'Visite cette page pour parler avec l\'héritage :',

        // Journey — Access Code
        journey_your_code: 'Ton code d\'accès',
        journey_code_desc: 'Partage ce code avec tes proches pour qu\'ils puissent parler avec ton héritage.',
        journey_email_code: 'Partager par e-mail'
};
